### ISSUE TITLE
SQLITE_ERROR

### ISSUE THREAD

**Issue by brunyman** [Zrips/Jobs#1]
Just installed this from scratch in spigot 1.8, we use sqlite for data storage, the plugin generated the database but wen we try to join a job we get this error, as result after a server restart the job selected will be lost.
Full server log: http://pastebin.com/0yJiZfE7

[08:51:05] [Server thread/INFO]: brunyman[/127.0.0.1:50580] logged in with entity id 99 at ([world] -41.58015517137273, 68.0, -21.76193990700618)
[08:51:16] [Server thread/INFO]: brunyman issued server command: /jobs stats
[08:51:21] [Server thread/INFO]: brunyman issued server command: /jobs join miner
[08:51:21] [Server thread/WARN]: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (table jobs has no column named username)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:404)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:399)
[08:51:21] [Server thread/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:383)
[08:51:21] [Server thread/WARN]: 	at com.gamingmesh.jobs.dao.JobsConnection.prepareStatement(JobsConnection.java:58)
[08:51:21] [Server thread/WARN]: 	at com.gamingmesh.jobs.dao.JobsDAO.joinJob(JobsDAO.java:146)
[08:51:21] [Server thread/WARN]: 	at com.gamingmesh.jobs.PlayerManager.joinJob(PlayerManager.java:151)
[08:51:21] [Server thread/WARN]: 	at com.gamingmesh.jobs.commands.JobsCommands.join(JobsCommands.java:193)
[08:51:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:51:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:51:21] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:51:21] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:51:21] [Server thread/WARN]: 	at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:70)
[08:51:21] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:51:21] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:51:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[08:51:21] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[08:51:21] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[08:51:21] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[08:51:21] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Zrips** [comment]
Now its should be ok, at least with sqlite part

**Comment by brunyman** [comment]
yes, this problem is fixed :P , another problem looks like you don't get exp and money when you break/place blocks that should give rewards, should i make a new post?

**Comment by Zrips** [comment]
ok ok, shut... i think i pushed plugin with my test code for place and brake protection. just some simple code to protect from placing same block and breaking again. I think this is "issue" you are getting right now

**Comment by brunyman** [comment]
ok, now it works, i get the money and experience, BUT there is another issue now, after a server restart all jobs progress is lost, it's like it's nothing saved to the database

**Comment by Zrips** [comment]
ok, i will need some more info, like server version, java version, what storing mode you are using sqlite or mysql and are you getting any errors connected with jobs plugin when starting or stooping server

**Comment by Zrips** [comment]
Just keep in mind that data are saved every 10min (by default), so if you are testing something, just wait at least 10min before restarting server

**Comment by Zrips** [comment]
Ok ok, found issue. Now this should work correctly
