### ISSUE TITLE
Error on server startup

### ISSUE THREAD

**Issue by T1MOXA** [Zrips/Jobs#100]
```
[Server thread/ERROR]: Cannot load configuration from stream
java.io.IOException: Stream closed
	at sun.nio.cs.StreamDecoder.ensureOpen(StreamDecoder.java:46) ~[?:1.8.0_111]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:148) ~[?:1.8.0_111]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_111]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_111]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_111]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_111]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:154) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:207) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at com.gamingmesh.jobs.config.YmlMaker.reloadConfig(YmlMaker.java:56) [Jobs3.9.3.jar:?]
	at com.gamingmesh.jobs.config.YmlMaker.getConfig(YmlMaker.java:75) [Jobs3.9.3.jar:?]
	at com.gamingmesh.jobs.i18n.Language.reload(Language.java:41) [Jobs3.9.3.jar:?]
	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:792) [Jobs3.9.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Zrips** [comment]
Will be fixed with next build
