### ISSUE TITLE
Could not pass event BlockBreakEvent to Jobs v3.9.4

### ISSUE THREAD

**Issue by DmitryRendov** [Zrips/Jobs#103]
Hi guys, I have such trace sometimes:
`[07:03:53] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Jobs v3.9.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:289) [spigot-survival-1.12.jar:git-Spigot-b78586                                        d-753a8e7]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:216) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7                                        ]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:882) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at com.gamingmesh.jobs.Jobs.isBpOk(Jobs.java:1118) ~[?:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:878) ~[?:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:858) ~[?:?]
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:305) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-survival-1.12.jar:git-Spigot-b78586d-753a8e7]
        ... 17 more
`
Any advice how to avoid them?
Thank you in advance!

**Comment by DmitryRendov** [comment]
just fyi, still reproducible in 3.9.6

**Comment by Killdore** [comment]
I've got the same problem.
