### ISSUE TITLE
I have some Warning in my console 

### ISSUE THREAD

**Issue by Flearl** [Zrips/Jobs#1037]
***Description of issue:**
When I use the Woodcutter job, warnings appear in the console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[06:34:03 WARN]: java.lang.NumberFormatException: For input string: "[amount]"
[06:34:03 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[06:34:03 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[06:34:03 WARN]:        at java.base/java.lang.Double.parseDouble(Double.java:543)
[06:34:03 WARN]:        at com.gamingmesh.jobs.PermissionManager.getMaxPermission(PermissionManager.java:154)
[06:34:03 WARN]:        at com.gamingmesh.jobs.container.JobsPlayer.getPlayerBoostNew(JobsPlayer.java:296)
[06:34:03 WARN]:        at com.gamingmesh.jobs.container.JobsPlayer.getBoost(JobsPlayer.java:265)
[06:34:03 WARN]:        at com.gamingmesh.jobs.PlayerManager.getBoost(PlayerManager.java:811)
[06:34:03 WARN]:        at com.gamingmesh.jobs.PlayerManager.getBoost(PlayerManager.java:801)
[06:34:03 WARN]:        at com.gamingmesh.jobs.PlayerManager.getFinalBonus(PlayerManager.java:997)
[06:34:03 WARN]:        at com.gamingmesh.jobs.PlayerManager.getFinalBonus(PlayerManager.java:951)
[06:34:03 WARN]:        at com.gamingmesh.jobs.Jobs.action(Jobs.java:1029)
[06:34:03 WARN]:        at com.gamingmesh.jobs.Jobs.action(Jobs.java:854)
[06:34:03 WARN]:        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:418)
[06:34:03 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor707.execute(Unknown Source)
[06:34:03 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[06:34:03 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[06:34:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[06:34:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:283)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:249)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1485)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[06:34:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[06:34:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)


---

**Server Type (Spigot/Paperspigot/etc):** 
paper-1.16.4-345
**Server Version (using `/ver`):** 
Version 1.16.4

**Comment by montlikadani** [comment]
You literally copied the `jobs.max.[number]` and added to permissions which is invalid.

**Comment by Flearl** [comment]
Thanks it has work the warning ist not coming again

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: montlikadani<mailto:notifications@github.com>
Gesendet: Freitag, 1. Januar 2021 15:44
An: Zrips/Jobs<mailto:Jobs@noreply.github.com>
Cc: Flearl<mailto:florian_ebert96@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Zrips/Jobs] I have some Warning in my console (#1037)


You literally copied the jobs.max.[number] and added to permissions which is invalid.
