### ISSUE TITLE
IllegalPluginAccessException

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#104]
```
[09:00:01] [Server thread/INFO]: [Jobs] Disabling Jobs v3.9.3
[09:00:01] [Server thread/INFO]: [Jobs] Saving blocks
[09:00:01] [Jobs-BufferedPaymentThread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[09:00:01] [Jobs-BufferedPaymentThread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413)
[09:00:01] [Jobs-BufferedPaymentThread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:148)
[09:00:01] [Jobs-BufferedPaymentThread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:122)
[09:00:01] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:190)
[09:00:01] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:55)
[09:00:01] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Exception in BufferedPaymentThread, stopping economy payments!
[09:00:01] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.
[09:00:01] [Server thread/INFO]: [Jobs] Added 3100 new block protection entries.
[09:00:01] [Server thread/INFO]: [Jobs] Deleted 985 old block protection entries.
```

**Comment by montlikadani** [comment]
**Try update to the latest version.**
