### ISSUE TITLE
NullPointerException on PlayerJoinEvent

### ISSUE THREAD

**Issue by UmbreonMajora** [Zrips/Jobs#1075]
***Description of issue:***
When a player joins the server a NullPointerException comes up.
I also tried with the current version 4.17.0 but the same error appears.
---

**ERROR:**
```
[14:14:21] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Jobs v4.17.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:200) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:154) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:53) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:219) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1127) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
        at org.bukkit.plugin.SimplePluginManager.getPermission(SimplePluginManager.java:686) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:196) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:204) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:175) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.recalculatePermissions(CraftHumanEntity.java:224) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at org.bukkit.permissions.PermissionAttachment.setPermission(PermissionAttachment.java:93) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        at com.gamingmesh.jobs.PermissionHandler.recalculatePermissions(PermissionHandler.java:225) ~[?:?]
        at com.gamingmesh.jobs.PlayerManager.playerJoin(PlayerManager.java:214) ~[?:?]
        at com.gamingmesh.jobs.listeners.JobsListener.onPlayerJoin(JobsListener.java:167) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.5.jar:git-Spigot-138d451-085fe67]
        ... 14 more
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.16.5-R0.1-SNAPSHOT

**Comment by montlikadani** [comment]
>  at com.gamingmesh.jobs.PermissionHandler.recalculatePermissions(PermissionHandler.java:225) ~[?:?]
at com.gamingmesh.jobs.PlayerManager.playerJoin(PlayerManager.java:214) ~[?:?]
at com.gamingmesh.jobs.listeners.JobsListener.onPlayerJoin(JobsListener.java:167) ~[?:?]


This error refers to this:
https://github.com/Zrips/Jobs/blob/865bcca5c0014171c916a02d61c86900a311858f/src/main/java/com/gamingmesh/jobs/PermissionHandler.java#L224

`permName` and `attachment` can't be null (never). Resolution: update your server software with BuildTools and use a permission plugin.
