### ISSUE TITLE
Error when disconnected

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#1084]
Hello, on spigot 1.16.5 when a player leave in few time after taking a job we have this error : 

[16:12:31] [Craft Scheduler Thread - 263/WARN]: [Jobs] Plugin Jobs v4.17.0 generated an exception while executing task 868475
java.lang.NullPointerException: null
        at com.gamingmesh.jobs.dao.JobsDAO.joinJob(JobsDAO.java:1453) ~[?:?]
        at com.gamingmesh.jobs.PlayerManager.lambda$joinJob$0(PlayerManager.java:396) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_281]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

Jobs : 4.17.0

**Comment by montlikadani** [comment]
Seems to be this already fixed. Join our discord server and install new version from `#dev-releases` channel.
