### ISSUE TITLE
Async Scoreboard Creation Error

### ISSUE THREAD

**Issue by EndaarF** [Zrips/Jobs#1090]
Running Jobs 4.16.3 on Paper 1.16.4 and receiving this error in the logs:

[09:27:38] [Craft Scheduler Thread - 6224/WARN]: [Jobs] Plugin Jobs v4.16.3 generated an exception while executing task 1877583
java.lang.IllegalStateException: Asynchronous scoreboard creation!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.4.jar:git-Paper-386]
at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:45) ~[patched_1.16.4.jar:git-Paper-386]
at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:25) ~[patched_1.16.4.jar:git-Paper-386]
at com.ue.common.utils.ServerProvider.createScoreBoard(ServerProvider.java:128) ~[?:?]
at com.ue.economyplayer.logic.impl.EconomyPlayerImpl.setScoreboard(EconomyPlayerImpl.java:302) ~[?:?]
at com.ue.economyplayer.logic.impl.EconomyPlayerImpl.updateScoreBoard(EconomyPlayerImpl.java:316) ~[?:?]
at com.ue.economyplayer.logic.impl.EconomyPlayerImpl.increasePlayerAmount(EconomyPlayerImpl.java:241) ~[?:?]
at com.ue.vault.impl.UltimateEconomyVaultImpl.depositPlayer(UltimateEconomyVaultImpl.java:69) ~[?:?]
at com.ue.vault.impl.UltimateEconomyVaultImpl.depositPlayer(UltimateEconomyVaultImpl.java:58) ~[?:?]
at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:33) ~[?:?]
at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:41) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-386]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-386]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-386]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

4.16.0 and 4.16.1 both crash on startup on 1.16.4/5 so I can't roll back to them. 4.16.2 and 4.16.3 both show the same error.

I'm not really sure what impact this is having. Jobs are apparently working as they should, but this is a lot of spam in the logs. Would appreciate some feedback. Thanks.

**Comment by montlikadani** [comment]
Jobs 4.16.3 - old version
```
at com.ue.common.utils.ServerProvider.createScoreBoard(ServerProvider.java:128) ~[?:?]
at com.ue.economyplayer.logic.impl.EconomyPlayerImpl.setScoreboard(EconomyPlayerImpl.java:302) ~[?:?]
at com.ue.economyplayer.logic.impl.EconomyPlayerImpl.updateScoreBoard(EconomyPlayerImpl.java:316) ~[?:?]
at com.ue.economyplayer.logic.impl.EconomyPlayerImpl.increasePlayerAmount(EconomyPlayerImpl.java:241) ~[?:?]
at com.ue.vault.impl.UltimateEconomyVaultImpl.depositPlayer(UltimateEconomyVaultImpl.java:69) ~[?:?]
at com.ue.vault.impl.UltimateEconomyVaultImpl.depositPlayer(UltimateEconomyVaultImpl.java:58) ~[?:?]
```
^ and this not our issue. It is your EconomyPlayer/UltimateEconomy ask the author of that resource.
