### ISSUE TITLE
Not work gui translate

### ISSUE THREAD

**Issue by andris155** [Zrips/Jobs#11]
A translated gui section, and not work. Write error code:
[20:44:58] [Server thread/ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 92, column 7:
          pickjob: '&eVรกlaszd ki a munkรกd!'
          ^
expected <block end>, but found Scalar
 in 'string', line 139, column 16:
            none: 'A(z) %jobname% munka nem ad pรฉnz ... 
                   ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:240) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at com.gamingmesh.jobs.config.YmlMaker.reloadConfig(YmlMaker.java:48) [Jobs2.54.2.jar:?]
	at com.gamingmesh.jobs.config.YmlMaker.getConfig(YmlMaker.java:67) [Jobs2.54.2.jar:?]
	at com.gamingmesh.jobs.i18n.Language.reload(Language.java:48) [Jobs2.54.2.jar:?]
	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:210) [Jobs2.54.2.jar:?]
	at com.gamingmesh.jobs.commands.JobsCommands.reload(JobsCommands.java:698) [Jobs2.54.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:93) [Jobs2.54.2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 92, column 7:
          pickjob: '&eVรกlaszd ki a munkรกd!'
          ^
expected <block end>, but found Scalar
 in 'string', line 139, column 16:
            none: 'A(z) %jobname% munka nem ad pรฉnz ... 
                   ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot_1.8.jar:git-PaperSpigot-0d986bb-18fbb24]
	... 21 more

**Comment by Zrips** [comment]
Paste your yml over http://yaml-online-parser.appspot.com/ and check for incorrect spelling.

**Comment by andris155** [comment]
Fixed.
Not work translations in gui:
smelt, fish, craft etc...
leftClick: '&eBal klikk: Infó a munkáról'
rightClick: '&eJobb klikk: Belépés a munkába'
