### ISSUE TITLE
Console Spam due to Jobs and Craftconomy

### ISSUE THREAD

**Issue by chrisraj1** [Zrips/Jobs#1111]
***Description of issue:**
I am having an issue that deals with Jobs Reborn and Craftconomy. Every time a Jobs action is performed (mining a block with miner job, breaking dirt with digger, etc.), a warning pops up followed by about 10 lines of unreadable spam. If someone is actively mining this happens about once a second. I talked to Zrips and he said it is because Craftconomy is no longer supported and I should open a ticket. I am try to figure out which one I should get and which ones will be compatible with my server. I have a towny server with plugins such as dtl traders, auction house, areashop, and chestshop.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## [20:45:35 WARN]: [Jobs] Plugin Jobs v4.17.1 generated an exception while executing task 1162545
java.lang.IllegalStateException: EconomyChangeEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[server.jar:git-Paper-534]
        at com.greatmancode.craftconomy3.tools.caller.bukkit.BukkitServerCaller.throwEvent(BukkitServerCaller.java:152) ~[?:?]
        at com.greatmancode.craftconomy3.account.Account.deposit(Account.java:171) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:311) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:131) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:54) ~[?:?]
        at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:33) ~[?:?]
        at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[server.jar:git-Paper-534]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[server.jar:git-Paper-534]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-534]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[20:45:35 INFO]: [Chunky] Task running for world. Processed: 717097 chunks (19.51%), ETA: 12:40:04, Rate: 64.9 cps, Current: -820, 117
[20:45:36 INFO]: [Chunky] Task running for world. Processed: 717150 chunks (19.51%), ETA: 12:05:04, Rate: 68.0 cps, Current: -820, 171
[20:45:37 INFO]: [Chunky] Task running for world. Processed: 717197 chunks (19.51%), ETA: 11:49:00, Rate: 69.5 cps, Current: -820, 217
[20:45:38 INFO]: [Chunky] Task running for world. Processed: 717236 chunks (19.51%), ETA: 11:44:23, Rate: 70.0 cps, Current: -820, 256
[20:45:39 INFO]: [Chunky] Task running for world. Processed: 717282 chunks (19.51%), ETA: 12:14:52, Rate: 67.1 cps, Current: -820, 302
[20:45:40 WARN]: [Jobs] Plugin Jobs v4.17.1 generated an exception while executing task 1164009
java.lang.IllegalStateException: EconomyChangeEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[server.jar:git-Paper-534]
        at com.greatmancode.craftconomy3.tools.caller.bukkit.BukkitServerCaller.throwEvent(BukkitServerCaller.java:152) ~[?:?]
        at com.greatmancode.craftconomy3.account.Account.deposit(Account.java:171) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:311) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:131) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:54) ~[?:?]
        at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:33) ~[?:?]
        at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[server.jar:git-Paper-534]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[server.jar:git-Paper-534]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-534]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282].##
####################
```
---

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 534 (1.16.5)
**Relevant plugins (Delete if this isn't needed):**
Dtl traders, area shop, auction house, chest shop, towny, craftconomy 3

**Comment by montlikadani** [comment]
CraftConomy is not updated since 2017. You have to change to another bank/economy provider, or trying to use EssentialsX or CMI with Vault.

**Comment by Geolykt** [comment]
EssX did not work with Towny last time I checked (which was Novemeber of last year, so it could be outdated information)
