### ISSUE TITLE
Legacy material gets triggered upon startup of the plugin

### ISSUE THREAD

**Issue by KoxSosen** [Zrips/Jobs#1151]
***Detailed description of the issue:**

Minecraft's Legacy Materials gets triggered when the plugin hooks into placeholderapi:

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[11:56:53 INFO]: [Jobs] PlaceholderAPI hooked.
[11:56:54 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
```

```
####################
## PASTE ERROR HERE ##
####################
```

--

**Jobs version: compiled version from this commit: 
https://github.com/Zrips/Jobs/commit/3239b5decf849a8ea941fe9d54db38c7b296cd45 ** 

**Server Type (Spigot/Paper/etc): Paper fork** 

**Server Version (using `/ver`):
[11:59:54 INFO]: This server is running Airplane version git-Airplane-"3b3cde7" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
**

**Comment by KoxSosen** [comment]
More info:

```
[10:21:40] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[10:21:40] [Server thread/WARN]: java.lang.Exception
[10:21:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.<clinit>(CraftLegacy.java:259)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.util.CraftLegacy.fromLegacy(CraftLegacy.java:22)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemFactory.getItemMeta(CraftItemFactory.java:52)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemFactory.getItemMeta(CraftItemFactory.java:48)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.getItemMeta(ItemStack.java:552)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.getDurability(ItemStack.java:230)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:34)
[10:21:40] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
[10:21:40] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:21:40] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.CMIReflections.asNMSCopy(CMIReflections.java:232)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.CMIReflections.getItemMinecraftName(CMIReflections.java:251)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.ItemManager.<clinit>(ItemManager.java:45)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.CMIMaterial.get(CMIMaterial.java:1397)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.GeneralConfigManager.loadGeneralSettings(GeneralConfigManager.java:491)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:254)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:801)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:494)
[10:21:40] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:702)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[10:21:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[10:21:40] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:581)
[10:21:40] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:283)
[10:21:40] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1057)
[10:21:40] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[10:21:40] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KoxSosen** [comment]
It seems like CMI's lib is accessing legacy materials for 0 reason.

**Comment by montlikadani** [comment]
It is reproducible without CMILib. `debug` option is enabled in server.properties, so the exception shows where this triggers.

**Comment by Zrips** [comment]
It wasn't accessing for no good reason, its basic backwards compatibility. Pushing new update which should no longer trigger this and hopefully we can avoid most issues if people still using legacy material identifications, like ID's which wont get recognized any longer on 1,13+ server version. Well, its time to move on.
d1ce5d7fa65edc2eebe8acbcf94e13bcf4fead00
