### ISSUE TITLE
Could not pass event BlockBreakEvent to Jobs v3.9.7

### ISSUE THREAD

**Issue by Typhome** [Zrips/Jobs#116]
Spigot 1.12
Jobs 3.9.7

```
[19:57:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Jobs v3.9.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:289) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:216) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:882) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-b1331.jar:git-Spigot-b78586d-753a8e7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
```

**Comment by Zrips** [comment]
I need full message as its cuts down where actual error place is being shown, without it it will take ages to find where issue was
