### ISSUE TITLE
Error when player types in chat

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/Jobs#1186]
***Detailed description of the issue:**
So if player types in chat is results a long WARN in console where is says something about JOBS.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
[20:14:44 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="[NHorník NBojovník NBagrista] ", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[20:14:44 WARN]: at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[20:14:44 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[20:14:44 WARN]: at com.gamingmesh.jobs.stuff.complement.KyoriChatEvent.onPlayerChatLow(KyoriChatEvent.java:60)
[20:14:44 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor495.execute(Unknown Source)
[20:14:44 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:14:44 WARN]: at org.bukkit.plugin.EventExecutor$$Lambda$5012/0000000000000000.execute(Unknown Source)
[20:14:44 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[20:14:44 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:14:44 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:128)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.lambda$process$1(ChatProcessor.java:66)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor$$Lambda$7524/0000000000000000.accept(Unknown Source)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:118)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63)
[20:14:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2093)
[20:14:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2008)
[20:14:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1946)
[20:14:44 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44)
[20:14:44 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[20:14:44 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[20:14:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:14:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:14:44 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[20:14:44 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="[NHorník NBojovník NBagrista] ", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[20:14:44 WARN]: at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[20:14:44 WARN]: at net.kyori.adventure.text.Component.text(Component.java:588)
[20:14:44 WARN]: at com.gamingmesh.jobs.stuff.complement.KyoriChatEvent.onPlayerChatHigh(KyoriChatEvent.java:74)
[20:14:44 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor494.execute(Unknown Source)
[20:14:44 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:14:44 WARN]: at org.bukkit.plugin.EventExecutor$$Lambda$5012/0000000000000000.execute(Unknown Source)
[20:14:44 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[20:14:44 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:14:44 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:128)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.lambda$process$1(ChatProcessor.java:66)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor$$Lambda$7524/0000000000000000.accept(Unknown Source)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:118)
[20:14:44 WARN]: at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63)
[20:14:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2093)
[20:14:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2008)
[20:14:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1946)
[20:14:44 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44)
[20:14:44 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[20:14:44 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[20:14:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:14:44 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:14:44 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[20:14:44 INFO]: ❤ [10] Zk.Helperka Markeet k Nutella k ⇨ Něco
```

---

**Jobs version:** 4.17.1

**Server Type (Spigot/Paper/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-686 (MC: 1.16.5)

**Comment by montlikadani** [comment]
> 4.17.1

Please update Jobs first time
