### ISSUE TITLE
Jobs does not connect to the database

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/Jobs#1196]
Hello, the server suddenly lost the levels and jobs of ALL users. We do not understand why since it has been suddenly. I still keep the .db file since I have it set in the sqlite config. Somebody could help me. I use version 4.17.2. Thanks

**Comment by AlfreDGR** [comment]
[Jobs] Disabling Jobs v4.17.2
[11:47:01 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] There was an error in the WebSocket connection
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
        at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126) ~[?:?]
        at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDisconnected(WebSocketClient.java:460) ~[?:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[?:?]
        at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3730) ~[?:?]
        at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3696) ~[?:?]
        at com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3663) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80) ~[?:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]

**Comment by montlikadani** [comment]
> [Jobs] Disabling Jobs v4.17.2
> [11:47:01 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] There was an error in the WebSocket connection
> java.lang.IllegalStateException: zip file closed
> at java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[?:?]
> at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
> at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126) ~[?:?]
> at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
> at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
> at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-731]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
> at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-731]
> at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-731]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
> at net.dv8tion.jda.internal.requests.WebSocketClient.onDisconnected(WebSocketClient.java:460) ~[?:?]
> at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[?:?]
> at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3730) ~[?:?]
> at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3696) ~[?:?]
> at com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3663) ~[?:?]
> at com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138) ~[?:?]
> at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80) ~[?:?]
> at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]

This does not seem to be caused by the Jobs plugin itself, more likely your host does not allow the connection of databases or your file is locked. Make sure that this works on local pc.
