### ISSUE TITLE
ChunkUnloadEvent bugg 1.12.2

### ISSUE THREAD

**Issue by Teyir** [Zrips/Jobs#1201]
***Detailed description of the issue:**

Hello, I have this error on my console when I start my servers and I don't have any players online

---
[13:00:25 ERROR]: Could not pass event ChunkUnloadEvent to Jobs v4.17.2
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.isPersistent()Z
at com.gamingmesh.jobs.listeners.JobsPaymentListener.onChunkUnload(JobsPaymentListener.java:1692) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor989.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:392) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:354) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:309) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:905) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

---

**Jobs version: 4.17.2 ** 

**Server Type (Spigot/Paper/etc): paper** 

**Server Version (using `/ver`): 1.12.2** 

Thank you very much

**Comment by montlikadani** [comment]
Re-install the jobs from the main site (Spigot).

**Comment by Teyir** [comment]
Ok thank you very much I'm a fucking idiot...

Thank you
