### ISSUE TITLE
Little issue on Startup in 1.17

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1209]
```
[08:35:54] [Server thread/INFO]: [Jobs] Enabling Jobs v4.17.2
[08:35:54] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_17_R1
[08:35:55] [Server thread/INFO]: [Jobs] Plugin has been disabled successfully.
[08:35:55] [Server thread/WARN]: java.lang.ClassNotFoundException: com.gamingmesh.jobs.nmsUtil.v1_17
[08:35:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
[08:35:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:35:55] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[08:35:55] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:35:55] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:35:55] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:690)
[08:35:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:35:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:35:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:35:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[08:35:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[08:35:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
[08:35:55] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[08:35:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
[08:35:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[08:35:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Al3XKOoL** [comment]
Hi. I get same problem.
Plugin get disabled after 1.17 update.

Regards.

**Comment by CloudeLecaw** [comment]
hehe same with4.17.3  

so we might still have to wait a little for the 1.17 update

**Comment by broken1arrow** [comment]
Was some confusion about nms in 1.17 and you have to compile with new "flags" if you use spigot now, to get nms not obfuscate.

Stuff will over time get fixed .

**Comment by montlikadani** [comment]
v5.0.0.0 is available on discord development releases channel.
