### ISSUE TITLE
Error Jobs Gain

### ISSUE THREAD

**Issue by Redhardzz** [Zrips/Jobs#1213]
when the player performs job actions, he gains nothing and the console goes crazy !

Error :

>.... [14:02:32 ERROR]: Could not pass event BrewEvent to Jobs v4.17.2
java.lang.NullPointerException: null
at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBrewEvent(JobsPaymentListener.java:348) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor598.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-759]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-759]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-759]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.TileEntityBrewingStand.j(TileEntityBrewingStand.java:252) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.TileEntityBrewingStand.tick(TileEntityBrewingStand.java:177) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.World.tickBlockEntities(World.java:873) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:683) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-759]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

>.... [15:34:33 ERROR]: Could not pass event JobsExpGainEvent to Diagonia v1.0
java.lang.NullPointerException: null
at com.dzious.bukkit.diagonia.listener.jobs.JobsExpGainListener.onExpGain(JobsExpGainListener.java:27) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1051.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-759]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-759]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-759]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-759]
at com.gamingmesh.jobs.Jobs.perform(Jobs.java:1411) ~[?:?]
at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:389) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor594.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-759]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-759]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-759]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:359) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:259) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-759]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-759]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by montlikadani** [comment]
The first error is fixed in this [commit](https://github.com/Zrips/Jobs/commit/ecb189b03e17bef0175c51ac94522c7f59b589a6)

The second one is coming from `Diagonia` plugin
