### ISSUE TITLE
On Startup of 5.0.0.0 with Jobs + CMILIB both running

### ISSUE THREAD

**Issue by pcisafox** [Zrips/Jobs#1218]
***Detailed description of the issue:**

Plugin shoots out an error and disables on startup. Might be due to using dev builds of paper or other issues, however thought it was good idea to send here first in case im being an idiot. I have both CMILib and Jobs, but Jobs is refusing to load and gives this error.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
[14:03:10] [Server thread/INFO]: [Jobs] Enabling Jobs v5.0.0.0
[14:03:10] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: jobsr
[14:03:10] [Server thread/INFO]: [Jobs] PlaceholderAPI hooked.
[14:03:10] [Server thread/INFO]: [Jobs] Loaded 8 titles!
[14:03:10] [Server thread/INFO]: [Jobs] Loaded 67 protected blocks timers!
[14:03:10] [Server thread/INFO]: [Jobs] Loaded 1228 custom item names!
[14:03:10] [Server thread/INFO]: [Jobs] Loaded 75 custom entity names!
[14:03:10] [Server thread/INFO]: [Jobs] Loaded 2 custom MythicMobs names!
[14:03:10] [Server thread/INFO]: [Jobs] Loaded 38 custom enchant names!
[14:03:10] [Server thread/INFO]: [Jobs] Loaded 16 custom color names!
[14:03:10] [Server thread/INFO]: [Jobs] Loaded 4 shop items!
[14:03:10] [Server thread/WARN]: java.lang.NoSuchMethodError: 'java.io.File net.Zrips.CMILib.FileHandler.ConfigReader.getFile()'
[14:03:10] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ConfigManager.updateExampleFile(ConfigManager.java:95)
[14:03:10] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ConfigManager.reload(ConfigManager.java:924)
[14:03:10] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:830)
[14:03:10] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:536)
[14:03:10] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:738)
[14:03:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:03:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:03:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:03:10] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304)
[14:03:10] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262)
[14:03:10] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:391)
[14:03:10] [Server thread/WARN]: 	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[14:03:10] [Server thread/WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[14:03:10] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:03:10] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:03:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:825)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1996)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1977)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184)
[14:03:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:03:10] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:03:10] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.

####################
```

---

**Jobs version:** 
5.0.0.0
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
1.17 (using paper 11 versions behind however if that causes bug)

**Comment by pcisafox** [comment]
Requires Dev build of CMILib 1.02.2 Downloaded at https://github.com/Zrips/Jobs/blob/master/libs/CMILib1.0.2.2.jar
