### ISSUE TITLE
Error with actionbar appeared in 1.17.. with CMILIB 1.0.27?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1224]
We see no reason why this error appeared..

```
[15:45:01] [Jobs-BufferedPaymentThread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player" is null
[15:45:01] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:146)
[15:45:01] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:101)
[15:45:01] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:97)
[15:45:01] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:176)
[15:45:01] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
[15:45:06] [Jobs-BufferedPaymentThread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player" is null
[15:45:06] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:146)
[15:45:06] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:101)
[15:45:06] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:97)
[15:45:06] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:176)
[15:45:06] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
[15:45:11] [Jobs-BufferedPaymentThread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player" is null
[15:45:11] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:146)
[15:45:11] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:101)
[15:45:11] [Jobs-BufferedPaymentThread/WARN]: 	at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:97)
[15:45:11] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:176)
[15:45:11] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
```

**Server Type (Spigot/Paper/etc):** 
PaperMC 1.17 Build 75

**Relevant plugins (Delete if this isn't needed):**
Jobs 5.0.0.1
Cmilibs 1.0.2.7

**Comment by CloudeLecaw** [comment]
addtion now some hours later

```
>.... [17:19:54 ERROR]: [Wraith] Unhandled exception number 256 occured in onPacketReceiving(PacketEvent) for Wraith
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.protocol.game.PacketPlayInUseEntity$b exists in class PacketPlayInUseEntity.
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:218) ~[?:?]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[?:?]
at dev.lone.wraith.f.f.onPacketReceiving(SourceFile:159) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) ~[?:?]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-75]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-75]
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[patched_1.17.jar:git-Paper-75]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.17.jar:git-Paper-75]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.jar:git-Paper-75]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.jar:git-Paper-75]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by mrfloris** [comment]
Just curious, what do you use for economy setup?

**Comment by CloudeLecaw** [comment]
we use the CMI economy

**Comment by Zrips** [comment]
Will fix, it got introduced with CMILib action bar optimization, even tho this should not really happen in normal situations, but something triggers actionbar message sending while player object is not defined properly. Well, its easy fix for CMILib and that will resolve this issue.
