### ISSUE TITLE
SQLiteException Error

### ISSUE THREAD

**Issue by MacMarshmello** [Zrips/Jobs#1244]
Hello there (Master Kenobi),

I recently set up a minecraft server on my RaspberryPi whicht is running on Linux 10. The Jobs Reborn plugin starts as it should and works fine but I keep getting the following error code in my console every 10 minutes:

```
[15:51:42 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[15:51:42 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1012)
[15:51:42 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1024)
[15:51:42 WARN]:        at org.sqlite.core.DB.throwex(DB.java:989)
[15:51:42 WARN]:        at org.sqlite.core.DB.executeBatch(DB.java:814)
[15:51:42 WARN]:        at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
[15:51:42 WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.saveBlockProtection(JobsDAO.java:2272)
[15:51:42 WARN]:        at com.gamingmesh.jobs.config.BlockProtectionManager.saveCache(BlockProtectionManager.java:109)
[15:51:42 WARN]:        at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:338)
[15:51:42 WARN]:        at com.gamingmesh.jobs.tasks.DatabaseSaveThread.run(DatabaseSaveThread.java:46)
```

First I thought the reason for this would be that the plugin has not enough permissions in the operating system, so I changed it to full access but the error keeps coming up. Can somebody help me? Thanks in advance!

Greetings
MacMarshmello

---

**Jobs version:** 5.0.0.6

**Server type:** PaperMC

**Server version:** git-Paper-782 (MC: 1.16.5)

**Installed plugins:**
- CMILib
- Essentials/EssentialsChat/EssentialsSpawn
- Jobs Reborn
- LuckPerms
- Multiverse-Core
- NametagEdit
- PlaceholderAPI
- PlayerHeads
- Scoreboard
- Shopkeepers
- Vault
- WorldEdit/WorldGuard

**Comment by MacMarshmello** [comment]
Fixed it! Looks like CMILib plugin didn't start up. I updated it today and now there's no error anymore.
