### ISSUE TITLE
NullPointerException: String.toLowerCase() because "permission" is null

### ISSUE THREAD

**Issue by Sandukhan** [Zrips/Jobs#1265]
***Detailed description of the issue:**
Jobs is generating lots of NullPointerException after players joining the server, changing worlds or reloading the plugin while players are present on the server. With no players on the server, this error isnt thrown.  

I suspected luckperms first, but after asking for support there, they pointed the problem at
com.gamingmesh.jobs.PermissionHandler.recalculatePermissions

```
####################
## PASTE ERROR HERE ##
####################

[12:41:22 WARN]: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "permission" is null
[12:41:22 WARN]:        at me.lucko.luckperms.common.treeview.PermissionRegistry.doInsert(PermissionRegistry.java:96)
[12:41:22 WARN]:        at me.lucko.luckperms.common.treeview.PermissionRegistry.insert(PermissionRegistry.java:89)
[12:41:22 WARN]:        at me.lucko.luckperms.bukkit.inject.server.LuckPermsPermissionMap$NotifyingChildrenMap.<init>(LuckPermsPermissionMap.java:246)
[12:41:22 WARN]:        at me.lucko.luckperms.bukkit.inject.server.LuckPermsPermissionMap.inject(LuckPermsPermissionMap.java:213)
[12:41:22 WARN]:        at me.lucko.luckperms.bukkit.inject.server.LuckPermsPermissionMap.put(LuckPermsPermissionMap.java:112)
[12:41:22 WARN]:        at me.lucko.luckperms.bukkit.inject.server.LuckPermsPermissionMap.put(LuckPermsPermissionMap.java:60)
[12:41:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:744)
[12:41:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:733)
[12:41:22 WARN]:        at com.gamingmesh.jobs.PermissionHandler.recalculatePermissions(PermissionHandler.java:204)
[12:41:22 WARN]:        at com.gamingmesh.jobs.PlayerManager.reload(PlayerManager.java:958)
[12:41:22 WARN]:        at com.gamingmesh.jobs.Jobs.reload(Jobs.java:853)
[12:41:22 WARN]:        at com.gamingmesh.jobs.Jobs.reload(Jobs.java:787)
[12:41:22 WARN]:        at com.gamingmesh.jobs.commands.list.reload.perform(reload.java:12)
[12:41:22 WARN]:        at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:93)
[12:41:22 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:41:22 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:41:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[12:41:22 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[12:41:22 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[12:41:22 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[12:41:22 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:41:22 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:41:22 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[12:41:22 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:41:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:41:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:41:22 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[12:41:22 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[12:41:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:41:22 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[12:41:22 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[12:41:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[12:41:22 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[12:41:22 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[12:41:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:41:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

####################
####################
```

Job config:
https://pastebin.com/9dHeJa9e

general config:
https://pastebin.com/682nJtjr


**Jobs version:** 
jobs 5.0.0.6

**Server Type (Spigot/Paper/etc):** 
paper-1.17.1 build 243
paper-1.16.5 build 788

**Comment by Zrips** [comment]
0100f78c8b86788d3aeb1fc25a6a29b69b2fdb9c
