### ISSUE TITLE
Logging again

### ISSUE THREAD

**Issue by gwelw** [Zrips/Jobs#132]
Spaming error when saveding the data base:

[17:59:10 WARN]: java.sql.SQLException: assertion failure: param count (8) != value count (32)
[17:59:10 WARN]:        at org.sqlite.core.DB.execute(DB.java:799)
[17:59:10 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:53)
[17:59:10 WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.saveLog(JobsDAO.java:1530)
[17:59:10 WARN]:        at com.gamingmesh.jobs.container.JobsPlayer.save(JobsPlayer.java:685)
[17:59:10 WARN]:        at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:214)
[17:59:10 WARN]:        at com.gamingmesh.jobs.tasks.DatabaseSaveThread.run(DatabaseSaveThread.java:53)

**Comment by montlikadani** [comment]
**Try update to the latest version.**
