### ISSUE TITLE
[1.18] Jobs fails to load on latest paper build 42

### ISSUE THREAD

**Issue by mrfloris** [Zrips/Jobs#1332]
```
jobs.jar version 5.0.1.0
cmilib.jar version 1.1.0.1
```

```
[14:55:40 INFO]: [Jobs] Enabling Jobs v5.0.1.0
[14:55:40 INFO]: ------------- Jobs -------------
[14:55:40 INFO]: [PlaceholderAPI] Successfully registered expansion: jobsr
[14:55:40 INFO]: PlaceholderAPI hooked.
[14:55:40 INFO]: Connected to database (SqLite)
[14:55:41 INFO]: Loaded 8 titles
[14:55:41 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
[14:55:41 WARN]: 	at org.bukkit.configuration.MemorySection.get(MemorySection.java:265)
[14:55:41 WARN]: 	at org.bukkit.configuration.MemorySection.get(MemorySection.java:230)
[14:55:41 WARN]: 	at org.bukkit.configuration.MemorySection.isString(MemorySection.java:335)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.config.RestrictedBlockManager.load(RestrictedBlockManager.java:43)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:269)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:846)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:548)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:754)
[14:55:41 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:55:41 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:55:41 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:55:41 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
[14:55:41 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
[14:55:41 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[14:55:41 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[14:55:41 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[14:55:41 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[14:55:41 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:55:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:55:41 INFO]: [Jobs] [STDOUT] There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[14:55:41 WARN]: Nag author(s): '[Zrips, montlikadani]' of 'Jobs' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:55:41 INFO]: ------------- Jobs -------------
[14:55:41 INFO]: ------------------------------------
[14:55:41 INFO]: ------------------------------------
```
It no longer seems to wish to start ~ i was testing because a few people mentioned it wouldn't load anymore.

I tried old jobs/ dir and fresh install. 

```
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17+35-2724) Host: Mac OS X 10.15.7 (x86_64)
Loading libraries, please wait...
[14:55:34 INFO]: [STDERR]: You have used the Spigot command line EULA agreement flag.
[14:55:34 INFO]: [STDERR]: By using this setting you are indicating your agreement to Mojang's EULA (https://account.mojang.com/documents/minecraft_eula).
[14:55:34 INFO]: [STDERR]: If you do not agree to the above EULA please stop your server and remove this flag immediately.
[14:55:34 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:55:35 INFO]: Reloading ResourceManager: Default, bukkit
[14:55:35 INFO]: Loaded 7 recipes
[14:55:36 INFO]: Starting minecraft server version 1.18
[14:55:36 INFO]: Loading properties
[14:55:36 INFO]: This server is running Paper version git-Paper-42 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: c3ff7e0)
[14:55:36 INFO]: Server Ping Player Sample Count: 12
[14:55:36 INFO]: Using 4 threads for Netty based IO
[14:55:36 INFO]: Default game type: SURVIVAL
[14:55:36 INFO]: Generating keypair
[14:55:36 INFO]: Starting Minecraft server on *:55555
[14:55:36 INFO]: Using default channel type
[14:55:36 INFO]: Paper: Using Java 11 compression from Velocity.
[14:55:36 INFO]: Paper: Using Java cipher from Velocity.
[14:55:37 INFO]: [LuckPerms] Loading LuckPerms v5.3.75
[14:55:37 INFO]: [Chunky] Loading Chunky v1.2.89
[14:55:37 INFO]: [Vault] Loading Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[14:55:37 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.10.10-DEV-132
[14:55:37 INFO]: [F3Name] Loading F3Name v3.3.0
[14:55:37 INFO]: [CMILib] Loading CMILib v1.1.0.1
[14:55:37 INFO]: [Jobs] Loading Jobs v5.0.1.0
[14:55:37 INFO]: [CMI] Loading CMI v9.1.0.1
[14:55:37 INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:55:37 INFO]: [LuckPerms] Enabling LuckPerms v5.3.75
[14:55:37 INFO]:         __
[14:55:37 INFO]:   |    |__)   LuckPerms v5.3.75
[14:55:37 INFO]:   |___ |      Running on Bukkit - Paper
[14:55:37 INFO]:
[14:55:37 INFO]: [LuckPerms] Loading configuration...
[14:55:37 INFO]: [LuckPerms] Loading storage provider... [H2]
[14:55:38 INFO]: [LuckPerms] Loading internal permission managers...
[14:55:38 INFO]: [LuckPerms] Performing initial data load...
[14:55:38 INFO]: [LuckPerms] Successfully enabled. (took 766ms)
[14:55:38 INFO]: [Vault] Enabling Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[14:55:38 WARN]: [Vault] Loaded class com.Zrips.CMI.Modules.Economy.Economy from CMI v9.1.0.1 which is not a depend, softdepend or loadbefore of this plugin.
[14:55:38 INFO]: [Vault] [Economy] CMI Economy found: Waiting
[14:55:38 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[14:55:38 INFO]: [Vault] Enabled Version 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[14:55:38 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[14:55:38 INFO]: Preparing level "spawn"
[14:55:39 INFO]: Preparing start region for dimension minecraft:overworld
[14:55:39 INFO]: Time elapsed: 69 ms
[14:55:39 INFO]: Preparing start region for dimension minecraft:the_nether
[14:55:39 INFO]: Time elapsed: 30 ms
[14:55:39 INFO]: Preparing start region for dimension minecraft:the_end
[14:55:39 INFO]: Time elapsed: 25 ms
[14:55:39 INFO]: [Chunky] Enabling Chunky v1.2.89
[14:55:39 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.10.10-DEV-132
[14:55:39 INFO]: [PlaceholderAPI] Fetching available expansion information...
[14:55:39 INFO]: [F3Name] Enabling F3Name v3.3.0
[14:55:39 INFO]: [F3Name] Starting Bukkit(v1_18_R1) version...
[14:55:39 INFO]: [F3Name] Found PlaceholderAPI! Using it for placeholders.
[14:55:39 INFO]: [F3Name] Found LuckPerms! Using it for groups.
[14:55:39 INFO]: [F3Name] [cmi.support:55555]
[14:55:39 INFO]: [F3Name] [cmi.support:55555]
[14:55:39 INFO]: [F3Name] Plugin enabled!
[14:55:39 INFO]: [CMILib] Enabling CMILib v1.1.0.1
[14:55:40 INFO]: Server version: v1_18_R1 - 1.18.0 - paper
[14:55:40 INFO]: CMI hooked.
[14:55:40 INFO]: [PlaceholderAPI] Successfully registered expansion: cmil
[14:55:40 INFO]: PlaceholderAPI hooked.
[14:55:40 INFO]: Updated (EN) language file. Took 41ms
[14:55:40 INFO]: [Jobs] Enabling Jobs v5.0.1.0
[14:55:40 INFO]: ------------- Jobs -------------
[14:55:40 INFO]: [PlaceholderAPI] Successfully registered expansion: jobsr
[14:55:40 INFO]: PlaceholderAPI hooked.
[14:55:40 INFO]: Connected to database (SqLite)
[14:55:41 INFO]: Loaded 8 titles
[14:55:41 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
[14:55:41 WARN]: 	at org.bukkit.configuration.MemorySection.get(MemorySection.java:265)
[14:55:41 WARN]: 	at org.bukkit.configuration.MemorySection.get(MemorySection.java:230)
[14:55:41 WARN]: 	at org.bukkit.configuration.MemorySection.isString(MemorySection.java:335)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.config.RestrictedBlockManager.load(RestrictedBlockManager.java:43)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:269)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:846)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:548)
[14:55:41 WARN]: 	at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:754)
[14:55:41 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:55:41 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:55:41 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:55:41 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
[14:55:41 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
[14:55:41 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[14:55:41 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[14:55:41 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[14:55:41 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[14:55:41 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:55:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:55:41 INFO]: [Jobs] [STDOUT] There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[14:55:41 WARN]: Nag author(s): '[Zrips, montlikadani]' of 'Jobs' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:55:41 INFO]: ------------- Jobs -------------
[14:55:41 INFO]: ------------------------------------
[14:55:41 INFO]: ------------------------------------
[14:55:41 INFO]: [CMI] Enabling CMI v9.1.0.1
[14:55:41 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[14:55:41 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[14:55:41 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃
[14:55:41 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃
[14:55:41 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[14:55:41 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[14:55:41 INFO]: _______________________________________________________
[14:55:41 INFO]:   Integrating PaperSpigot async methods
[14:55:41 INFO]:   55 Enabled and 1 Disabled modules
[14:55:41 INFO]:   Loaded (28) portals into memory. Took 31ms
[14:55:41 INFO]:   Loaded (5) dynamic signs into memory. Took 1ms
[14:55:41 INFO]:   Permission plugin: LuckPerms5.3.75
[14:55:41 INFO]:   Initialized Cipher256 AES
[14:55:41 INFO]:   Loaded (59) regular alias into memory. Took 35ms
[14:55:41 INFO]:   Loaded (15) custom text's into memory. Took 2ms
[14:55:41 INFO]:   3.36.0 data base type detected
[14:55:42 INFO]:   Started SqLite data base. Took 117ms
[14:55:42 INFO]:   Vault was found - Enabling capabilities. Economy: CMIEconomy
[14:55:42 INFO]:   Cant load powderedsnow hologram. (santa) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Cant load runtop hologram. (run) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Cant load fish hologram. (general) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Cant load celebrationbarrel3 hologram. (general) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Cant load celebrationbarrel2 hologram. (general) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Cant load celebrationbarrel hologram. (general) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Cant load celebrationbarrel6 hologram. (general) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Cant load Worth hologram. (general) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Cant load celebrationbarrel4 hologram. (general) is missing. We will try to load it later on, if that doesnt happen please report to the developer.
[14:55:42 INFO]:   Loaded (10) holograms into memory. Took 17ms
[14:55:42 INFO]:   Loaded (5) warning categories into memory. Took 0ms
[14:55:42 INFO]:   Loaded (3) warning commands into memory. Took 0ms
[14:55:42 INFO]:   Loaded (134) custom mob heads into memory. Took 14ms
[14:55:42 INFO]:   Loaded (0) cooldowns into memory. Took 20ms
[14:55:42 INFO]:   Loaded (1) jails into memory. Took 2ms
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (mine) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (skygrid) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (nether) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (sanctuary) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (end) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (general) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (builders) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (run) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (skyblock) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (cave) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (acid) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (uwu) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (pvp) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (oneblock) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (debug) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (sushi) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (owo) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (generalx) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (hardcore) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (oldtest) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (PrisonMines) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (SpawnPhoenix23) name
[14:55:42 INFO]:   (RandomTeleportation) Can't find world with (santa) name
[14:55:42 INFO]:   Loaded (1) chat rooms into memory. Took 1ms
[14:55:43 INFO]:   Loaded (194) kits into memory. Took 1460ms
[14:55:43 INFO]:   Loaded (1) ranks into memory. Took 9ms
[14:55:43 INFO]:   Loaded (8) playtime rewards into memory. Took 2ms
[14:55:44 INFO]:   Loaded (3126) player data into memory. Took 253ms
[14:55:44 INFO]:   Loaded (19729) playtime records into memory. Took 118ms
[14:55:44 INFO]:   Loaded (1) playtime reward records into memory. Took 0ms
[14:55:44 INFO]:   Loaded (274) custom alias into memory. Took 68ms
[14:55:44 INFO]:   Loaded (55) interactive commands into memory. Took 5ms
[14:55:44 INFO]:   Registered events. Took 124ms
[14:55:44 INFO]:   Loaded (16) event action commands into memory. Took 4ms
[14:55:44 INFO]:   Updated (EN) language file. Took 138ms
[14:55:44 INFO]:   Loaded (1099) worth values into memory. Took 62ms
[14:55:44 INFO]:   Loaded (106) warps into memory. Took 15ms
[14:55:44 INFO]:   Vault permissions was found - Enabling capabilities.
[14:55:44 INFO]: [PlaceholderAPI] Successfully registered expansion: cmi
[14:55:44 INFO]:   PlaceholderAPI hooked.
[14:55:44 INFO]:   PlaceholderAPI was found - Enabling capabilities.
[14:55:44 INFO]:   Jobs was found - Enabling capabilities.
[14:55:44 INFO]:   Initializing world manager.
[14:55:44 INFO]:   Loaded (9) schedules into memory. Took 17ms
[14:55:44 INFO]:   Loaded GeoIP
[14:55:44 INFO]:   Loaded (11) skin cache entries into memory. Took 2ms
[14:55:44 INFO]:   Loaded (21) custom recipes into memory. Took 259ms
[14:55:44 INFO]:   Version 9.1.0.1 has been enabled
[14:55:44 INFO]: ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
[14:55:44 INFO]: [Vault][Economy] CMI Economy hooked.
[14:55:45 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[14:55:45 INFO]: Running delayed init tasks
[14:55:45 WARN]: [PlaceholderAPI] Loaded class net.luckperms.api.LuckPerms from LuckPerms v5.3.75 which is not a depend, softdepend or loadbefore of this plugin.
[14:55:45 INFO]: [PlaceholderAPI] Successfully registered expansion: luckperms
[14:55:45 INFO]: 1 placeholder hooks successfully registered!
[14:55:45 INFO]: Done (8.558s)! For help, type "help"
[14:55:45 INFO]: Timings Reset
> pl
[14:58:00 INFO]: Plugins (8): Chunky, CMI, CMILib, F3Name, Jobs, LuckPerms, PlaceholderAPI, Vault
> stop
[14:58:01 INFO]: Stopping the server
[14:58:01 INFO]: Stopping server
[14:58:01 INFO]: [CMI] Disabling CMI v9.1.0.1
[14:58:01 INFO]: [Vault][Economy] CMI Economy unhooked.
[14:58:01 INFO]: [CMI] Closed db connections
[14:58:01 INFO]: [CMILib] Disabling CMILib v1.1.0.1
[14:58:01 INFO]: [F3Name] Disabling F3Name v3.3.0
[14:58:01 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.10-DEV-132
[14:58:01 INFO]: [Vault] Disabling Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[14:58:01 INFO]: [Chunky] Disabling Chunky v1.2.89
[14:58:01 INFO]: [LuckPerms] Disabling LuckPerms v5.3.75
[14:58:01 INFO]: [LuckPerms] Starting shutdown process...
[14:58:01 INFO]: [LuckPerms] Closing storage...
[14:58:01 INFO]: [LuckPerms] Goodbye!
[14:58:01 INFO]: Saving players
[14:58:01 INFO]: Saving worlds
[14:58:01 INFO]: Saving chunks for level 'ServerLevel[spawn]'/minecraft:overworld
[14:58:01 INFO]: Saving chunks for level 'ServerLevel[spawn_nether]'/minecraft:the_nether
[14:58:02 INFO]: Saving chunks for level 'ServerLevel[spawn_the_end]'/minecraft:the_end
[14:58:02 INFO]: ThreadedAnvilChunkStorage (spawn): All chunks are saved
[14:58:02 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:58:02 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:58:02 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[14:58:02 INFO]: Flushing Chunk IO
[14:58:02 INFO]: Closing Thread Pool
> %
```

**Comment by mrfloris** [comment]
Tested build paper-33 for 1.18, and it works fine.

**Comment by mrfloris** [comment]
Build 47 of paper fixes it, works again.. 

the f#ck is going on. :D
