### ISSUE TITLE
java.lang.IllegalStateException: Queue full

### ISSUE THREAD

**Issue by tonito396pp** [Zrips/Jobs#1350]
***Detailed description of the issue:**
I start it first time it work but after reset it error
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## PASTE ERROR HERE ##
####################
```
[15:56:10 WARN]: java.lang.IllegalStateException: Queue full
[15:56:10 WARN]:        at java.base/java.util.AbstractQueue.add(AbstractQueue.java:98)
[15:56:10 WARN]:        at java.base/java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:329)
[15:56:10 WARN]:        at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:252)
[15:56:10 WARN]:        at org.yaml.snakeyaml.serializer.Serializer.serializeComments(Serializer.java:224)
[15:56:10 WARN]:        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:168)
[15:56:10 WARN]:        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[15:56:10 WARN]:        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:207)
[15:56:10 WARN]:        at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:115)
[15:56:10 WARN]:        at org.yaml.snakeyaml.Yaml.serialize(Yaml.java:366)
[15:56:10 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:89)
[15:56:10 WARN]:        at CMILib1.1.0.4.jar//net.Zrips.CMILib.FileHandler.ConfigReader.save(ConfigReader.java:75)
[15:56:10 WARN]:        at CMILib1.1.0.4.jar//net.Zrips.CMILib.FileHandler.ConfigReader.save(ConfigReader.java:294)
[15:56:10 WARN]:        at Jobs5.0.1.0.jar//com.gamingmesh.jobs.config.ConfigManager.updateExampleFile(ConfigManager.java:488)
[15:56:10 WARN]:        at Jobs5.0.1.0.jar//com.gamingmesh.jobs.config.ConfigManager.reload(ConfigManager.java:929)
[15:56:10 WARN]:        at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:848)
[15:56:10 WARN]:        at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:548)
[15:56:10 WARN]:        at Jobs5.0.1.0.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:754)
[15:56:10 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:56:10 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:56:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[15:56:10 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[15:56:10 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[15:56:10 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[15:56:10 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[15:56:10 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[15:56:10 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[15:56:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[15:56:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:56:10 INFO]: [Jobs] [STDOUT] There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[15:56:10 WARN]: Nag author(s): '[Zrips, montlikadani]' of 'Jobs' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:** 
5.0.1.0
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
1.18.1

**Comment by mrfloris** [comment]
Also reported here: https://github.com/Zrips/Jobs/issues/1347

**Comment by mrfloris** [comment]
CMILib 1.1.0.5 should fix this, update ^_^
