### ISSUE TITLE
Invalid sql column check at startup.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#137]
Jobs v4.1.3

```
[02:56:24] [Server thread/INFO]: [Jobs] Enabling Jobs v4.1.3
[02:56:24] [Server thread/INFO]: Not a culumn |SELECT left FROM jobs_archive|
[02:56:24] [Server thread/INFO]: Creating culumn |ALTER TABLE `jobs_archive` ADD COLUMN `left` bigint;|
```

Occurs at every start-up, even with a fresh mysql database.

**Comment by DmitryRendov** [comment]
I'd like to add more, related to this issue - when a player is leaving any job I'm getting an issue like that:

`[18:09:39] [Server thread/INFO]: guyfromqueens issued server command: /jobs leave builder
[18:09:39] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'left' in 'field list'
[18:09:39] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:09:39] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:09:39] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:09:39] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[18:09:39] [Server thread/WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[18:09:39] [Server thread/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.recordToArchive(JobsDAO.java:1175)
[18:09:39] [Server thread/WARN]:        at com.gamingmesh.jobs.PlayerManager.leaveJob(PlayerManager.java:385)
[18:09:39] [Server thread/WARN]:        at com.gamingmesh.jobs.commands.list.leave.perform(leave.java:36)
[18:09:39] [Server thread/WARN]:        at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:114)
[18:09:39] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:09:39] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:09:39] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:09:39] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:09:39] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[18:09:39] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[18:09:39] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
`

**Comment by Zrips** [comment]
Is this is still an issue with latest version?

**Comment by DmitryRendov** [comment]
It is still an issue. And looks like a reason for that - missed schema version in mysql table and skipped or wrong database migration. I've got another exception today - https://pastebin.com/AqcxPjCH

I'll try to figure out the steps to reproduce on pure spigot+jobs+mysql later

**Comment by DmitryRendov** [comment]
As a workaround I've fixed the issue by manually amending the database - https://pastebin.com/5hHFGJpv Anyway, be careful by doing such upgrade and make a backup beforehand)
