### ISSUE TITLE
SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)

### ISSUE THREAD

**Issue by Qveshn** [Zrips/Jobs#1376]
***Detailed description of the issue:**

After the `jobs reload` command, there are exceptions for new players who enter the server for the first time after the installed plugin (empty database). Also, there are other exceptions.
All exceptions are of type `org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)`

**REPRODUCING:**

1. Install plugin (copy to plugins folder)
2. Restart server
3. Player A joins the server: no exception
4. Player A leaves the server
5. Command `jobs reload` (from console)
6. Player A joins the server: no exception
7. Player B joins the server: EXCEPTION! (see below EXCEPTION 1)
8. Player C joins the server: EXCEPTION! (see below EXCEPTION 1)
10. Any player joins the job via `/jobs browse` + right click on job: EXCEPTION! (see below EXCEPTION 2)
...
11. After some time (apparently, when plugin starts saving buffered data to the database), EXCEPTION SPAM STARTS! (see below EXCEPTIONS 3)

**ASSUMPTIONS:**
IMHO: On command `jobs reload` the plugin just forgets about its variable with opened database connection and does not `close()` it.
While this object is in garbage collection, the plugin can not open new connection.

---

**EXCEPTION 1**
```
[22:47:07] [User Authenticator #13/INFO]: UUID of player Guga is 8a3bfcba-2bad-3c19-8671-c40ee6c310ca
[22:47:10] [Server thread/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[22:47:10] [Server thread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1012)
[22:47:10] [Server thread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1024)
[22:47:10] [Server thread/WARN]:        at org.sqlite.core.DB.execute(DB.java:863)
[22:47:10] [Server thread/WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[22:47:10] [Server thread/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.recordNewPlayer(JobsDAO.java:926)
[22:47:10] [Server thread/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.getAllJobs(JobsDAO.java:597)
[22:47:10] [Server thread/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.loadFromDao(JobsDAO.java:1897)
[22:47:10] [Server thread/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.loadFromDao(JobsDAO.java:1916)
[22:47:10] [Server thread/WARN]:        at com.gamingmesh.jobs.PlayerManager.playerJoin(PlayerManager.java:235)
[22:47:10] [Server thread/WARN]:        at com.gamingmesh.jobs.listeners.JobsListener.onPlayerJoin(JobsListener.java:165)
[22:47:10] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:47:10] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[22:47:10] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:47:10] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[22:47:10] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[22:47:10] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:47:10] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[22:47:10] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:276)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:192)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74)
[22:47:10] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1336)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050)
[22:47:10] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[22:47:10] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[22:47:10] [Server thread/INFO]: Guga[/46.119.46.19:51431] logged in with entity id 48471 at ([world]-7.5, 86.0, 9.5)
```

**EXCEPTION 2**
```
[23:29:18] [Server thread/INFO]: Madar issued server command: /jobs browse
[23:29:26] [Server thread/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[23:29:26] [Server thread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1012)
[23:29:26] [Server thread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1024)
[23:29:26] [Server thread/WARN]:        at org.sqlite.core.DB.execute(DB.java:863)
[23:29:26] [Server thread/WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[23:29:26] [Server thread/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.joinJob(JobsDAO.java:1503)
[23:29:26] [Server thread/WARN]:        at com.gamingmesh.jobs.PlayerManager.joinJob(PlayerManager.java:481)
[23:29:26] [Server thread/WARN]:        at com.gamingmesh.jobs.commands.list.join.perform(join.java:86)
[23:29:26] [Server thread/WARN]:        at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:93)
[23:29:26] [Server thread/WARN]:        at com.gamingmesh.jobs.Gui.GuiManager$1.click(GuiManager.java:192)
[23:29:26] [Server thread/WARN]:        at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:263)
[23:29:26] [Server thread/WARN]:        at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:221)
[23:29:26] [Server thread/WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor266.invoke(Unknown Source)
[23:29:26] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:29:26] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[23:29:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[23:29:26] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:29:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[23:29:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[23:29:26] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2427)
[23:29:26] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55)
[23:29:26] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11)
[23:29:26] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[23:29:26] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[23:29:26] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[23:29:26] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[23:29:26] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[23:29:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148)
[23:29:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141)
[23:29:26] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[23:29:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125)
[23:29:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054)
[23:29:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[23:29:26] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**EXCEPTIONS 3**
```
[23:50:42] [Jobs-DatabaseSaveTask/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[23:50:42] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1012)
[23:50:42] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1024)
[23:50:42] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.execute(DB.java:863)
[23:50:42] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[23:50:42] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.savePoints(JobsDAO.java:2077)
[23:50:42] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.container.JobsPlayer.save(JobsPlayer.java:874)
[23:50:42] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:301)
[23:50:42] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.tasks.DatabaseSaveThread.run(DatabaseSaveThread.java:46)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1012)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1024)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.execute(DB.java:863)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.recordPlayersLimits(JobsDAO.java:1373)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.container.JobsPlayer.save(JobsPlayer.java:875)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:301)
[23:50:45] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.tasks.DatabaseSaveThread.run(DatabaseSaveThread.java:46)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1012)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1024)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.core.DB.execute(DB.java:863)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.updateSeen(JobsDAO.java:1994)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.container.JobsPlayer.save(JobsPlayer.java:876)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:301)
[23:50:48] [Jobs-DatabaseSaveTask/WARN]:        at com.gamingmesh.jobs.tasks.DatabaseSaveThread.run(DatabaseSaveThread.java:46)
...
```

**Jobs version:** 
5.0.1.2

**Server Type (Spigot/Paper/etc):** 
Spigot

**Server Version (using `/ver`):** 
CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
ab07c80b62f4249035718cc3090dde6e7d88940c
