### ISSUE TITLE
enchants from ecoenchants cancel paments for enchanting.

### ISSUE THREAD

**Issue by Bibithom** [Zrips/Jobs#1381]
***Detailed description of the issue: I've an enchanter jobs, wich contains only items to enchant, no enchants. So, my players will be paid for every enchanting option, but it appears that they aren't paid when there's a custom enchant on their item.
To verify that, i've tried to do multiple enchants without custom enchants and it works, but when there's an enchant from ecoenchant it don't works anymore and players aren't get paid.
Thanks in advance for your answer, i will post this issue on ecoenchant git too.**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
[06:47]
[02.02 09:15:19] [Server] [ERROR] Could not pass event EnchantItemEvent to Jobs v5.0.1.2
[02.02 09:15:19] [Server] java.lang.NullPointerExceptionCannot invoke "com.gamingmesh.jobs.CMILib.CMIEnchantment.toString()" because the return value of "com.gamingmesh.jobs.CMILib.CMIEnchantment.get(String)" is null
[02.02 09:15:19] [Server] 	at com.gamingmesh.jobs.stuff.Util.enchantMatchesActionInfo(Util.java:412) ~[Jobs5.0.1.2.jar:?]
[02.02 09:15:19] [Server] 	at com.gamingmesh.jobs.container.Job.lambda$getJobInfo$0(Job.java:295) ~[Jobs5.0.1.2.jar:?]
[02.02 09:15:19] [Server] 	at com.gamingmesh.jobs.container.Job.getJobInfo(Job.java:305) ~[Jobs5.0.1.2.jar:?]
[02.02 09:15:19] [Server] 	at com.gamingmesh.jobs.Jobs.action(Jobs.java:1094) ~[Jobs5.0.1.2.jar:?]
[02.02 09:15:19] [Server] 	at com.gamingmesh.jobs.Jobs.action(Jobs.java:914) ~[Jobs5.0.1.2.jar:?]
[02.02 09:15:19] [Server] 	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onEnchantItem(JobsPaymentListener.java:1064) ~[Jobs5.0.1.2.jar:?]
[02.02 09:15:19] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1637.execute(Unknown Source) ~[?:?]
[02.02 09:15:19] [Server] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
[02.02 09:15:19] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
[02.02 09:15:19] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
[02.02 09:15:19] [Server] 	at net.minecraft.world.inventory.EnchantmentMenu.lambda$clickMenuButton$1(EnchantmentMenu.java:262) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.world.inventory.ContainerLevelAccess.lambda$execute$0(ContainerLevelAccess.java:67) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:54) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.world.inventory.ContainerLevelAccess.execute(ContainerLevelAccess.java:66) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.world.inventory.EnchantmentMenu.clickMenuButton(EnchantmentMenu.java:246) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerButtonClick(ServerGamePacketListenerImpl.java:2959) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerButtonClickPacket.handle(ServerboundContainerButtonClickPacket.java:17) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerButtonClickPacket.handle(ServerboundContainerButtonClickPacket.java:6) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
[02.02 09:15:19] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-181]
[02.02 09:15:19] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Enchant:
    book:
      income: 20
      points: 2.119615
      experience: 2.119615
```

---

**Jobs version: 5.0.1.2 Mysql** 

**Server Type (Spigot/Paper/etc):Paper** 

**Server Version (using `/ver`):git-paper-177** 

**Relevant plugins (Delete if this isn't needed): EcoEnchant**

**Comment by Zrips** [comment]
7e2ac975783edeb69451cdb1af1d98d0804cb06a
