### ISSUE TITLE
Unhandled exception executing command 'jobs'

### ISSUE THREAD

**Issue by HerondaleMC** [Zrips/Jobs#1387]
***Detailed description of the issue:**

--- Hey, I am getting this error code everytime I try to give people job levels or several other commands that has to do with /jobs. This has been like this since the day I downloaded the plugin.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## PASTE ERROR HERE ##
####################
``` [07:23:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin Jobs v5.0.1.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1939) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1778) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1759) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3403-Spigot-f4ff00f-2e61a5f]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.UUID org.bukkit.Bukkit.getPlayerUniqueId(java.lang.String)'
	at com.gamingmesh.jobs.PlayerManager.getJobsPlayer(PlayerManager.java:383) ~[Jobs5.0.1.2.jar:?]
	at com.gamingmesh.jobs.commands.list.level.perform(level.java:61) ~[Jobs5.0.1.2.jar:?]
	at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:93) ~[Jobs5.0.1.2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 21 more

---

**Jobs version:** 5.0.1.2

**Server Type (Spigot/Paper/etc):**  Spigot

**Server Version (using `/ver`):** 1.18.1

**Comment by Zrips** [comment]
5f57d4aa953bfe15bd70a0ce46b8fa5ce7a06f7f
