### ISSUE TITLE
Tables not created in MySQL

### ISSUE THREAD

**Issue by mcdaddytalk** [Zrips/Jobs#1429]
MySQL tables are not being generated in db resulting in errors when plugin tries to execute queries against it

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
[10:49:32] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table 'hqkmc.jobs_jobs' doesn't exist
[10:49:32] [Server thread/WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[10:49:32] [Server thread/WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[10:49:32] [Server thread/WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[10:49:32] [Server thread/WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
[10:49:32] [Server thread/WARN]:        at Jobs5.0.2.1.jar//com.gamingmesh.jobs.dao.JobsDAO.getSlotsTaken(JobsDAO.java:2752)
[10:49:32] [Server thread/WARN]:        at Jobs5.0.2.1.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:865)
[10:49:32] [Server thread/WARN]:        at Jobs5.0.2.1.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:536)
[10:49:32] [Server thread/WARN]:        at Jobs5.0.2.1.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:741)
[10:49:32] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:49:32] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:49:32] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[10:49:32] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[10:49:32] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[10:49:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[10:49:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[10:49:32] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[10:49:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[10:49:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[10:49:32] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
---

Jobs: 5.0.2.1 MySQL
CMILib: 1.1.2.4
Server: Paper(277) 1.18.2-R0.1-SNAPSHOT
Economy: EssentialsX Economy Vault: 1.7.3-b131

**Comment by mcdaddytalk** [comment]
I tried in a fresh install and could not recreate the issue.   Likely another plugin is interfering.
Will close after I finish my investigating

**Comment by Zrips** [comment]
1b85ade74a5ed3f40f1d8264344a74c5366db610
