### ISSUE TITLE
Jobs Disabling on Startup (Please Help)

### ISSUE THREAD

**Issue by TheJoeEnder** [Zrips/Jobs#1469]
Getting this error almost everytime my server restarts.

[22:27:21 INFO]: =============================================================                                                                                                                                                    [124/30867]
[22:27:21 INFO]: [Jobs] Enabling Jobs v5.1.0.0
[22:27:21 INFO]: ------------- Jobs -------------
[22:27:21 INFO]: [PlaceholderAPI] Successfully registered expansion: jobsr [5.1.0.0]
[22:27:21 INFO]: PlaceholderAPI hooked.
[22:27:21 INFO]: Connected to database (SqLite)
[22:27:21 INFO]: [Towny] New update available: 0.98.3.1 | Current version: 0.98.3.0
[22:27:21 INFO]: [Towny] Download it here: https://github.com/TownyAdvanced/Towny/releases/tag/0.98.3.1
[22:27:22 INFO]: Loaded 8 titles
[22:27:22 INFO]: Loaded 69 protected blocks timers
[22:27:22 INFO]: Loaded 1229 custom item names
[22:27:22 INFO]: Loaded 75 custom entity names
[22:27:22 INFO]: Loaded 2 custom MythicMobs names
[22:27:22 INFO]: Loaded 38 custom enchant names
[22:27:22 INFO]: Loaded 16 custom color names
[22:27:22 INFO]: Loaded 4 shop items
[22:27:22 INFO]: Loaded 1 quests for Miner
[22:27:22 INFO]: Loaded 6 jobs
[22:27:22 INFO]: Loaded 0 boosted items
[22:27:22 WARN]: java.lang.IllegalArgumentException: Name cannot be null
[22:27:22 WARN]:        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[22:27:22 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.getWorld(CraftServer.java:1344)
[22:27:22 WARN]:        at org.bukkit.Bukkit.getWorld(Bukkit.java:760)
[22:27:22 WARN]:        at CMILib1.2.1.1.jar//net.Zrips.CMILib.Container.CMILocation.<init>(CMILocation.java:52)
[22:27:22 WARN]:        at CMILib1.2.1.1.jar//net.Zrips.CMILib.Container.CMILocation.fromString(CMILocation.java:418)
[22:27:22 WARN]:        at Jobs5.1.0.0.jar//com.gamingmesh.jobs.container.blockOwnerShip.BlockOwnerShip.load(BlockOwnerShip.java:366)
[22:27:22 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[22:27:22 WARN]:        at Jobs5.1.0.0.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:846)
[22:27:22 WARN]:        at Jobs5.1.0.0.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:536)
[22:27:22 WARN]:        at Jobs5.1.0.0.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:741)
[22:27:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:27:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:27:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[22:27:22 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[22:27:22 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[22:27:22 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[22:27:22 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[22:27:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[22:27:22 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[22:27:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[22:27:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:27:22 INFO]: [Jobs] [STDOUT] There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.

**Comment by Zrips** [comment]
Double check your blockOwnerShips.yml file for any invalid entries you might have. Will introduce small fix to CMILib to prevent this from happening and not allowing for plugin to load, but issue arises from issue in your records for one or another reason.
