### ISSUE TITLE
JobsReborn is intervening BossShopPro plugin

### ISSUE THREAD

**Issue by crimsson** [Zrips/Jobs#1472]
***Detailed description of the issue:**
So I have shop plugin called BossShopPro. When I tried to open its basic command such as /shop or /bs, the internal error message appeared in both in-game chat and console (as per below). I noticed that this plugin has "points" as a currency for trading and then I attempted to remove JobsReborn plugin and restart the server. After that, the /shop or /bs command worked just fine. So I can be sure that JobsReborn is causing the issue with this plugin.

Can you please fix this issue?
Thank you
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
[13:26:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bs' in plugin BossShopPro v2.0.9
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-794]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-794]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.gamingmesh.jobs.economy.PointsData com.gamingmesh.jobs.PlayerManager.getPointsData()'
at org.black_ixx.bossshop.pointsystem.BSPointsPluginJobs.getPoints(BSPointsPluginJobs.java:14) ~[?:?]
at org.black_ixx.bossshop.managers.features.PointsManager.getPoints(PointsManager.java:107) ~[?:?]
at org.black_ixx.bossshop.managers.misc.StringManager.transform(StringManager.java:130) ~[?:?]
at org.black_ixx.bossshop.managers.misc.StringManager.transform(StringManager.java:110) ~[?:?]
at org.black_ixx.bossshop.managers.item.ItemStackTranslator.translateItemStack(ItemStackTranslator.java:40) ~[?:?]
at org.black_ixx.bossshop.managers.ShopCustomizer.addItem(ShopCustomizer.java:186) ~[?:?]
at org.black_ixx.bossshop.managers.ShopCustomizer.createInventory(ShopCustomizer.java:136) ~[?:?]
at org.black_ixx.bossshop.managers.ShopCustomizer.createInventory(ShopCustomizer.java:41) ~[?:?]
at org.black_ixx.bossshop.core.BSShop.createInventory(BSShop.java:198) ~[?:?]
at org.black_ixx.bossshop.core.BSShop.openInventory(BSShop.java:293) ~[?:?]
at org.black_ixx.bossshop.core.BSShops.openShop(BSShops.java:129) ~[?:?]
at org.black_ixx.bossshop.core.BSShops.openShop(BSShops.java:101) ~[?:?]
at org.black_ixx.bossshop.managers.CommandManager.playerCommandOpenShop(CommandManager.java:201) ~[?:?]
at org.black_ixx.bossshop.managers.CommandManager.onCommand(CommandManager.java:169) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]
... 19 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version: Jobs5.1.0.0**  

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): 1.16.5** 

**Relevant plugins: JobsReborn and BossShopPro**

**Comment by Zrips** [comment]
Issue with BossShopPro plugin using outdated methods which no longer exist. It needs to be updated to match current plugin state.
