### ISSUE TITLE
Could not pass [some events]  to Jobs v5.1.2.2

### ISSUE THREAD

**Issue by comonier** [Zrips/Jobs#1567]
**Hello, I would like to know if there is anything I can do to prevent this error from appearing on my server's console.
Sorry, I couldn't understand what exactly is generating this error message.**

```yaml
[14:35:05] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Jobs v5.1.2.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign cannot be cast to class org.bukkit.block.data.type.Sign (org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign and org.bukkit.block.data.type.Sign are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
    at com.gamingmesh.jobs.Signs.SignUtil.updateHead(SignUtil.java:349) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.Signs.SignUtil.signUpdate(SignUtil.java:279) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.Signs.SignUtil.updateAllSign(SignUtil.java:175) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.PlayerManager.performLevelUp(PlayerManager.java:830) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.Jobs.action(Jobs.java:1287) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.Jobs.action(Jobs.java:946) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:480) ~[Jobs5.1.2.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor852.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-364]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:292) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1871) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-364]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by comonier** [comment]
```yaml
[16:38:24 ERROR]: Could not pass event EntityDeathEvent to Jobs v5.1.2.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign cannot be cast to class org.bukkit.block.data.type.Sign (org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign and org.bukkit.block.data.type.Sign are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
        at com.gamingmesh.jobs.Signs.SignUtil.updateHead(SignUtil.java:349) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Signs.SignUtil.signUpdate(SignUtil.java:279) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Signs.SignUtil.updateAllSign(SignUtil.java:175) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.PlayerManager.performLevelUp(PlayerManager.java:830) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:1287) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:972) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onEntityDeath(JobsPaymentListener.java:1422) ~[Jobs5.1.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor851.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-364]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:879) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1767) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1664) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1491) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:402) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:182) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:173) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:296) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:232) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1211) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:918) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-364]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```

**Comment by comonier** [comment]
```yaml
[16:38:24 ERROR]: Could not pass event EntityDeathEvent to Jobs v5.1.2.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign cannot be cast to class org.bukkit.block.data.type.Sign (org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign and org.bukkit.block.data.type.Sign are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
        at com.gamingmesh.jobs.Signs.SignUtil.updateHead(SignUtil.java:349) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Signs.SignUtil.signUpdate(SignUtil.java:279) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Signs.SignUtil.updateAllSign(SignUtil.java:175) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.PlayerManager.performLevelUp(PlayerManager.java:830) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:1287) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:972) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onEntityDeath(JobsPaymentListener.java:1422) ~[Jobs5.1.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor851.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-364]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:879) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1767) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1664) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1491) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:402) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:182) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:173) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:296) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:232) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1211) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:918) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-364]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```

**Comment by comonier** [comment]
```yaml
[17:45:30 ERROR]: Could not pass event BlockBreakEvent to Jobs v5.1.2.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign cannot be cast to class org.bukkit.block.data.type.Sign (org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign and org.bukkit.block.data.type.Sign are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
        at com.gamingmesh.jobs.Signs.SignUtil.updateHead(SignUtil.java:349) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Signs.SignUtil.signUpdate(SignUtil.java:279) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Signs.SignUtil.updateAllSign(SignUtil.java:175) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.PlayerManager.performLevelUp(PlayerManager.java:830) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:1287) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:946) ~[Jobs5.1.2.2.jar:?]
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:480) ~[Jobs5.1.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor852.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-364]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:292) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1871) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-364]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mrfloris** [comment]
You're just posting the same error?
Can you share the full info of these commands?
```
ver
jobs version
```
