### ISSUE TITLE
already have a job send error on console

### ISSUE THREAD

**Issue by comonier** [Zrips/Jobs#1568]
Everyone have all jobs because i set it on permissions..

but when someone try to join on a new job, it sends error on console
check it:

```yaml
[17:26:27] [Server thread/INFO]: Bananinha1826 issued server command: /jobs join Miner
[17:26:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin Jobs v5.1.2.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-364]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-364]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-364]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign cannot be cast to class org.bukkit.block.data.type.Sign (org.bukkit.craftbukkit.v1_19_R2.block.impl.CraftWallSign and org.bukkit.block.data.type.Sign are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
	at com.gamingmesh.jobs.Signs.SignUtil.updateHead(SignUtil.java:349) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.Signs.SignUtil.signUpdate(SignUtil.java:279) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.Signs.SignUtil.updateAllSign(SignUtil.java:175) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.PlayerManager.joinJob(PlayerManager.java:482) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.commands.list.join.perform(join.java:88) ~[Jobs5.1.2.2.jar:?]
	at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:116) ~[Jobs5.1.2.2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by mrfloris** [comment]
Can you do these and share the full output?
```
ver
jobs version
```

**Comment by Zrips** [comment]
9b291b299b3961e4dae3e0060c21cc656ec1eb5c
