### ISSUE TITLE
[BUG][1.12.2] spamming error in server log about TURTLE [jobs 5.2.1.1]

### ISSUE THREAD

**Issue by InuYasha86000** [Zrips/Jobs#1658]
I have found with jobs5.2.1.1 I am getting a looping error in my server logs when any player(s) is/are logged on and the error will not stop until there's no one logged into the server.
I have tried deleting all prior files/configs for a fresh start but it still comes up.

---

[23:37:08] [Server thread/ERROR] [Minecraft]: Could not pass event CreatureSpawnEvent to Jobs v5.2.1.1
java.lang.NoSuchFieldError: TURTLE
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onCreatureBreed(JobsPaymentListener.java:1604) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor192.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:1.12.2-de16e0a9]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:1.12.2-de16e0a9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.12.2-de16e0a9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) ~[SimplePluginManager.class:1.12.2-de16e0a9]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:312) ~[CraftEventFactory.class:1.12.2-de16e0a9]
	at net.minecraft.world.World.spawnEntity(World.java:1422) ~[amu.class:?]
	at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1375) ~[oo.class:?]
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:218) ~[anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:399) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:910) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:800) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_381]
```


---

**Jobs version:** 
5.2.1.1
**Server Type (Spigot/Paper/etc):** 
magma
**Server Version (using `/ver`):** 
1.12.2 (magma version de16e0a9)

**Comment by blakedj012** [comment]
me too

[12:07:57 ERROR]: Could not pass event CreatureSpawnEvent to Jobs v5.2.1.1
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[JavaPluginLoader$1.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:380) ~[CraftEventFactory.class:?]
        at net.minecraft.world.World.addEntity(World.java:1491) ~[amu.class:?]
        at net.minecraft.world.WorldServer.addEntity(WorldServer.java:1251) ~[oo.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.addEntityToWorld(NMSImpl.java:289) ~[?:?]
        at net.citizensnpcs.util.NMS.addEntityToWorld(NMS.java:74) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:55) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:321) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:280) ~[?:?]
        at net.citizensnpcs.trait.SitTrait.run(SitTrait.java:71) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:561) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:476) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.func_70071_h_(EntityHumanNPC.java:136) ~[?:?]
        at net.minecraft.world.World.func_72866_a(World.java:2387) ~[amu.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.lambda$playerTicker$1(NMSImpl.java:1060) ~[?:?]
        at net.citizensnpcs.util.NMS.lambda$playerTicker$2(NMS.java:662) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask$PlayerTick.run(PlayerUpdateTask.java:67) ~[?:?]
        at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_252]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:49) [Citizens-2.0.32-b3124.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) [CraftTask.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoSuchFieldError: TURTLE
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onCreatureBreed(JobsPaymentListener.java:1604) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[JavaPluginLoader$1.class:?]
        ... 27 more

**Comment by Zrips** [comment]
f29ed32d3f3b2b87d8d800e57a969fbb7db8881f
