### ISSUE TITLE
Console error on 1.8

### ISSUE THREAD

**Issue by vSKAH** [Zrips/Jobs#1662]
***Detailed description of the issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
 Could not pass event CreatureSpawnEvent to Jobs v5.2.1.1
java.lang.NoSuchFieldError: TURTLE
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onCreatureBreed(JobsPaymentListener.java:1604) ~[?:?]
        at org.imanity.imanityspigot.events.executor.asm.generated.GeneratedEventExecutor592.execute(Unknown Source) ~[?:?]
        at org.imanity.imanityspigot.executor.EventExecutorGenerator.lambda$create$1(EventExecutorGenerator.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(SourceFile:296) ~[spigot.jar:git-iSpigot-PaperEdition]
```

---

**5.2.1.1:** 

**Server Type (Spigot/Paper/etc):** Imanity (1.8 Paper Fork)

**Comment by Zrips** [comment]
f29ed32d3f3b2b87d8d800e57a969fbb7db8881f
