### ISSUE TITLE
jobs not working 1.20.6

### ISSUE THREAD

**Issue by WhiteProject1** [Zrips/Jobs#1754]
***Detailed description of the issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
[20:51:04] [Server thread/INFO]: ------------- Jobs -------------
[20:51:04] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: jobsr [5.2.3.0]
[20:51:04] [Server thread/INFO]: PlaceholderAPI hooked.
[20:51:05] [Server thread/INFO]: Connected to database (SqLite)
[20:51:05] [Server thread/INFO]: Loaded 8 titles
[20:51:05] [Server thread/INFO]: Loaded 69 protected blocks timers
[20:51:06] [Server thread/INFO]: Loaded 1406 custom item names
[20:51:06] [Server thread/INFO]: Loaded 84 custom entity names
[20:51:06] [Server thread/INFO]: Loaded 2 custom MythicMobs names
[20:51:06] [Server thread/INFO]: Loaded 42 custom enchant names
[20:51:06] [Server thread/INFO]: Loaded 46 custom enchant names
[20:51:06] [Server thread/INFO]: Loaded 16 custom color names
[20:51:06] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
[20:51:06] [Server thread/WARN]: 	at CMILib1.4.7.6.jar//net.Zrips.CMILib.Items.CMIItemSerializer.applyPotionEffect(CMIItemSerializer.java:751)
[20:51:06] [Server thread/WARN]: 	at CMILib1.4.7.6.jar//net.Zrips.CMILib.Items.CMIItemSerializer.deserialize(CMIItemSerializer.java:571)
[20:51:06] [Server thread/WARN]: 	at CMILib1.4.7.6.jar//net.Zrips.CMILib.Items.CMIItemStack.deserialize(CMIItemStack.java:869)
[20:51:06] [Server thread/WARN]: 	at Jobs5.2.3.0.jar//com.gamingmesh.jobs.config.ShopManager.load(ShopManager.java:452)
[20:51:06] [Server thread/WARN]: 	at Jobs5.2.3.0.jar//com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:302)
[20:51:06] [Server thread/WARN]: 	at Jobs5.2.3.0.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:850)
[20:51:06] [Server thread/WARN]: 	at Jobs5.2.3.0.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:537)
[20:51:06] [Server thread/WARN]: 	at Jobs5.2.3.0.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:751)
[20:51:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[20:51:06] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[20:51:06] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[20:51:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[20:51:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653)
[20:51:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:565)
[20:51:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685)
[20:51:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444)
[20:51:06] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:358)
[20:51:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154)
[20:51:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[20:51:06] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[20:51:06] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
[20:51:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[20:51:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[20:51:06] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[20:51:06] [Server thread/WARN]: 	... 20 more
[20:51:06] [Server thread/INFO]: [Jobs] There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[20:51:06] [Server thread/INFO]: ------------- Jobs -------------
[20:51:06] [Server thread/INFO]: Closed database connection
[20:51:06] [Server thread/INFO]: ------------------------------------
```

```
Default config
```

---

**Jobs version:**  Jobs5.2.3.0

**Server Type (Spigot/Paper/etc):**  Purpur 

**Server Version (using `/ver`):**  
![image](https://github.com/Zrips/Jobs/assets/103301275/e3d49e5a-1c21-4ae9-b3f2-a27350523753)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Try updating purpur to the latest version, as this error was present with early 1.20.6 builds and then resolved later on.

**Comment by FireML** [comment]
This issue is happening for me on the latest paper 1.20.6 build

**Comment by WhiteProject1** [comment]
I updated to the latest versions of paper but it is still available

**Comment by AuthFailed** [comment]
Same error on Purpur 1.20.6 latest build
![image](https://github.com/Zrips/Jobs/assets/21986465/61b9cf56-3fdf-4c8a-af99-092ac3b70f05)

**Comment by rautamiekka** [comment]
> I updated to the latest versions of paper but it is still available

> This issue is happening for me on the latest paper 1.20.6 build

Show the version.

**Comment by Zrips** [comment]
Update to latest CMILib 1.4.7.7 version and this should be resolved
