### ISSUE TITLE
Spawn eggs in bonus shop

### ISSUE THREAD

**Issue by DmitryRendov** [Zrips/Jobs#177]
ShulkerEgg:
    Price: 500.0
    Icon:
      Id: 383
      Data: 0
      Amount: 1
    GiveItems:
      ShulkerEgg:
        Id: 383:69
        Amount: 1

`[07:14:07 ERROR]: Could not pass event InventoryClickEvent to Jobs v4.4.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at com.gamingmesh.jobs.config.ShopManager.checkSlot(ShopManager.java:139) ~[?:?]
        at com.gamingmesh.jobs.listeners.JobsListener.onShopGuiClick(JobsListener.java:187) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor175.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-survival-1.12.2.jar:git-Spigot-4bd94dc-9ab298d]
        ... 15 more
`

**Comment by montlikadani** [comment]
**Try update to the latest version.**
