### ISSUE TITLE
Issue with jobs shop while performing command /jobs shop

### ISSUE THREAD

**Issue by ArturoApa** [Zrips/Jobs#1790]
***Detailed description of the issue:**
When using command /jobs shop a problem came, saying null....caused by icon is null

---

**ERROR:**
[https://pastebin.com/X1ddeBGd](https://pastebin.com/X1ddeBGd)
```
####################
Cannot invoke "net.Zrips.CMILib.Items.CMIItemStack.getItemStack()" because "icon" is null
        at com.gamingmesh.jobs.config.ShopManager.openShopGui(ShopManager.java:136) ~[Jobs5.2.4.0.jar:?]
        at com.gamingmesh.jobs.commands.list.shop.perform(shop.java:37) ~[Jobs5.2.4.0.jar:?]
        at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:118) ~[Jobs5.2.4.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
####################
```

**CONFIG SECTION:**
```
generalConfig.yml as default
```

---

**Jobs version:  Jobs5.2.4.0** 

**Server Type: Pufferfish a fork of Paper** 

**Server Version: 1.20.1** 

**Relevant plugins: CMILib 1.5.0.7**

**Comment by Zrips** [comment]
1fdb18dfe1930bb3c2c20805e75794a51d23b7e0
