### ISSUE TITLE
Potion type mus not be null?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1794]
***Detailed description of the issue:**
On Startup i get this erro in the log

```
[06:01:39] [Server thread/INFO]: [Jobs] Loaded 78 top list signs
[06:01:39] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type must not be null
[06:01:39] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[06:01:39] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:27)
[06:01:39] [Server thread/WARN]: 	at CMILib_1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemSerializer.applyPotionEffect(CMIItemSerializer.java:759)
[06:01:39] [Server thread/WARN]: 	at CMILib_1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemSerializer.deserialize(CMIItemSerializer.java:574)
[06:01:39] [Server thread/WARN]: 	at CMILib_1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemStack.deserialize(CMIItemStack.java:905)
[06:01:39] [Server thread/WARN]: 	at Jobs_5.2.4.0.jar//com.gamingmesh.jobs.config.ShopManager.load(ShopManager.java:452)
[06:01:39] [Server thread/WARN]: 	at Jobs_5.2.4.0.jar//com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:303)
[06:01:39] [Server thread/WARN]: 	at Jobs_5.2.4.0.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:878)
[06:01:39] [Server thread/WARN]: 	at Jobs_5.2.4.0.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:559)
[06:01:39] [Server thread/WARN]: 	at Jobs_5.2.4.0.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:773)
[06:01:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[06:01:39] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[06:01:39] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[06:01:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[06:01:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[06:01:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[06:01:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[06:01:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[06:01:39] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[06:01:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[06:01:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[06:01:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[06:01:39] [Server thread/INFO]: Loaded 4 shop items
[06:01:39] [Server thread/INFO]: Loaded 14 jobs
[06:01:39] [Server thread/INFO]: Loaded 0 boosted items
```

**Jobs version:** 
5.2.4.0

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
1.20,.4

Might its something i can solve from my site? where this Potion type 0 could be defined?

**Comment by CloudeLecaw** [comment]
Well i "fixed" it with removing this item from our shopItems.yml
`- potion;n{&6Jump_boost};jump`
looks like this format is not vailed anymore :)

So i close the issue because its solved from my site.
