### ISSUE TITLE
5.2.4.0 -> Potion Type must not be null(CMILib 1.5.0.9)

### ISSUE THREAD

**Issue by smscentras** [Zrips/Jobs#1798]
***Detailed description of the issue:**
Jobs 5.2.4.0 have problem with CMILib 1.5.0.9(1.5.0.8 all ok)
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[04:42:08 WARN]: java.lang.IllegalArgumentException: Potion Type must not be null
[04:42:08 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[04:42:08 WARN]:        at org.bukkit.potion.PotionData.<init>(PotionData.java:27)
[04:42:08 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemSerializer.applyPotionEffect(CMIItemSerializer.java:759)
[04:42:08 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemSerializer.deserialize(CMIItemSerializer.java:574)
[04:42:08 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemStack.deserialize(CMIItemStack.java:905)
[04:42:08 WARN]:        at Jobs5.2.4.0.jar//com.gamingmesh.jobs.config.ShopManager.load(ShopManager.java:452)
[04:42:08 WARN]:        at Jobs5.2.4.0.jar//com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:303)
[04:42:08 WARN]:        at Jobs5.2.4.0.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:878)
[04:42:08 WARN]:        at Jobs5.2.4.0.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:559)
[04:42:08 WARN]:        at Jobs5.2.4.0.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:773)
[04:42:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[04:42:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[04:42:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[04:42:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[04:42:08 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653)
[04:42:08 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564)
[04:42:08 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[04:42:08 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[04:42:08 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:346)
[04:42:08 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
[04:42:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[04:42:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```
```

**Jobs version:** 
Jobs: 5.2.4.0 SqLite
**Server Type (Spigot/Paper/etc):** 
Purpur
**Server Version (using `/ver`):** 
git-Purpur-2176 (MC: 1.20.4)*

**Comment by Zrips** [comment]
Fixed with later CMILib updates
