### ISSUE TITLE
Could not pass events

### ISSUE THREAD

**Issue by gamelamp** [Zrips/Jobs#1800]
***Detailed description of the issue:**
I don't know what or how it happened (it happened on my server and a player triggered it)
But the console threw out this: https://pastebin.com/YWD0vkmH
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## Could not pass event PlayerItemConsumeEvent to Jobs v5.2.4.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionData.getType()" because the return value of "org.bukkit.inventory.meta.PotionMeta.getBasePotionData()" is null
        at Jobs5.2.4.0.jar/com.gamingmesh.jobs.listeners.JobsPaymentListener.onPlayerItemConsumeEvent(JobsPaymentListener.java:1675) ~[Jobs5.2.4.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor406.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-124-df3b654]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:4074) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:2016) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3931) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2656) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3911) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3133) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.world.entity.player.Player.tick(Player.java:288) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:835) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.network.Connection.tick(Connection.java:638) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1823) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] ##
####################
```

**Jobs version: 5.2.4.0** 

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): 1.21 build 127** 

**Relevant plugins (Delete if this isn't needed): CMILib1.5.1.0.jar**

**Comment by gamelamp** [comment]
welp that didn't look nice, sorry. the formatting got all wrong and my pastebin did not paste completely correct

**Comment by Zrips** [comment]
326ce9e01b97178d3ff35a3c7db10151399c8995
