### ISSUE TITLE
Error in new Jobs 5.2.4.1

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1804]
new Version 5.2.4.1 throws this error. The Error spams freuently

```
[20:25:31] [Craft Scheduler Thread - 1897 - CMILib/ERROR]: Could not pass event JobsInstancePaymentEvent to Jobs v5.2.4.1
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
	at Jobs_5.2.4.1-1723744293375.jar/com.gamingmesh.jobs.listeners.JobsPaymentVisualizationListener.onJobsInstancePaymentActionBarEvent(JobsPaymentVisualizationListener.java:136) ~[Jobs_5.2.4.1-1723744293375.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1328.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at Jobs_5.2.4.1-1723744293375.jar/com.gamingmesh.jobs.Jobs.lambda$action$5(Jobs.java:1317) ~[Jobs_5.2.4.1-1723744293375.jar:?]
	at CMILib_1.5.1.1.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48) ~[CMILib_1.5.1.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:25:31] [Craft Scheduler Thread - 1897 - CMILib/ERROR]: Could not pass event JobsInstancePaymentEvent to Jobs v5.2.4.1
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
	at Jobs_5.2.4.1-1723744293375.jar/com.gamingmesh.jobs.listeners.JobsPaymentVisualizationListener.onJobsInstancePaymentActionBarEvent(JobsPaymentVisualizationListener.java:136) ~[Jobs_5.2.4.1-1723744293375.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1328.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at Jobs_5.2.4.1-1723744293375.jar/com.gamingmesh.jobs.Jobs.lambda$action$5(Jobs.java:1317) ~[Jobs_5.2.4.1-1723744293375.jar:?]
	at CMILib_1.5.1.1.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48) ~[CMILib_1.5.1.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:25:32] [Craft Scheduler Thread - 1930 - CMILib/ERROR]: Could not pass event JobsInstancePaymentEvent to Jobs v5.2.4.1
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
	at Jobs_5.2.4.1-1723744293375.jar/com.gamingmesh.jobs.listeners.JobsPaymentVisualizationListener.onJobsInstancePaymentActionBarEvent(JobsPaymentVisualizationListener.java:136) ~[Jobs_5.2.4.1-1723744293375.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1328.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at Jobs_5.2.4.1-1723744293375.jar/com.gamingmesh.jobs.Jobs.lambda$action$5(Jobs.java:1317) ~[Jobs_5.2.4.1-1723744293375.jar:?]
	at CMILib_1.5.1.1.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48) ~[CMILib_1.5.1.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Could it be this happens because extra job reward bonus of 50% is enabled?

**Jobs version:** 
![15-08-2024_20-21-48](https://github.com/user-attachments/assets/997f8ccb-a8e3-49bc-904d-52b28ebe3af8)

**Server Type and Version (Spigot/Paper/etc):** 
![15-08-2024_20-22-24](https://github.com/user-attachments/assets/34c5d7f8-c316-4556-93ea-40e17e1c3437)

**Comment by CloudeLecaw** [comment]
Edit:
Could it be it has to be with the nightboost (schedule)?

```
Boost:
  NightBoost:
    Enabled: true
    From: '18:15:00'
    Until: '22:00:00'
    Exp: 1.5
    Money: 1.5
    Days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    Jobs:
    - All
    BroadcastOnStart: true
    MessageOnStart:
    - '&2***********************************************'
    - '&e   Ab jetzt gibt es Spätzulage von &450%'
    - '&e      in den Berufen von &418-22 &eUhr '                 
    - '&2***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&2***********************************************'
    - '&e     Die Spätzulage ist nun zu Ende&2  '
    - '&2***********************************************'
    BroadcastInterval: 60
    BroadcastMessage:
    - '&2******************************************************'
    - '&e               Spätzulage ist aktiv '
    - '&2******************************************************' 
```

**Comment by Zrips** [comment]
New version is out with a fix
