### ISSUE TITLE
BoostedItems given before update 1.21 no longer work.

### ISSUE THREAD

**Issue by blacktoez** [Zrips/Jobs#1810]
BoostedItems given before update 1.21 no longer work after update 1.21. The error was reproduced with a boost pickaxe while mining ores in the miner job.

### Version Information
```
--------------------------------------------------
Jobs: Jobs5.2.4.2
CMILib: CMILib1.5.1.1
Server: Purpur version 1.21.1-2294-ver/1.21.1@1d3cef7
--------------------------------------------------
```

### Errors
```
[05:40:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Jobs v5.2.4.0
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: jobsitemboost.pêcheur
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:117) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at CMILib1.5.1.1.jar/net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.getKey(CMIPersistentDataContainer.java:128) ~[CMILib1.5.1.1.jar:?]
	at CMILib1.5.1.1.jar/net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.hasKey(CMIPersistentDataContainer.java:134) ~[CMILib1.5.1.1.jar:?]
	at CMILib1.5.1.1.jar/net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:1327) ~[CMILib1.5.1.1.jar:?]
	at CMILib1.5.1.1.jar/net.Zrips.CMILib.NBT.CMINBT.getString(CMINBT.java:606) ~[CMILib1.5.1.1.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.ItemBoostManager.getJobsItemByNbt(ItemBoostManager.java:272) ~[Jobs5.2.4.0.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.PlayerManager.getJobsItemByNbt(PlayerManager.java:1125) ~[Jobs5.2.4.0.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.PlayerManager.getInventoryBoost(PlayerManager.java:1055) ~[Jobs5.2.4.0.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.PlayerManager.getItemBoostNBT(PlayerManager.java:1036) ~[Jobs5.2.4.0.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.PlayerManager.getFinalBonus(PlayerManager.java:1202) ~[Jobs5.2.4.0.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.PlayerManager.getFinalBonus(PlayerManager.java:1145) ~[Jobs5.2.4.0.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.Jobs.action(Jobs.java:1208) ~[Jobs5.2.4.0.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.Jobs.action(Jobs.java:993) ~[Jobs5.2.4.0.jar:?]
	at Jobs5.2.4.0.jar/com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:510) ~[Jobs5.2.4.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor489.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2294-1d3cef7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at AdvancedEnchantments-9.10.6-1724038593010.jar/net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakBlock(DropsHandler.java:611) ~[AdvancedEnchantments-9.10.6-1724038593010.jar:?]
	at AdvancedEnchantments-9.10.6-1724038593010.jar/net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakAndDropExp(DropsHandler.java:554) ~[AdvancedEnchantments-9.10.6-1724038593010.jar:?]
	at AdvancedEnchantments-9.10.6-1724038593010.jar/net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:509) ~[AdvancedEnchantments-9.10.6-1724038593010.jar:?]
	at AdvancedEnchantments-9.10.6-1724038593010.jar/net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:87) ~[AdvancedEnchantments-9.10.6-1724038593010.jar:?]
	at AdvancedEnchantments-9.10.6-1724038593010.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:129) ~[AdvancedEnchantments-9.10.6-1724038593010.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1779.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2294-1d3cef7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1930) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[05:40:06] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.nbt.StringTag.e(java.lang.String)
[05:40:06] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2395)
[05:40:06] [Server thread/WARN]: 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getMethod(AbstractDefaultRulesReflectionProxy.java:100)
[05:40:06] [Server thread/WARN]: 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getMethod(Unknown Source)
[05:40:06] [Server thread/WARN]: 	at CMILib1.5.1.1.jar//net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:1354)
[05:40:06] [Server thread/WARN]: 	at CMILib1.5.1.1.jar//net.Zrips.CMILib.NBT.CMINBT.getString(CMINBT.java:606)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.ItemBoostManager.getJobsItemByNbt(ItemBoostManager.java:272)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.PlayerManager.getJobsItemByNbt(PlayerManager.java:1125)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.PlayerManager.getInventoryBoost(PlayerManager.java:1055)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.PlayerManager.getItemBoostNBT(PlayerManager.java:1036)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.PlayerManager.getFinalBonus(PlayerManager.java:1202)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.PlayerManager.getFinalBonus(PlayerManager.java:1145)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.Jobs.action(Jobs.java:1208)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.Jobs.action(Jobs.java:993)
[05:40:06] [Server thread/WARN]: 	at Jobs5.2.4.0.jar//com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:510)
[05:40:06] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor489.execute(Unknown Source)
[05:40:06] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[05:40:06] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:40:06] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:40:06] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[05:40:06] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[05:40:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[05:40:06] [Server thread/WARN]: 	at AdvancedEnchantments-9.10.6-1724038593010.jar//net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakBlock(DropsHandler.java:611)
[05:40:06] [Server thread/WARN]: 	at AdvancedEnchantments-9.10.6-1724038593010.jar//net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakAndDropExp(DropsHandler.java:554)
[05:40:06] [Server thread/WARN]: 	at AdvancedEnchantments-9.10.6-1724038593010.jar//net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:509)
[05:40:06] [Server thread/WARN]: 	at AdvancedEnchantments-9.10.6-1724038593010.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:87)
[05:40:06] [Server thread/WARN]: 	at AdvancedEnchantments-9.10.6-1724038593010.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:129)
[05:40:06] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1779.execute(Unknown Source)
[05:40:06] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[05:40:06] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:40:06] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:40:06] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[05:40:06] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[05:40:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1930)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355)
[05:40:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
[05:40:06] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Zrips** [comment]
Not much can be done as it fails due to special character usage ê in jobs name wich fails to recognize it properly on 1.21 server
