### ISSUE TITLE
error when killing mobs

### ISSUE THREAD

**Issue by dan28000** [Zrips/Jobs#1823]
***Detailed description of the issue:**
when killing mobs on 1.20.1 server it throws this

**ERROR:**
```
[13:43:17 ERROR]: Could not pass event EntityDeathEvent to Jobs v5.2.4.2
java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onEntityDeath(JobsPaymentListener.java:1309) ~[Jobs5.2.4.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1233.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:937) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1863) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1755) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1567) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.hurt(Animal.java:88) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrownTrident.onHitEntity(ThrownTrident.java:147) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:233) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:224) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:297) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:233) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrownTrident.tick(ThrownTrident.java:92) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1435) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:896) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:873) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

---

**Jobs version:** 5.2.4.2

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** 
Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Purpur-2058 (MC: 1.20.1)
* You are running the latest version

**Comment by Zrips** [comment]
fed6ef13551b6fde928b2ef6a28a01c56779010a
