### ISSUE TITLE
Trident/Bow pay not working

### ISSUE THREAD

**Issue by DustySpirit** [Zrips/Jobs#1828]
### Description of Issue

when killing mobs with a bow or trident thrown ability an error is sent to the console. 
The last version that does not have this issue is 5.2.4.0

### Version Information

```shell
versions 
Jobs 5.2.4.3
CMILIB 1.5.1.4
```

### Errors

```shell
[22:27:11 ERROR]: Could not pass event EntityDeathEvent to Jobs v5.2.4.3
java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onEntityDeath(JobsPaymentListener.java:1309) ~[Jobs5.2.4.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor328.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:962) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1839) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1733) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1556) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:319) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrownTrident.onHitEntity(ThrownTrident.java:147) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:203) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:194) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:296) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:232) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrownTrident.tick(ThrownTrident.java:92) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1386) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:900) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Zrips** [comment]
1d3b15ab87b61cb85533256d556571568ad39af0
