### ISSUE TITLE
EntityDeathEvent Bug on 1.8

### ISSUE THREAD

**Issue by Siux-YT** [Zrips/Jobs#1836]
### Description of Issue

The error you're encountering is related to the Jobs plugin, specifically version 5.2.4.3, which seems to be incompatible with your Minecraft server version (1.8.8). The NoSuchMethodError indicates that the method getDamageSource() is not available in the 1.8.8 version of the Bukkit/Spigot API. This method was introduced in later Minecraft versions, so the plugin is likely trying to access a feature that doesn't exist in your current server version.

### Version Information

```shell
5.2.4.3
```

### Errors

```shell
[16:33:58] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Jobs v5.2.4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-cbe632ca]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-PaperSpigot-cbe632ca]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-cbe632ca]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-PaperSpigot-cbe632ca]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-PaperSpigot-cbe632ca]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:907) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:845) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:250) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1650) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1617) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1450) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:983) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:846) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:682) ~[server.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:135) ~[server.jar:git-PaperSpigot-cbe632ca]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onEntityDeath(JobsPaymentListener.java:1309) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-cbe632ca]
	... 19 more
```

**Comment by ItsSynchro** [comment]
I also get this whilst the server version being 1.20.2

**Comment by Zrips** [comment]
1d3b15ab87b61cb85533256d556571568ad39af0
