### ISSUE TITLE
Startup Error/Disabling on Jobs 5.2.4.4

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Jobs#1838]
### Description of Issue

Jobs 5.2.4.4 throws an error and disables on startup when upgrading from 5.2.4.3 without any previous issues. Only happened on one of the three servers I run Jobs on and not really sure what the differences is -- the only thing I can think of is that I have a few worlds that aren't loaded by default, but all of the servers have that (and it hasn't been an issue before). 

### Version Information

```shell
Jobs: 5.2.4.3 SqLite
CMILib: 1.5.1.5 
Server: 123 1.21.1-R0.1-SNAPSHOT
Economy: CMIEconomy Vault: 1.7.3-CMI
```

### Errors

```shell
[18:52:03] [Server thread/INFO]: [Jobs] Enabling Jobs v5.2.4.4
[18:52:03] [Server thread/INFO]: ------------- Jobs -------------
[18:52:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: jobsr [5.2.4.4]
[18:52:03] [Server thread/INFO]: PlaceholderAPI hooked.
[18:52:03] [Server thread/INFO]: Connected to database (SqLite)
[18:52:03] [Server thread/INFO]: Loaded 8 titles
[18:52:03] [Server thread/INFO]: Loaded 4 restricted areas!
[18:52:03] [Server thread/INFO]: Loaded 52 protected blocks timers
[18:52:03] [Server thread/INFO]: Loaded 1481 custom item names
[18:52:03] [Server thread/INFO]: Loaded 84 custom entity names
[18:52:03] [Server thread/INFO]: Loaded 2 custom MythicMobs names
[18:52:03] [Server thread/INFO]: Loaded 42 custom enchant names
[18:52:03] [Server thread/INFO]: Loaded 46 custom enchant names
[18:52:03] [Server thread/INFO]: Loaded 16 custom color names
[18:52:03] [Server thread/INFO]: [Jobs] Loaded 27 top list signs
[18:52:03] [Server thread/INFO]: Update shops items icon section and use 'ItemStack' instead
[18:52:03] [Server thread/INFO]: Loaded 4 shop items
[18:52:03] [Server thread/INFO]: Update Weaponsmith jobs gui item section to use `ItemStack` instead of `Item` sections format. More information inside _EXAMPLE job file
[18:52:03] [Server thread/INFO]: Loaded 1 quests for Weaponsmith
[18:52:03] [Server thread/INFO]: Loaded 1 quests for Hunter
[18:52:03] [Server thread/INFO]: Loaded 2 quests for Farmer
[18:52:03] [Server thread/INFO]: Loaded 2 quests for Terraformer
[18:52:03] [Server thread/INFO]: Loaded 1 quests for Fisherman
[18:52:03] [Server thread/INFO]: Loaded 6 quests for Miner
[18:52:03] [Server thread/INFO]: Loaded 1 quests for Crafter
[18:52:03] [Server thread/INFO]: Loaded 1 quests for Woodcutter
[18:52:03] [Server thread/INFO]: Loaded 1 quests for Brewer
[18:52:03] [Server thread/INFO]: Loaded 3 quests for Redstoner
[18:52:03] [Server thread/INFO]: Loaded 1 quests for Enchanter
[18:52:03] [Server thread/INFO]: Loaded 3 quests for Builder
[18:52:03] [Server thread/INFO]: Loaded 12 jobs
[18:52:03] [Server thread/INFO]: Loaded 0 boosted items
[18:52:03] [Server thread/INFO]: Loaded 300 furnace for reassigning.
[18:52:03] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "loc" is null
[18:52:03] [Server thread/WARN]: 	at CMILib1.5.1.5.jar//net.Zrips.CMILib.Container.CMILocation.<init>(CMILocation.java:42)
[18:52:03] [Server thread/WARN]: 	at CMILib1.5.1.5.jar//net.Zrips.CMILib.Container.CMILocation.toString(CMILocation.java:425)
[18:52:03] [Server thread/WARN]: 	at Jobs5.2.4.4.jar//com.gamingmesh.jobs.container.blockOwnerShip.BlockOwnerShip.load(BlockOwnerShip.java:382)
[18:52:03] [Server thread/WARN]: 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[18:52:03] [Server thread/WARN]: 	at Jobs5.2.4.4.jar//com.gamingmesh.jobs.Jobs.reload(Jobs.java:893)
[18:52:03] [Server thread/WARN]: 	at Jobs5.2.4.4.jar//com.gamingmesh.jobs.Jobs.startup(Jobs.java:559)
[18:52:03] [Server thread/WARN]: 	at Jobs5.2.4.4.jar//com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:773)
[18:52:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[18:52:03] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[18:52:03] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[18:52:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[18:52:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[18:52:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[18:52:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[18:52:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[18:52:03] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[18:52:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[18:52:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[18:52:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:52:03] [Server thread/INFO]: [Jobs] [STDOUT] There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[18:52:03] [Server thread/WARN]: Nag author(s): '[Zrips]' of 'Jobs v5.2.4.4' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[18:52:03] [Server thread/INFO]: ------------- Jobs -------------
[18:52:03] [Server thread/INFO]: Closed database connection
[18:52:03] [Server thread/INFO]: ------------------------------------
```

**Comment by Zrips** [comment]
4a2862281b8c77cf4a5dd1593123c888610d2a62
