### ISSUE TITLE
NoClassDefFoundError: org/bukkit/block/data/type/Slab$Type

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#209]
Jobs v4.7.0
Paper dev 1533 (Spigot 1.12.2)

```
[02:36:22] [Server thread/ERROR]: Could not pass event CraftItemEvent to Jobs v4.7.0
java.lang.NoClassDefFoundError: org/bukkit/block/data/type/Slab$Type
	at com.gamingmesh.jobs.CMILib.ItemManager$1.<clinit>(ItemManager.java:2262) ~[?:?]
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2196) ~[?:?]
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2192) ~[?:?]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onInventoryCraft(JobsPaymentListener.java:577) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor833.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1533]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1985) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.type.Slab$Type
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 22 more

```

**Comment by Fabrimat** [comment]
For me:
Jobs v4.7.0
Spigot 1.12

`Could not pass event CraftItemEvent to Jobs v4.7.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [server.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.gamingmesh.jobs.CMILib.ItemManager$1
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2196) ~[?:?]
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2192) ~[?:?]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onInventoryCraft(JobsPaymentListener.java:577) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor768.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-596221b-9a1fc1e]
	... 15 more`
