### ISSUE TITLE
Could not pass event CraftItemEvent to Jobs v4.7.0

### ISSUE THREAD

**Issue by Yhenko** [Zrips/Jobs#210]
```
[21:24:39] [Server thread/ERROR]: Could not pass event CraftItemEvent to Jobs v4.7.0
java.lang.NoClassDefFoundError: Could not initialize class com.gamingmesh.jobs.CMILib.ItemManager$1
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2196) ~[?:?]
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2192) ~[?:?]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onInventoryCraft(JobsPaymentListener.java:577) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor690.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[test.jar:git-Paper-1533]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[test.jar:git-Paper-1533]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[test.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[test.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1985) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[test.jar:git-Paper-1533]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[test.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[21:24:39] [Server thread/ERROR]: Could not pass event CraftItemEvent to Jobs v4.7.0
java.lang.NoClassDefFoundError: Could not initialize class com.gamingmesh.jobs.CMILib.ItemManager$1
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2196) ~[?:?]
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2192) ~[?:?]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onInventoryCraft(JobsPaymentListener.java:577) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor690.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[test.jar:git-Paper-1533]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[test.jar:git-Paper-1533]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[test.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[test.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1985) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[test.jar:git-Paper-1533]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[test.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[test.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by Yhenko** [comment]
And this..
[img]https://i.gyazo.com/46d3b0ef39eac78c2a060496a6dbdff5.png[/img]
