### ISSUE TITLE
Jobs does not loaded

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/Jobs#227]
Jobs lates (spigot)
4.8.0

Server version:

This server is running CraftBukkit version git-Spigot-fe3ab0d-162bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

```
[11:35:21 INFO]: TheTopCz issued server command: /jobs
[11:35:21 INFO]: [Jobs] Cant read language file. Plugin will be disabled.
[11:35:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin Jobs v4.8.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
at com.gamingmesh.jobs.i18n.Language.getMessage(Language.java:68) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.i18n.Language.getMessage(Language.java:60) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.commands.JobsCommands.help(JobsCommands.java:153) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:69) ~[Jobs4.8.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
... 15 more
[11:35:37 INFO]: ladaladik124 issued server command: /jobs stats
[11:35:37 INFO]: [Jobs] Cant read language file. Plugin will be disabled.
[11:35:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin Jobs v4.8.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
at com.gamingmesh.jobs.i18n.Language.getMessage(Language.java:68) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.i18n.Language.getMessage(Language.java:60) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.commands.JobsCommands.sendUsage(JobsCommands.java:142) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.commands.list.stats.perform(stats.java:31) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:112) ~[Jobs4.8.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
... 15 more
>Jobs reload
[11:37:59 INFO]: [Jobs] Loaded 8 titles!
[11:37:59 INFO]: [Jobs] Your defined (93) protected block id/name is not correct!
[11:37:59 INFO]: [Jobs] Your defined (149) protected block id/name is not correct!
[11:37:59 INFO]: [Jobs] Loaded 46 protected blocks timers!
[11:37:59 INFO]: [Jobs] Loaded 641 custom item names!
[11:37:59 INFO]: [Jobs] Loaded 41 custom entity names!
[11:37:59 INFO]: [Jobs] Loaded 27 custom enchant names!
[11:37:59 INFO]: [Jobs] Loaded 16 custom color names!
[11:37:59 INFO]: [Jobs] Cant read language file. Plugin will be disabled.
[11:37:59 WARN]: Unexpected exception while parsing console command "Jobs reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin Jobs v4.8.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchServerCommand(CraftServer.java:679) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.DedicatedServer.aW(DedicatedServer.java:453) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:412) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
at com.gamingmesh.jobs.i18n.Language.getMessage(Language.java:68) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.i18n.Language.getMessage(Language.java:60) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.commands.list.reload.perform(reload.java:19) ~[Jobs4.8.0.jar:?]
at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:112) ~[Jobs4.8.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-fe3ab0d-162bda9]
... 8 more
```

**Comment by montlikadani** [comment]
**Please do NOT send the full server log just send it when we ask. Just send it where your bug is with the plugin.**

**Comment by TheTopCz** [comment]
Solved, my mistake
