### ISSUE TITLE
Jobs don't work on 1.13.1 version: 4.8.0

### ISSUE THREAD

**Issue by arturek1666** [Zrips/Jobs#229]
This issue is with the newest update:  4.8.0
```
[15:08:35] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[15:08:35] [Server thread/WARN]: java.lang.NullPointerException
[15:08:35] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.NameTranslatorManager.readFile(NameTranslatorManager.java:183)
[15:08:35] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.NameTranslatorManager.load(NameTranslatorManager.java:1780)
[15:08:35] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:357)
[15:08:35] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:604)
[15:08:35] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:538)
[15:08:35] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:812)
[15:08:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:08:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[15:08:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:08:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434)
[15:08:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348)
[15:08:35] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[15:08:35] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:576)
[15:08:35] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:433)
[15:08:35] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:305)
[15:08:35] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784)
[15:08:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by montlikadani** [comment]
Fixes, [commit](https://github.com/Zrips/Jobs/commit/1e8940124f6e7bea399eb1caacbbcc5dd2120a03#diff-653e2e5a015b53ecc101fc4e916fe02d)
