### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by ArtelGG** [Zrips/Jobs#250]
**Server version:** 1.8.8
**Plugin version:** 4.8.0
Configuration files are all default.

```
[03:34:44 INFO]: [Jobs] Enabling Jobs v4.8.0
[03:34:44 INFO]: [Jobs] Your server version don't support BossBar. This feature will be disabled
[03:34:45 INFO]: [Jobs] Loaded 8 titles!
[03:34:45 INFO]: [Jobs] Your defined (93) protected block id/name is not correct!
[03:34:45 INFO]: [Jobs] Your defined (149) protected block id/name is not correct!
[03:34:45 INFO]: [Jobs] Your defined (207) protected block id/name is not correct!
[03:34:45 INFO]: [Jobs] Loaded 46 protected blocks timers!
[03:34:45 INFO]: [Jobs] Loaded 641 custom item names!
[03:34:45 INFO]: [Jobs] Loaded 41 custom entity names!
[03:34:45 INFO]: [Jobs] Loaded 27 custom enchant names!
[03:34:45 INFO]: [Jobs] Loaded 16 custom color names!
[03:34:45 INFO]: [Jobs] Loaded 0 custom potion names!
[03:34:45 INFO]: [Jobs] Loaded 4 shop items!
[03:34:45 WARN]: [Jobs] Job Miner has an invalid Break type property: NETHER_BRICK (NETHER_BRICK)! Material must be a block!
[03:34:45 WARN]: [Jobs] Job Farmer has an invalid Break type property: CHORUS_PLANT!
[03:34:45 WARN]: [Jobs] Job Farmer has an invalid Break type property: CHORUS_FLOWER!
[03:34:45 WARN]: [Jobs] Job Farmer has an invalid Break type property: BEETROOT_BLOCK-3!
[03:34:45 INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[03:34:45 WARN]: java.lang.NullPointerException
[03:34:45 WARN]:        at com.gamingmesh.jobs.CMILib.ItemManager$CMIEntityType.isAlive(ItemManager.java:587)
[03:34:45 WARN]:        at com.gamingmesh.jobs.config.ConfigManager.loadJobSettings(ConfigManager.java:926)
[03:34:45 WARN]:        at com.gamingmesh.jobs.config.ConfigManager.reload(ConfigManager.java:72)
[03:34:45 WARN]:        at com.gamingmesh.jobs.Jobs.reload(Jobs.java:606)
[03:34:45 WARN]:        at com.gamingmesh.jobs.Jobs.startup(Jobs.java:538)
[03:34:45 WARN]:        at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:812)
[03:34:45 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[03:34:45 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[03:34:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[03:34:45 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[03:34:45 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[03:34:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[03:34:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[03:34:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[03:34:45 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[03:34:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[03:34:45 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by montlikadani** [comment]
For the time being, it still does not work, and now there is no long console error: [commit](https://github.com/Zrips/Jobs/commit/ebc6c99dc20c27b94f373055508ab4489dc936fc#diff-2bbefed2dca880e596848b248efa0102)

**Comment by Zrips** [comment]
fe9d6960c7485fc7fbd537e25b9289d64930eaed
