### ISSUE TITLE
Pls Fix!! i can't wait

### ISSUE THREAD

**Issue by a7ssan** [Zrips/Jobs#256]
```
10.10 14:22:32 [Server] INFO There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
10.10 14:22:32 [Server] WARN java.lang.NullPointerException
10.10 14:22:32 [Server] WARN at com.gamingmesh.jobs.config.ConfigManager.loadJobSettings(ConfigManager.java:409)
10.10 14:22:32 [Server] WARN at com.gamingmesh.jobs.config.ConfigManager.reload(ConfigManager.java:72)
10.10 14:22:32 [Server] WARN at com.gamingmesh.jobs.Jobs.reload(Jobs.java:606)
10.10 14:22:32 [Server] WARN at com.gamingmesh.jobs.Jobs.startup(Jobs.java:538)
10.10 14:22:32 [Server] WARN at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:812)
10.10 14:22:32 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
10.10 14:22:32 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
10.10 14:22:32 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
10.10 14:22:32 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
10.10 14:22:32 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
10.10 14:22:32 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
10.10 14:22:32 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
10.10 14:22:32 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
10.10 14:22:32 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
```

**Comment by montlikadani** [comment]
The jobsConfig.yml file exists? And are there jobs in the file?

**Comment by DmitryRendov** [comment]
Cant wait)) lol... Try to remove config folder, restart server to get new one and compare with yours old if that helps

**Comment by a7ssan** [comment]
> Q1: The jobsConfig.yml file exists? Q2: And are there jobs in the file?

A1: yea its in files ,
 A2: Yes, there are

My server version 1.8.8 PaperSpigot

**Comment by a7ssan** [comment]
the issue not closed Sorry
