### ISSUE TITLE
The latest version of Jobs doesnt work on 1.12.2 server

### ISSUE THREAD

**Issue by ACluco1** [Zrips/Jobs#285]
Hello, i want to update plugin, but on server startup i got this error and jobs are just disabled.

```
[04:00:08 INFO]: [Jobs] Enabling Jobs v4.9.1
[04:00:08 INFO]: [Jobs] Loaded 4 titles!
[04:00:08 INFO]: [Jobs] Loaded 48 protected blocks timers!
[04:00:08 WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[04:00:08 WARN]: at com.gamingmesh.jobs.config.NameTranslatorManager.readFile(NameTranslatorManager.java:150)
[04:00:08 WARN]: at com.gamingmesh.jobs.config.NameTranslatorManager.load(NameTranslatorManager.java:479)
[04:00:08 WARN]: at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:359)
[04:00:08 WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:600)
[04:00:08 WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:533)
[04:00:08 WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:807)
[04:00:08 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[04:00:08 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[04:00:08 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[04:00:08 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[04:00:08 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[04:00:08 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[04:00:08 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[04:00:08 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[04:00:08 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[04:00:08 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[04:00:08 WARN]: at java.lang.Thread.run(Thread.java:745)
[04:00:08 INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
```

**Comment by montlikadani** [comment]
You can check this comment: https://github.com/Zrips/Jobs/issues/283#issuecomment-436291200
