### ISSUE TITLE
missing (not found) locale/Messages_en.yml

### ISSUE THREAD

**Issue by xinxcode** [Zrips/Jobs#294]
```
[22:47:03] [Server thread/INFO]: [Jobs] Enabling Jobs v4.9.2
[22:47:07] [Server thread/WARN]: java.lang.IllegalArgumentException: The embedded resource 'locale/messages_en.yml' cannot be found in plugins\Jobs4.9.2.jar
[22:47:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:195)
[22:47:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.YmlMaker.saveDefaultConfig(YmlMaker.java:94)
[22:47:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.LanguageManager.load(LanguageManager.java:102)
[22:47:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:350)
[22:47:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:600)
[22:47:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:533)
[22:47:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:808)
[22:47:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:47:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:47:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[22:47:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[22:47:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[22:47:07] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[22:47:07] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[22:47:07] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[22:47:07] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[22:47:07] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[22:47:07] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:47:07] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
```

**Comment by montlikadani** [comment]
#293

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/855cea13ef91f18d82c8930640c9afad21a57555
