### ISSUE TITLE
1.13.2 error on startup

### ISSUE THREAD

**Issue by baxandrei** [Zrips/Jobs#306]
```[18:52:06] [Server thread/INFO]: [0;33;1m[Jobs] Loaded 8 titles![m
[18:52:07] [Server thread/INFO]: [0;33;1m[Jobs] Loaded 45 protected blocks timers![m
[18:52:07] [Server thread/INFO]: [0;33;1m[Jobs] Loaded 641 custom item names![m
[18:52:07] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[18:52:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.NameTranslatorManager.readFile(NameTranslatorManager.java:167)
[18:52:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.NameTranslatorManager.load(NameTranslatorManager.java:504)
[18:52:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:360)
[18:52:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:600)
[18:52:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:533)
[18:52:07] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:808)
[18:52:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[18:52:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[18:52:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[18:52:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434)
[18:52:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348)
[18:52:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
[18:52:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
[18:52:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
[18:52:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[18:52:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[18:52:07] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:52:07] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.```

**Comment by montlikadani** [comment]
You can check this comment: https://github.com/Zrips/Jobs/issues/283#issuecomment-436291200

**Comment by baxandrei** [comment]
Thanx.
