### ISSUE TITLE
Quests Broken? Could not pass event BlockBreakEvent (Using the 1st example quest)

### ISSUE THREAD

**Issue by BoozleDoof** [Zrips/Jobs#332]
```
[07:13:25] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Jobs v4.9.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1176) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at com.gamingmesh.jobs.container.JobsPlayer.getQuestProgressions(JobsPlayer.java:891) ~[?:?]
	at com.gamingmesh.jobs.Jobs.checkDailyQuests(Jobs.java:897) ~[?:?]
	at com.gamingmesh.jobs.Jobs.action(Jobs.java:1018) ~[?:?]
	at com.gamingmesh.jobs.Jobs.action(Jobs.java:919) ~[?:?]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:408) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[custom.jar:git-Spigot-518206a-a5b9c7b]
	... 17 more
```
**Problem Description**
Whenever I add a section for the quests into jobConfig.yml, upon running the **/jobs reload** command the server spits out the error code above.

**Server Version**: Craftbukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Jobs Version**: 4.9.5

Plugin Configuration Folder (includes jobConfig.yml
[Jobs.zip](https://github.com/Zrips/Jobs/files/2763115/Jobs.zip)

**Comment by BoozleDoof** [comment]
After further testing, it seems like a server restarts has allowed the quest to operate.
```/jobs reload``` may not be completely updating this feature.
With the same configuration that was broken prior, it is now working after a server restart.
