### ISSUE TITLE
Error mcmmo compatibility 

### ISSUE THREAD

**Issue by LogGits** [Zrips/Jobs#340]
Jobs 4.9.5 has an error with the new mcMMO 2.1.2. The latest version of mcMMO can be found [here](https://ci.ecocitycraft.com/job/McMMO/) for testing.

```
ERROR 30/01/2019 17:31:23
17:31:23Could not pass event McMMOPlayerAbilityActivateEvent to Jobs v4.9.5
Console 30/01/2019 17:31:23
17:31:23java.lang.NoSuchMethodError: com.gmail.nossr50.events.skills.abilities.McMMOPlayerAbilityActivateEvent.getAbility()Lcom/gmail/nossr50/datatypes/skills/AbilityType;
at com.gamingmesh.jobs.listeners.McMMOlistener.OnAbilityOn(McMMOlistener.java:66) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor614.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-510]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
at com.gmail.nossr50.util.EventUtils.callPlayerAbilityActivateEvent(EventUtils.java:146) ~[?:?]
at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkAbilityActivation(McMMOPlayer.java:825) ~[?:?]
at com.gmail.nossr50.listeners.BlockListener.onBlockDamage(BlockListener.java:437) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor106.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-510]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:373) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:184) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1285) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-510]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-510]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-510]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by Zrips** [comment]
af4d6ce282dfed17dc5d04d03ff1aa86970a8a3d
