### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by LogGits** [Zrips/Jobs#342]
```

WARN 30/01/2019 20:44:54
20:44:54 at com.gamingmesh.jobs.config.GeneralConfigManager.loadGeneralSettings(GeneralConfigManager.java:414)
at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:343)
at com.gamingmesh.jobs.Jobs.reload(Jobs.java:613)
at com.gamingmesh.jobs.Jobs.startup(Jobs.java:546)
at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:828)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
at java.lang.Thread.run(Thread.java:748)
INFO 30/01/2019 20:44:54
20:44:54There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
WARN 30/01/2019 20:44:54
20:44:54java.lang.NullPointerException
at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:877)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256)
at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:869)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
at java.lang.Thread.run(Thread.java:748)
INFO 30/01/2019 20:44:54
20:44:54[Jobs]: Plugin has been disabled successfully.
```

**Comment by Zrips** [comment]
95f922e1518b57239d02c840fedf508a869adfa6
