### ISSUE TITLE
plugin is disabled

### ISSUE THREAD

**Issue by successed** [Zrips/Jobs#368]
```
[13:03:14 INFO]: izmirmc issued server command: /jobs
[13:03:14 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'jobs' in plugin Jobs v4.10.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-529]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-529]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by montlikadani** [comment]
Plugin is disabled check your server software. You need to use Spigot/Bukkit/Paper software to prevent this issue. And check your server plugins that preventing the Jobs plugin start at server boot.

**Comment by soaphacker** [comment]
i dont really know, it gives me that error too, can someone help? im tryng to run shopGUI+ on Gravelhost, is it ok?
