### ISSUE TITLE
Cannot execute command 'jobs' in plugin Jobs v4.10.2

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/Jobs#376]
**In the latest version you can no longer run /jobs stats. Es comes with the following in the console:**
```
17:48:41] [Server thread/INFO]: Blueeyestar issued server command: /jobs stats
[17:48:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'jobs' in plugin Jobs v4.10.2 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[17:48:45] [Server thread/INFO]: Blueeyestar issued server command: /jobs stats
[17:48:45] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'jobs' in plugin Jobs v4.10.2 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by montlikadani** [comment]
Descibes "Cannot execute command 'jobs' in plugin Jobs v4.10.2 - plugin is disabled.", the plugin disabled, so you need to enable.

**Comment by Blueeyestar** [comment]
[17:59:59] [Server thread/INFO]: [Jobs] Enabling Jobs v4.10.2
[18:00:02] [Server thread/INFO]: [0;33;1m[Jobs] PlaceholderAPI hooked.[m
[18:00:02] [Server thread/INFO]: [0;33;1mPlaceholderAPI was found - Enabling capabilities.[m
[18:00:02] [Server thread/WARN]: java.lang.Error: Unresolved compilation problem: 
	The type java.util.function.Consumer cannot be resolved. It is indirectly referenced from required .class files

[18:00:02] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.ActionBarTitleMessages.<init>(ActionBarTitleMessages.java:118)
[18:00:02] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.setActionBar(Jobs.java:314)
[18:00:02] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:815)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[18:00:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:00:02] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[18:00:02] [Server thread/WARN]: java.lang.NullPointerException
[18:00:02] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:893)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256)
[18:00:02] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:886)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[18:00:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[18:00:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[18:00:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:00:02] [Server thread/ERROR]: Error occurred while enabling Jobs v4.10.2 (Is it up to date?)
java.lang.NullPointerException: null
	at com.gamingmesh.jobs.Jobs.shutdown(Jobs.java:670) ~[?:?]
	at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:901) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:886) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [Spigot-latest.jar:git-Spigot-4165cd8-cb98c6e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by montlikadani** [comment]
Try restart the server.

**Comment by Blueeyestar** [comment]
Is this a joke? The server's been restarted x times. The plugin is not accepted

**Comment by montlikadani** [comment]
Do you please take a screenshot about the server plugins? In the plugins folder.

**Comment by Blueeyestar** [comment]
![screen](https://user-images.githubusercontent.com/35557302/53585622-a3b95780-3b86-11e9-8af1-51b8fa1e8056.png)

**Comment by montlikadani** [comment]
Try the Jobs plugin without using CMI plugin.

**Comment by Blueeyestar** [comment]
The same error even without CMI

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/a377ad08dba48bf93189065eeb228553294a8230
