### ISSUE TITLE
/jobs convert (times two)

### ISSUE THREAD

**Issue by El-pika** [Zrips/Jobs#378]
Sorry about that, still not working with the last patch :(

jobs convert
```
[01:07:11 WARN]: Unexpected exception while parsing console command "jobs convert"
org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin Jobs v4.10.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:684) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
at com.gamingmesh.jobs.Jobs.ChangeDatabase(Jobs.java:671) ~[?:?]
at com.gamingmesh.jobs.commands.list.convert.perform(convert.java:42) ~[?:?]
at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:109) ~[?:?]
at org.bukkit.command.PluginCommand.execute(Plu
ginCommand.java:44) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
... 8 more
```

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/2c0451aa55e097f31125ce16b7e56cfad4d858de
