### ISSUE TITLE
DB conversion error

### ISSUE THREAD

**Issue by HgeX** [Zrips/Jobs#403]
So a couple of days ago I tried to convert my Jobs SQLite database to MySQL, but it resulted in the following exception:

`[23:18:22] [Server thread/WARN]: Unexpected exception while parsing console command "jobs convert"
org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin Jobs v4.10.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-621]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-621]
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-621]
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[patched_1.13.2.jar:git-Paper-621]
    at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[patched_1.13.2.jar:git-Paper-621]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.13.2.jar:git-Paper-621]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-621]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-621]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
    at com.gamingmesh.jobs.Jobs.ChangeDatabase(Jobs.java:671) ~[?:?]
    at com.gamingmesh.jobs.commands.list.convert.perform(convert.java:42) ~[?:?]
    at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:109) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-621]
    ... 8 more`

Plugin version: Jobs v4.10.3

**Comment by montlikadani** [comment]
Try with installing the dev version from [Releases](https://github.com/Zrips/Jobs/releases) tab.

**Comment by HgeX** [comment]
I've tested the db conversion with the version that you suggested and it works more or less. It connects to the database no problem, creates all the necessary tables, but after that (when the plugin is importing data from the old database I guess) the server starts lagging, crashing, and soon the watchdog thread kills it.
