### ISSUE TITLE
Shop malfunctioning

### ISSUE THREAD

**Issue by HgeX** [Zrips/Jobs#404]
Since version 4.10.3 my players cannot buy enchanted books from the Jobs shop. What happens all the time is that they get the book but with no enchantments. This feature worked perfectly in version 4.9.5.

**Comment by montlikadani** [comment]
Does you used the `Enchants` section?

**Comment by HgeX** [comment]
Yes I did

`mending:
    Price: 4200.0
    Icon:
      Id: 403
      Name: "&bVarázskönyv"
      Lore:
      - "&f➸ &eÖnjavítás"
      HideWithoutPermission: true
    RequiredPermission:
    - jobs.item.mending
    RequiredTotalLevels: 35
    # (Optional) Gives items by defined criteria
    GiveItems:
      # Can be any word
      PickAxe:
        # (Required) Item id
        Id: 'enchanted_book'
        # (Optional - Default: 0) Item data
        Data: 0
        # (Optional - Default: 1) Item amount
        Amount: 1
        # (Optional) Item name
        Name: ""
        # (Optional) Item lore
        Lore:
        - ""
        # (Optional) Item enchants
        Enchants:
        - MENDING=1`

**Comment by montlikadani** [comment]
It seems you using the Id of item. Please change 403 to `Id: enchanted_book` and remove Data integer.

_Látom magyar vagy, de beszéljünk egyelőre magyarul_

**Comment by HgeX** [comment]
Okay, I'll do that today, and let you known if it solves my issue.

**Comment by HgeX** [comment]
I've retested the shop with the suggested changed, but unfortunately nothing really changed. This is the current configuration:

`  mending:
    Price: 4200.0
    Icon:
      Id: 403
      Name: "&bVarázskönyv"
      Lore:
      - "&f➸ &eÖnjavítás"
      HideWithoutPermission: true
    RequiredPermission:
    - jobs.item.mending
    RequiredTotalLevels: 35
    # (Optional) Gives items by defined criteria
    GiveItems:
      # Can be any word
      PickAxe:
        # (Required) Item id
        Id: 'enchanted_book'
        # (Optional - Default: 1) Item amount
        Amount: 1
        # (Optional) Item name
        Name: ""
        # (Optional) Item lore
        Lore:
        - ""
        # (Optional) Item enchants
        Enchants:
        - MENDING=1 `

When I changed the Icon.Id to `enchanted_book`, the plugin wasn't able to parse it: `[09:55:14] [Server thread/ERROR]: [Jobs] Shop item mending has an invalid Icon Id property. Skipping! `. So I changed it back to `403`. But then I thought maybe I should change the Id in the 'GiveItems' section to `enchanted_book`. After that I got the following exception every time, when I clicked in the shop menu:

`
[10:03:00] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Jobs v4.10.3
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2144) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
    at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft.jar:git-Spigot-2474d93-e693496]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft.jar:git-Spigot-2474d93-e693496]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft.jar:git-Spigot-2474d93-e693496]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft.jar:git-Spigot-2474d93-e693496]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft.jar:git-Spigot-2474d93-e693496]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
    at com.gamingmesh.jobs.config.ShopManager.checkSlot(ShopManager.java:124) ~[?:?]
    at com.gamingmesh.jobs.listeners.JobsListener.onShopGuiClick(JobsListener.java:205) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft.jar:git-Spigot-2474d93-e693496]
    ... 15 more`

So I changed it back to `403`. So the problem remained the same, when buying an enchanted book, I get the book, but no enchantments

**Comment by HgeX** [comment]
What's interesting for me is that enchants work perfectly with other items:

`  szerencsecsakany:
    Price: 2800.0
    Icon:
      Id: 278
      Name: "&cGyémántcsákány"
      Lore:
      - "&f➸ &eSzerencse III"
      HideWithoutPermission: true
    RequiredPermission:
    - jobs.item.szerencsecsakany
    RequiredJobLevels:
    - Miner-15
    # (Optional) Gives items by defined criteria
    GiveItems:
      # Can be any word
      PickAxe:
        # (Required) Item id
        Id: 278
        # (Optional - Default: 0) Item data
        Data: 0
        # (Optional - Default: 1) Item amount
        Amount: 1
        # (Optional) Item name
        Name: ""
        # (Optional) Item lore
        Lore:
        - ""
        # (Optional) Item enchants
        Enchants:
        - LOOT_BONUS_BLOCKS=3`

**Comment by montlikadani** [comment]
@HgeX Mindegy, magyarul... Tehát az item `Id: 278`-at megváltoztattad `Id: diamond_pickaxe`-ra és azt a verziót használod, amit elküldtem?

**Comment by HgeX** [comment]
Bocsi, hogy eddig nem reagáltam. :( Szóval igen, a dev verzióval próbáltam ki a shopot. Ez már nem is működött az id-kkel, tehát mindenhol a material név lett megadva. A hiba viszont továbbra is jelen van, hiába próbálok enchantolt könyvet megadni, csak egy sima varázskönyvet kapok, függetlenül attól, hogy az `enchants` részben mit adtam meg. Kipróbtam egyébként azzal az alapkonfiggal is, amit a plugin hoz létre magának, és azzal sem volt jó. Ez a jelenlegi konfigom: 
`  mending:
    Price: 4200.0
    Icon:
      Id: "enchanted_book"
      Name: "&bVarázskönyv"
      Lore:
      - "&f➸ &eÖnjavítás"
      HideWithoutPermission: true
    RequiredPermission:
    - jobs.item.mending
    RequiredTotalLevels: 35
    # (Optional) Gives items by defined criteria
    GiveItems:
      # Can be any word
      PickAxe:
        # (Required) Item id
        Id: "enchanted_book"
        # (Optional - Default: 1) Item amount
        Amount: 1
        # (Optional) Item name
        Name: ""
        # (Optional) Item lore
        Lore:
        - ""
        # (Optional) Item enchants
        Enchants:
        - MENDING=1

`

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/472112377f1f5b194640fd63c43d999a137ab027
