### ISSUE TITLE
1.14 Experimental Build Money Issue

### ISSUE THREAD

**Issue by LordBanshee** [Zrips/Jobs#409]
Server Version: 1.14 Spigot
Plugin Version: 4.11.0Experimental

Using the most up to date version of EssentialsX, Vault, and your plugin, I am not able to receive money for completing job related tasks. The only two jobs I've tested are Mining and Hunting, but both are critical functions of the plugin. I am also not receiving points. I haven't seen anything in my server console related to Jobs besides the basic loading messages, either.

Thanks!

**Comment by Zrips** [comment]
By default players in creative will not get paid. So check that one. Other then this you should see indication in console what economy plugin Jobs will use on server startup. So check that one too. And then simply check what you should get for which blocks with /jobs info miner

**Comment by Doot0Doot** [comment]
I'm also having this issue with those exact plugins and versions.

**Comment by Resi23** [comment]
Same here
`[12:55:55] [Craft Scheduler Thread - 1/WARN]: [Jobs] Plugin Jobs v4.11.1 generated an exception while executing task 506
java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
	at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
	at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:174) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:166) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.tryDepositPlayer(Economy_Essentials.java:149) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:180) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
	at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
	at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:40) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.jar:git-Spigot-1eece4f-09a453a]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

**Comment by dan101201** [comment]
when is the version where its fixed coming out
