### ISSUE TITLE
Players will not earn money from job - java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.

### ISSUE THREAD

**Issue by farizluqman** [Zrips/Jobs#414]
This is the error log:

```
[22:56:53] [Craft Scheduler Thread - 4/WARN]: [Jobs] Plugin Jobs v4.11.1 generated an exception while executing task 68
java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-Spigot-1eece4f-ee88184]
	at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
	at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:174) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:166) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.tryDepositPlayer(Economy_Essentials.java:149) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:180) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
	at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
	at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:40) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-1eece4f-ee88184]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-1eece4f-ee88184]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[22:56:56] [Server thread/INFO]: EarnestAngel issued server command: /bal
[22:56:58] [Craft Scheduler Thread - 4/WARN]: [Jobs] Plugin Jobs v4.11.1 generated an exception while executing task 71
java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-Spigot-1eece4f-ee88184]
	at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
	at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:174) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:166) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.tryDepositPlayer(Economy_Essentials.java:149) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:180) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
	at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
	at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:40) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-1eece4f-ee88184]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-1eece4f-ee88184]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/409
