### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/Jobs#424]
```
[14:35:11] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Jobs v4.11.0
java.lang.NoSuchMethodError: io.lumine.xikage.mythicmobs.mobs.MythicMob.getDisplayName()Ljava/lang/String;
	at com.gamingmesh.jobs.MythicMobs.MythicMobs4.getDisplayName(MythicMobs4.java:64) ~[?:?]
	at com.gamingmesh.jobs.config.NameTranslatorManager.Translate(NameTranslatorManager.java:120) ~[?:?]
	at com.gamingmesh.jobs.container.JobInfo.getRealisticName(JobInfo.java:83) ~[?:?]
	at com.gamingmesh.jobs.Gui.GuiManager.CreateJobsSubGUI(GuiManager.java:205) ~[?:?]
	at com.gamingmesh.jobs.listeners.JobsListener.onGuiLeftClick(JobsListener.java:243) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1320.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-626]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-626]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-626]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2288) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-626]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-626]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by montlikadani** [comment]
Could you please send more information about plugin?
The jobConfig file about the job.

**Comment by p82183645** [comment]
> Could you please send more information about plugin?
> The jobConfig file about the job.

https://www.dropbox.com/s/aw29dfge3ohcqdj/jobConfig.yml?dl=0

**Comment by montlikadani** [comment]
The `Hunter` job in `MMKill` action, these names in the MythicMob is exist?

**Comment by p82183645** [comment]
> The `Hunter` job in `MMKill` action, these names in the MythicMob is exist?

yes

**Comment by p82183645** [comment]
> The `Hunter` job in `MMKill` action, these names in the MythicMob is exist?


4.10 no this error

**Comment by montlikadani** [comment]
What MythicMob version are you using?

**Comment by montlikadani** [comment]
Now I tested this, and this working properly for me. Make sure you have using the latest free version of MythicMob plugin and using the dev. version of Jobs in [Releases](https://github.com/Zrips/Jobs/releases) tab. We only supports the free version.

**Comment by p82183645** [comment]
> Now I tested this, and this working properly for me. Make sure you have using the latest free version of MythicMob plugin and using the dev. version of Jobs in [Releases](https://github.com/Zrips/Jobs/releases) tab. We only supports the free version.

mm 4.7 no free

**Comment by Zrips** [comment]
MythicMobs 2.7 changed its API which causes this issue to appear. For time being it will not be supported until we can get access to new version which can be used in compiling a plugin. 
7cbdf517135abe67d92f880d4768826427135ce7
