### ISSUE TITLE
Don't get money from jobs

### ISSUE THREAD

**Issue by dan101201** [Zrips/Jobs#428]
[14:57:34] [Craft Scheduler Thread - 5/WARN]: [Jobs] Plugin Jobs v4.11.1 generated an exception while executing task 307
java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
        at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:174) ~[?:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:166) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.tryDepositPlayer(Economy_Essentials.java:149) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:180) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
        at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
        at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/414
