### ISSUE TITLE
1.14.1 money bug, i have jobs v4.11.2

### ISSUE THREAD

**Issue by successed** [Zrips/Jobs#433]
[00:12:54] [Craft Scheduler Thread - 60/WARN]: [Jobs] Plugin Jobs v4.11.2 generated an exception while executing task 127037
java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
        at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
        at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
        at com.earth2me.essentials.api.Economy.substract(Economy.java:198) ~[?:?]
        at com.earth2me.essentials.api.Economy.subtract(Economy.java:190) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.withdrawPlayer(Economy_Essentials.java:107) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.withdrawPlayer(AbstractEconomy.java:40) ~[?:?]
        at com.gamingmesh.jobs.economy.VaultEconomy.withdrawPlayer(VaultEconomy.java:43) ~[?:?]
        at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [paperclip.jar:git-Spigot-03bd4b0-17da342]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Zrips** [comment]
Switch economy-async to false until essentials fix this issue at their end. And report this issue at their github too, just to speed up their update.
