### ISSUE TITLE
Paperspigot 1.14.4 compatibility issue

### ISSUE THREAD

**Issue by ItsSynchro** [Zrips/Jobs#485]
***Description of issue:**
JobsReborn does not load up on 1.14.4
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## [15:28:50 INFO]: ItsSynchro issued server command: /jobs
[15:28:50 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'jobs' in plugin Jobs v4.13.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-135]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
 ##
####################
```

---

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):**  Paper version git-Paper-135 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
Full console error please.
