### ISSUE TITLE
Collect Event (Berrys and Composter)

### ISSUE THREAD

**Issue by Minersheart** [Zrips/Jobs#575]
***Description of issue:**

User can earn Money and Job XP on other players ground.
He cant destroy or build there but on permanent left mouseklick they earn .---

Oly at SweetBerrys and Composters (with interrups while breaking the block)
semms to be the Collect evet and the rights (permissions) on it
.**CONFIG SECTION (DELETE IF NOT RELEVANT):**
#      Collect:
#      sweet_berry_bush-3:
#        income: 0.2
#        points: 1.0
#        experience: 1.5
#      composter:
#        income: 0.2
#        points: 1.0
#        experience: 1.5
```

---

**Server Type (Spigot/Paperspigot/etc):** 
paper 1.14 latest
**Server Version (using `/ver`):** 
ubuntu
**Relevant plugins (Delete if this isn't needed):**
CMI ,Jobs Reborne, luckperms all latest

**Comment by montlikadani** [comment]
Can you please write it more explain your problem?
The player will get money if right clicking on the composter or bush, and if the player clicks left will breaks, and will not get income.

**Comment by Minersheart** [comment]
on permanently mouseclick with no rights to build or break on the ground (other people ground) they get money and job xp the effect appears after 2 or 3 seconds...in the normal case on the own ground it seems to be the normal earning to the job ...

**Comment by montlikadani** [comment]
Well, this fixed in [this commit](https://github.com/Zrips/Jobs/commit/648c6f412a5e0d0a1dd2eba2da6bed0e2ee930a6), so you need to compile this project to download the test jar.

**Comment by Minersheart** [comment]
Sorry but how to copile the Project with Eclpise IDE i get the error Invalid plugin.yml and i cant get it valid.

**Comment by Minersheart** [comment]
[09:41:59 ERROR]: Could not load 'plugins\JobsReborne.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPlug
inLoader.java:159) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:142) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.j
ava:355) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:8
57) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.Bukkit.reload(Bukkit.java:610) ~[patched_1.14.4.jar:git-Pa
per-159]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:
54) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:15
9) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServ
er.java:739) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(Cra
ftServer.java:701) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(Dedi
catedServer.java:456) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:
418) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:
1074) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:918) ~[patched_1.14.4.jar:git-Paper-159]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 14 more

**Comment by Minersheart** [comment]
pls give me a link
https://dev.bukkit.org/projects/jobs-reborn here are three links but i get the same project or wich one is it to use...!!??

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/tree/master/src/main/resources

**Comment by Minersheart** [comment]
Sorry i cant get it done help me im stupid...grrr

[18:13:29 ERROR]: Could not load 'plugins\JobsReborne.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPlug
inLoader.java:159) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:142) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.j
ava:355) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.ja
va:226) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:869) ~[patched_1.14.4.jar:git-Paper-159]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by Minersheart** [comment]
I added the plugin.yml with this result..!!

**Comment by Minersheart** [comment]
It seems to be already fixed...after the correct compiling
