### ISSUE TITLE
Jobs4.14.1Overload

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/Jobs#582]
***HELP***HELP***HELP***

Spigot-Ver:CraftBukkit version git-Spigot-56f8471-7554e08 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

I'm having problems with the version of Jobs4.14.1. It takes too much server performance. More than 28-35% of the total server performance is consumed by jobs. This is too much. Now I wanted to switch back to the stable Jobs4.13.1. This is no longer possible because Jobs4.14.1 destroyed them. It always comes with loading in the console:

[11:18:29] [Server thread/INFO]: [Jobs] Loaded 2 schedulers!
[11:18:29] [Server thread/INFO]: [Jobs] Preloaded 454 players data in 0.0
[11:18:29] [Server thread/WARN]: java.lang.IllegalArgumentException: Name cannot be null
[11:18:29] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[11:18:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.getWorld(CraftServer.java:1029)
[11:18:29] [Server thread/WARN]: 	at org.bukkit.Bukkit.getWorld(Bukkit.java:491)
[11:18:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.dao.JobsDAO.loadBlockProtection(JobsDAO.java:1735)
[11:18:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:968)
[11:18:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:18:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[11:18:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[11:18:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[11:18:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[11:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[11:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266)
[11:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[11:18:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:18:29] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[11:18:29] [Jobs-DatabaseSaveTask/INFO]: [Jobs] Database save task shutdown!
[11:18:29] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.

![jobs2](https://user-images.githubusercontent.com/35557302/67851898-b3b97a80-fb0b-11e9-8ff2-4046960b6af3.png)

Please fix quickly .. or give a tip as I can take the old version again

The server is only jerky since Jobs overloaded the server !!! I need urgent help!!

**Comment by banit** [comment]
https://timings.aikar.co/?id=de0320cfad6148eb913aedb7c73afa9d
same issue.. new jobs update kills performance

**Comment by Zrips** [comment]
633ad3dcc3f9a92ac07a8a341eee196c4b8d7fc1
