### ISSUE TITLE
IllegalStateException at DepositRequestEvent

### ISSUE THREAD

**Issue by Padlick01** [Zrips/Jobs#584]
**Description of issue:**
When somebody has an job and do their thing, Jobs pl spams the console with following error:
---

```
[16:31:39 WARN]: [Jobs] Plugin Jobs v4.14.1 generated an exception while executing task 167983
java.lang.IllegalStateException: DepositRequestEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-221]
        at us._donut_.skvault.CustomEconomy.depositPlayer(CustomEconomy.java:105) ~[?:?]
        at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
        at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-221]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

---

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-221 (MC: 1.14.4)

**Comment by montlikadani** [comment]
This is not jobs plugin problem, this is your economy plugin.
