### ISSUE TITLE
Same Problem with Overload... installing the old version throws this into console

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/Jobs#585]
***Description of issue:**
Nullpointer and then disabling Plugin
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:34:04] [Jobs-DatabaseSaveTask/INFO]: [Jobs] Started database save task.
[17:34:04] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Started buffered payment thread.
[17:34:04] [Server thread/INFO]: [Jobs] Preloaded 231 players data in 0.01
[17:34:04] [Server thread/INFO]: [Jobs] WorldGuard detected.
[17:34:04] [Server thread/WARN]: java.lang.IllegalArgumentException: Name cannot be null
[17:34:04] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[17:34:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.getWorld(CraftServer.java:1079)
[17:34:04] [Server thread/WARN]: 	at org.bukkit.Bukkit.getWorld(Bukkit.java:525)
[17:34:04] [Server thread/WARN]: 	at com.gamingmesh.jobs.dao.JobsDAO.loadBlockProtection(JobsDAO.java:1735)
[17:34:04] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:968)
[17:34:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:34:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[17:34:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[17:34:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[17:34:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[17:34:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[17:34:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[17:34:04] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[17:34:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:34:04] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[17:34:04] [Jobs-DatabaseSaveTask/INFO]: [Jobs] Database save task shutdown!
[17:34:04] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.
```

---

**Server Type (Spigot/Paperspigot/etc):** 

Paper 218

**Comment by Blueeyestar** [comment]
The problem is already reported, we have the same problem
https://github.com/Zrips/Jobs/issues/582

**Comment by Zrips** [comment]
633ad3dcc3f9a92ac07a8a341eee196c4b8d7fc1
