### ISSUE TITLE
SQLite Error

### ISSUE THREAD

**Issue by UmbreonMajora** [Zrips/Jobs#586]
***Description of issue:**
SQLite Error
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[12:58:04] [Server thread/INFO]: [Jobs] Converting to new database format
[12:58:04] [Server thread/WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: blocks.world)
[12:58:04] [Server thread/WARN]:     at org.sqlite.core.DB.newSQLException(DB.java:941)
[12:58:04] [Server thread/WARN]:     at org.sqlite.core.DB.newSQLException(DB.java:953)
[12:58:04] [Server thread/WARN]:     at org.sqlite.core.DB.execute(DB.java:854)
[12:58:04] [Server thread/WARN]:     at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:56)
[12:58:04] [Server thread/WARN]:     at com.gamingmesh.jobs.dao.JobsDAO.convertID(JobsDAO.java:996)
[12:58:04] [Server thread/WARN]:     at com.gamingmesh.jobs.dao.JobsDAO.access$200(JobsDAO.java:42)
[12:58:04] [Server thread/WARN]:     at com.gamingmesh.jobs.dao.JobsDAO$1.run(JobsDAO.java:958)
[12:58:04] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[12:58:04] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[12:58:04] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022)
[12:58:04] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393)
[12:58:04] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970)
[12:58:04] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815)
[12:58:04] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:748)
```

---

**Server Type (Spigot/Paperspigot/etc) Spigot:** 

**Server Version (using `/ver`): 1.14.4**

**Comment by Zrips** [comment]
Plugin version?
