### ISSUE TITLE
jobs reborn problem latest version

### ISSUE THREAD

**Issue by DrTableBasse** [Zrips/Jobs#589]
[16:43:12 WARN]: [Jobs] Plugin Jobs v4.14.2 generated an exception while executing task 1805
java.lang.IllegalStateException: UserBalanceUpdateEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-221]
        at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
        at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:174) ~[?:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:166) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.tryDepositPlayer(Economy_Essentials.java:149) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:180) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
        at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32) ~[?:?]
        at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-221]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by Straiker123** [comment]
Similar problem as here https://github.com/Zrips/Jobs/issues/587

**Comment by montlikadani** [comment]
This is not jobs plugins problem, this is the economy plugin, when calling the economy take, set or other, it will calls a new event, which sometimes needs asynchronous task. Same as https://github.com/Zrips/Jobs/issues/584
