### ISSUE TITLE
Jobs start problem

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/Jobs#608]
***Jobs not started**

```
[04:27:15] [Server thread/INFO]: [Jobs] Loaded 1 schedulers!
[04:27:16] [Server thread/WARN]: java.lang.NullPointerException
[04:27:16] [Server thread/WARN]: 	at com.gamingmesh.jobs.dao.JobsDAO.getAllJobs(JobsDAO.java:672)
[04:27:16] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.loadAllPlayersData(Jobs.java:608)
[04:27:16] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:597)
[04:27:16] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:912)
[04:27:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[04:27:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[04:27:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[04:27:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[04:27:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[04:27:16] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[04:27:16] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[04:27:16] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[04:27:16] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:27:16] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[04:27:16] [Jobs-DatabaseSaveTask/INFO]: [Jobs] Database save task shutdown!


 /jobs
[14:34:57] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'jobs' in plugin Jobs v4.14.3 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-226]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-226]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-226]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

---

**Server Type (Spigot/Paperspigot/etc):** 

Paperspigot

**Server Version (using `/ver`):** 

 This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/3e0ed72a3fca6fe6e01b1985dda5ac5fe9b33ccf
