### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by Filip1004** [Zrips/Jobs#610]
**Description of issue:**
I upgraded Jobs from version 4.5.2 to 4.14.3 and the plugin dont work and showing this error
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:01:03 INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[19:01:03 WARN]: java.lang.NullPointerException
[19:01:03 WARN]: at com.gamingmesh.jobs.config.NameTranslatorManager.readFile(NameTranslatorManager.java:183)
[19:01:03 WARN]: at com.gamingmesh.jobs.config.NameTranslatorManager.load(NameTranslatorManager.java:1780)
[19:01:03 WARN]: at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:357)
[19:01:03 WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:604)
[19:01:03 WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:538)
[19:01:03 WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:812)
[19:01:03 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:01:03 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:01:03 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:01:03 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[19:01:03 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[19:01:03 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[19:01:03 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[19:01:03 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[19:01:03 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[19:01:03 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[19:01:03 WARN]: at java.lang.Thread.run(Thread.java:745)
```

---

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): 1.12.2**

**Comment by montlikadani** [comment]
> 4.5.2

It looks like it's time to upgrade. Delete each file from the Jobs folder and regenerate it by restarting the server.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/6319c69c2958285f59294ffb023b923224979ddb
