### ISSUE TITLE
Placeholder API integration issue

### ISSUE THREAD

**Issue by digital-r** [Zrips/Jobs#623]
Server version: Paper 1.15.1 build #23
Jobs Reborn version: 4.15.0 (latest)
PAPI version: PlaceholderAPI v2.10.5-DEV-82

On server start error logged:

[15:45:04] [Server thread/INFO]: [Jobs] Enabling Jobs v4.15.0-devBuild
[15:45:04] [Server thread/ERROR]: Error occurred while enabling Jobs v4.15.0-devBuild (Is it up to date?)
java.lang.NumberFormatException: For input string: "2105-DEV-82"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
	at com.gamingmesh.jobs.Jobs.setupPlaceHolderAPI(Jobs.java:213) ~[?:?]
	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:874) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-23]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[15:45:04] [Server thread/INFO]: [Jobs] Disabling Jobs v4.15.0-devBuild
[15:45:04] [Server thread/WARN]: java.lang.NullPointerException
[15:45:04] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:969)
[15:45:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[15:45:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
[15:45:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
[15:45:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[15:45:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[15:45:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[15:45:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[15:45:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481)
[15:45:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290)
[15:45:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[15:45:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
[15:45:04] [Server thread/ERROR]: Error occurred while disabling Jobs v4.15.0-devBuild (Is it up to date?)
java.lang.NullPointerException: null
	at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:248) ~[?:?]
	at com.gamingmesh.jobs.Jobs.shutdown(Jobs.java:733) ~[?:?]
	at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:977) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-23]
	at java.lang.Thread.run(Thread.java:844) [?:?]

**Comment by montlikadani** [comment]
PLEASE SEARCH FOR SAME/DUPLICATE ISSUES! https://github.com/Zrips/Jobs/issues/622

**Comment by Blamo27** [comment]
@montlikadani I think you should upload the file build with the CI to prevent this
