### ISSUE TITLE
PlaceholderAPI is not compatible with the latest version of Jobs

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/Jobs#625]
` [Jobs] Enabling Jobs v4.15.0-devBuild
[19:26:11 ERROR]: Error occurred while enabling Jobs v4.15.0-devBuild (Is it up to date?)
java.lang.NumberFormatException: For input string: "2105-DEV-83"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_221]
        at com.gamingmesh.jobs.Jobs.setupPlaceHolderAPI(Jobs.java:213) ~[?:?]
        at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:874) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-25]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[19:26:11 INFO]: [Jobs] Disabling Jobs v4.15.0-devBuild
[19:26:11 WARN]: java.lang.NullPointerException
[19:26:11 WARN]:        at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:969)
[19:26:11 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[19:26:11 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
[19:26:11 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
[19:26:11 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[19:26:11 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[19:26:11 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[19:26:11 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[19:26:11 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481)
[19:26:11 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290)
[19:26:11 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[19:26:11 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:26:11 ERROR]: Error occurred while disabling Jobs v4.15.0-devBuild (Is it up to date?)
java.lang.NullPointerException: null
        at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:248) ~[?:?]
        at com.gamingmesh.jobs.Jobs.shutdown(Jobs.java:733) ~[?:?]
        at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:977) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-25]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

This server is running Paper version git-Paper-25 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

PlaceHolderAPI build:
https://ci.extendedclip.com/job/PlaceholderAPI/83/

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/623
