### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ProAlexYTB** [Zrips/Jobs#626]
When i start the server he give me error

---

Error occurred while enabling Jobs v4.15.0-devBuild (Is it up to date?)
java.lang.NumberFormatException: For input string: "2105-DEV-82"
    at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_231]
    at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_231]
    at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_231]
    at com.gamingmesh.jobs.Jobs.setupPlaceHolderAPI(Jobs.java:213) ~[?:?]
    at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:874) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

---

Spigot

1.15.1

**Comment by montlikadani** [comment]
#625
