### ISSUE TITLE
Nullpointer exception / plugin disabling itself

### ISSUE THREAD

**Issue by nicuch** [Zrips/Jobs#627]
***Description of issue:**
Console error / plugin disabling itself
---

**ERROR:**
```
[16:25:43] [Server thread/WARN]: java.lang.NullPointerException
[16:25:43] [Server thread/WARN]: 	at com.gamingmesh.jobs.dao.JobsDAO.getAllJobs(JobsDAO.java:673)
[16:25:43] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.loadAllPlayersData(Jobs.java:607)
[16:25:43] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:596)
[16:25:43] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:909)
[16:25:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:25:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[16:25:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[16:25:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[16:25:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[16:25:43] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481)
[16:25:43] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290)
[16:25:43] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[16:25:43] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper version git-Paper-27 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
PlaceholderAPI

**Comment by montlikadani** [comment]
#608

**Comment by nicuch** [comment]
Oh, ok. Gonna compile it now. Thanks
