### ISSUE TITLE
Explore Manager Erroring on Startup - Plugin Disabled

### ISSUE THREAD

**Issue by mobilephone2003** [Zrips/Jobs#636]
***Description of issue:**

Jobs is unable to start, and disables itself. There's a few folks who have it and it seems going back versions doesn't solve it.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:44:59] [Server thread/INFO]: [Jobs] Loading explorer data
[19:44:59] [Server thread/WARN]: java.lang.NullPointerException
[19:44:59] [Server thread/WARN]: 	at com.gamingmesh.jobs.container.ExploreChunk.deserializeNames(ExploreChunk.java:106)
[19:44:59] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ExploreManager.load(ExploreManager.java:117)
[19:44:59] [Server thread/WARN]: 	at com.gamingmesh.jobs.dao.JobsDAO.loadExplore(JobsDAO.java:2482)
[19:44:59] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ExploreManager.load(ExploreManager.java:48)
[19:44:59] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:955)
[19:44:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:44:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[19:44:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[19:44:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[19:44:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[19:44:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481)
[19:44:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290)
[19:44:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[19:44:59] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:44:59] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[19:44:59] [Server thread/INFO]: [Jobs] Updated 176 explorer entries.
[19:44:59] [Jobs-DatabaseSaveTask/INFO]: [Jobs] Database save task shutdown!
[19:44:59] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.
[19:44:59] [Server thread/INFO]: [Jobs] Plugin has been disabled successfully.
```

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-33 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/1ecffe18959432c0842228cfcbf3606bb0a9163b
