### ISSUE TITLE
Missing TranslatableWords

### ISSUE THREAD

**Issue by JohnPolyStriker** [Zrips/Jobs#648]
```
`[20:20:10] [Server thread/INFO]: [Jobs] Enabling Jobs v4.15.2
[20:20:10] [Server thread/INFO]: [Jobs] PlaceholderAPI hooked.
[20:20:10] [Server thread/INFO]: PlaceholderAPI was found - Enabling capabilities.
[20:20:11] [Server thread/INFO]: [Jobs] Loaded 8 titles!
[20:20:11] [Server thread/INFO]: [Jobs] Loaded 75 protected blocks timers!
[20:20:11] [Server thread/WARN]: java.lang.IllegalArgumentException: The embedded resource 'TranslatableWords/Words_EN.yml' cannot be found in plugins/Jobs4.15.2.jar
[20:20:11] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:192)
[20:20:11] [Server thread/WARN]: at com.gamingmesh.jobs.config.YmlMaker.saveDefaultConfig(YmlMaker.java:89)
[20:20:11] [Server thread/WARN]: at com.gamingmesh.jobs.config.NameTranslatorManager.readFile(NameTranslatorManager.java:117)
[20:20:11] [Server thread/WARN]: at com.gamingmesh.jobs.config.NameTranslatorManager.load(NameTranslatorManager.java:415)
[20:20:11] [Server thread/WARN]: at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:395)
[20:20:11] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:692)
[20:20:11] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:600)
[20:20:11] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:918)
[20:20:11] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:20:11] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[20:20:11] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[20:20:11] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[20:20:11] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[20:20:11] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456)
[20:20:11] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266)
[20:20:11] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783)
[20:20:11] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[20:20:11] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.`
```

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.15.1

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/12b262b6b4ff847db521a25dd9c2cac7990e7955
