### ISSUE TITLE
Still Missing TranslatableWords

### ISSUE THREAD

**Issue by JohnPolyStriker** [Zrips/Jobs#654]
***Description of issue:**

I reported missing TranslatableWords in v4.15.2. In v4.15.3 it should be fixed but the problem is still here.
---

**ERROR:**
```
`[10:36:28] [Server thread/INFO]: [Jobs] Enabling Jobs v4.15.3
[10:36:28] [Server thread/INFO]: [Jobs] PlaceholderAPI hooked.
[10:36:28] [Server thread/INFO]: PlaceholderAPI was found - Enabling capabilities.
[10:36:30] [Server thread/INFO]: [Jobs] Loaded 8 titles!
[10:36:30] [Server thread/INFO]: [Jobs] Loaded 75 protected blocks timers!
[10:36:30] [Server thread/INFO]: [Jobs] Loaded 995 custom item names!
[10:36:30] [Server thread/INFO]: [Jobs] Loaded 67 custom entity names!
[10:36:30] [Server thread/INFO]: [Jobs] Loaded 2 custom MythicMobs names!
[10:36:30] [Server thread/INFO]: [Jobs] Loaded 37 custom enchant names!
[10:36:30] [Server thread/INFO]: [Jobs] Loaded 16 custom color names!
[10:36:30] [Server thread/INFO]: [Jobs] Loaded 4 shop items!
[10:36:30] [Server thread/WARN]: java.io.FileNotFoundException: plugins/Jobs/locale/messages_EN.yml (No such file or directory)
[10:36:30] [Server thread/WARN]: at java.io.FileInputStream.open0(Native Method)
[10:36:30] [Server thread/WARN]: at java.io.FileInputStream.open(FileInputStream.java:195)
[10:36:30] [Server thread/WARN]: at java.io.FileInputStream.<init>(FileInputStream.java:138)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.config.YmlMaker.reloadConfig(YmlMaker.java:37)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.config.YmlMaker.getConfig(YmlMaker.java:53)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.i18n.Language.reload(Language.java:47)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:797)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:499)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:714)
[10:36:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:36:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[10:36:30] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[10:36:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[10:36:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[10:36:30] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456)
[10:36:30] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266)
[10:36:30] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783)
[10:36:30] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[10:36:30] [Server thread/WARN]: java.lang.IllegalArgumentException: Stream cannot be null
[10:36:30] [Server thread/WARN]: at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[10:36:30] [Server thread/WARN]: at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:207)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.config.YmlMaker.reloadConfig(YmlMaker.java:42)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.config.YmlMaker.getConfig(YmlMaker.java:53)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.i18n.Language.reload(Language.java:47)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.reload(Jobs.java:797)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.startup(Jobs.java:499)
[10:36:30] [Server thread/WARN]: at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:714)
[10:36:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:36:30] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[10:36:30] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[10:36:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[10:36:30] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[10:36:30] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456)
[10:36:30] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266)
[10:36:30] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783)
[10:36:30] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[10:36:30] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.`
```
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.15.1

**Comment by montlikadani** [comment]
Update to 4.15.3

**Comment by JohnPolyStriker** [comment]
It is 4.15.3 "[Jobs] Enabling Jobs v4.15.3"

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/8f067f4646e755b5138228c5eaea716d981289ae
