### ISSUE TITLE
Nullpointer Exception

### ISSUE THREAD

**Issue by banit** [Zrips/Jobs#670]
Using Jobs for multiple Servers connected via MySQL Database.
After Converting to correct Storage System all will work fine until Server Restart happens. Afterwards i get for every User joining a Server this Exception. And there is no Sync between the Servers.

WARN 21:11:21
[Jobs]: Task #201287 for Jobs v4.15.4 generated an exception
Console 21:11:21
java.lang.NullPointerException: null
at com.gamingmesh.jobs.dao.JobsDAO.getAllJobs(JobsDAO.java:624) ~[?:?]
at com.gamingmesh.jobs.dao.JobsDAO.loadFromDao(JobsDAO.java:1781) ~[?:?]
at com.gamingmesh.jobs.PlayerManager.playerJoin(PlayerManager.java:187) ~[?:?]
at com.gamingmesh.jobs.listeners.JobsListener$1.run(JobsListener.java:198) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-93]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-93]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-93]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-93]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-93]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-93]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

Paper 87, Jobs 4.15.4 
[Jobs.zip](https://github.com/Zrips/Jobs/files/4188108/Jobs.zip)
My Jobs Configs.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/7271bda0c592025959d3cc2d9343eb3ef6d98a61
