### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Lazulio** [Zrips/Jobs#685]
***Plugin was running fine and everything was working until a scheduled restart when I received the error below, no changes were made to the configuration or any other server properties.**

---

```
####################
## 02.03 16:00:15 [Server] WARN java.lang.NullPointerException
02.03 16:00:15 [Server] WARN at com.gamingmesh.jobs.config.ShopManager.load(ShopManager.java:319)
02.03 16:00:15 [Server] WARN at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:392)
02.03 16:00:15 [Server] WARN at com.gamingmesh.jobs.Jobs.reload(Jobs.java:798)
02.03 16:00:15 [Server] WARN at com.gamingmesh.jobs.Jobs.startup(Jobs.java:506)
02.03 16:00:15 [Server] WARN at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:713)
02.03 16:00:15 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
02.03 16:00:15 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
02.03 16:00:15 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
02.03 16:00:15 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
02.03 16:00:15 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
02.03 16:00:15 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
02.03 16:00:15 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
02.03 16:00:15 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
02.03 16:00:15 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
02.03 16:00:15 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
02.03 16:00:15 [Server] WARN at java.lang.Thread.run(Thread.java:748)
02.03 16:00:15 [Server] INFO There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled. ##
####################
```

**Spigot** 

**1.12.2**

**Comment by montlikadani** [comment]
You have missconfigured shopItems file, which is causing this error. If you don't know how to fix, then reset the file.
