### ISSUE TITLE
java.lang.IllegalStateException: UserBalanceUpdateEvent may only be triggered synchronously - even though money/income is disabled.

### ISSUE THREAD

**Issue by Abbnoxious** [Zrips/Jobs#688]
Every time something is killed by a player with a Job, the error below pops up in console.

I have money and points disabled in generalConfig. The only thing that's enabled is exp. From what I understand, if I have every Kill etc. action in jobConfig set to `income: 0` this shouldn't be happening.
Relatively new to this stuff though so bear with me. Is there something I'm missing here? Why is this error appearing if economy and income earning are disabled? Thanks in advance for any assistance provided!

Edit: thought I should mention that EXP gain is working just fine and all that I want to use at the moment.

---

```
03.03 17:10:29 [Server] WARN Plugin Jobs v4.15.5 generated an exception while executing task 314
03.03 17:10:29 [Server] INFO java.lang.IllegalStateException: UserBalanceUpdateEvent may only be triggered synchronously.
03.03 17:10:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:547) ~[patched_1.15.2.jar:git-Paper-121]
03.03 17:10:29 [Server] INFO at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
03.03 17:10:29 [Server] INFO at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
03.03 17:10:29 [Server] INFO at com.earth2me.essentials.api.Economy.substract(Economy.java:198) ~[?:?]
03.03 17:10:29 [Server] INFO at com.earth2me.essentials.api.Economy.subtract(Economy.java:190) ~[?:?]
03.03 17:10:29 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Essentials.withdrawPlayer(Economy_Essentials.java:107) ~[?:?]
03.03 17:10:29 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.withdrawPlayer(AbstractEconomy.java:40) ~[?:?]
03.03 17:10:29 [Server] INFO at com.gamingmesh.jobs.economy.VaultEconomy.withdrawPlayer(VaultEconomy.java:43) ~[?:?]
03.03 17:10:29 [Server] INFO at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:43) ~[?:?]
03.03 17:10:29 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-121]
03.03 17:10:29 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-121]
03.03 17:10:29 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-121]
03.03 17:10:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
03.03 17:10:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
03.03 17:10:29 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

---

**Server Type (Spigot/Paperspigot/etc):**  Paper 121 (1.15.2)

**Server Version (using `/ver`):** 1.15.2

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/422#issuecomment-495977567
