### ISSUE TITLE
Console Error - Dont know what is this come from

### ISSUE THREAD

**Issue by NikolaiCinotti** [Zrips/Jobs#692]
Dont know where this come from.
https://hastebin.com/ebitotafew.cs

But this keep spamming my entire console.

(im not doing anything but my player are playing, so I cant know what is happening with this console error, none players has complain)

```
06.03 23:36:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
06.03 23:36:22 [Server] INFO Caused by: java.lang.NullPointerException
06.03 23:36:22 [Server] Server thread/ERROR Could not pass event BlockBreakEvent to Jobs v4.15.5
06.03 23:36:22 [Server] INFO org.bukkit.event.EventException: null
06.03 23:36:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
06.03 23:36:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
06.03 23:36:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
06.03 23:36:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
```

**Comment by montlikadani** [comment]
Please compress the server log file and send here.
