### ISSUE TITLE
MythicMobs-4.9.0

### ISSUE THREAD

**Issue by zz2423257** [Zrips/Jobs#701]
***Description of issue:**

--- MythicMobs

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
``` 

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
[01:57:15 ERROR]: Could not pass event InventoryClickEvent to Jobs v4.15.5
java.lang.NullPointerException: null
        at com.gamingmesh.jobs.hooks.MythicMobs.MythicMobs4.getDisplayName(MythicMobs4.java:67) ~[?:?]
        at com.gamingmesh.jobs.config.NameTranslatorManager.Translate(NameTranslatorManager.java:124) ~[?:?]
        at com.gamingmesh.jobs.config.NameTranslatorManager.Translate(NameTranslatorManager.java:33) ~[?:?]
        at com.gamingmesh.jobs.container.JobInfo.getRealisticName(JobInfo.java:83) ~[?:?]
        at com.gamingmesh.jobs.Gui.GuiManager.openJobsBrowseGUI(GuiManager.java:228) ~[?:?]
        at com.gamingmesh.jobs.Gui.GuiManager$1.click(GuiManager.java:147) ~[?:?]
        at com.gamingmesh.jobs.CMIGUI.GUIManager.processClick(GUIManager.java:215) ~[?:?]
        at com.gamingmesh.jobs.CMIGUI.GUIListener.onInventoryClick(GUIListener.java:110) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1117.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-143]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2333) ~[?:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
---

**Server Type (Spigot/Paperspigot/etc):**   paper

**Server Version (using `/ver`):**  1.15.2

**Relevant plugins (Delete if this isn't needed):** Jobs/MythicMobs

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/9fa5dfb2aaa3989941cc4409c2182551256fdf06
