### ISSUE TITLE
Could not pass event EntityDeathEvent to Jobs v4.15.6

### ISSUE THREAD

**Issue by metalshark** [Zrips/Jobs#729]
Could not pass event EntityDeathEvent to Jobs v4.15.6
---
```
java.lang.NullPointerException: null
at com.gamingmesh.jobs.listeners.JobsPaymentListener.onEntityDeath(JobsPaymentListener.java:1126) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor467.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-158]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-158]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-158]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-158]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-158]
at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-158]
at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-158]
at net.minecraft.server.v1_15_R1.EntityTameableAnimal.die(SourceFile:222) ~[patched_1.15.2.jar:git-Paper-158]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:118) ~[patched_1.15.2.jar:git-Paper-158]
at com.gmail.nossr50.skills.taming.TrackedTamingEntity.run(TrackedTamingEntity.java:46) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-158]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-158]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-158]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-158]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-158]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-158]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

---

Paper

git-Paper-158 (MC: 1.15.2)

**Comment by montlikadani** [comment]
Update the plugin to the latest (v4.15.7) version. This already been fixed.
