### ISSUE TITLE
Exception in BufferedPaymentThread, stopping economy payments!

### ISSUE THREAD

**Issue by bartyrealms** [Zrips/Jobs#738]
**Description of issue:**
Jobs payments stop randomly.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[16:21:24] [Jobs-BufferedPaymentThread/WARN]: java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (1.000000376)
[16:21:24] [Jobs-BufferedPaymentThread/WARN]:     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
[16:21:24] [Jobs-BufferedPaymentThread/WARN]:     at org.bukkit.craftbukkit.v1_15_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158)
[16:21:24] [Jobs-BufferedPaymentThread/WARN]:     at com.gamingmesh.jobs.config.BossBarManager.ShowJobProgression(BossBarManager.java:116)
[16:21:24] [Jobs-BufferedPaymentThread/WARN]:     at com.gamingmesh.jobs.config.BossBarManager.ShowJobProgression(BossBarManager.java:44)
[16:21:24] [Jobs-BufferedPaymentThread/WARN]:     at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:207)
[16:21:24] [Jobs-BufferedPaymentThread/WARN]:     at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
[16:21:24] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Exception in BufferedPaymentThread, stopping economy payments!
[16:21:24] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.
```

---

**Server Type (Spigot/Paperspigot/etc):** git-Tuinity-"8499889"

**Server Version (using `/ver`):**  1.15.2

**Comment by montlikadani** [comment]
You using an oldest version of Jobs. Update it firstly, because this has been fixed.
