### ISSUE TITLE
java.lang.NullPointerException om.gamingmesh.jobs.container.ExploreChunk.deserializeNames(ExploreChunk.java:110)

### ISSUE THREAD

**Issue by apatuka** [Zrips/Jobs#749]
***Description of issue:**
Plugin is not loading
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:00:00] [Server thread/WARN]: java.lang.NullPointerException
[13:00:00] [Server thread/WARN]:        at com.gamingmesh.jobs.container.ExploreChunk.deserializeNames(ExploreChunk.java:110)
[13:00:00] [Server thread/WARN]:        at com.gamingmesh.jobs.config.ExploreManager.load(ExploreManager.java:117)
[13:00:00] [Server thread/WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.loadExplore(JobsDAO.java:2482)
[13:00:00] [Server thread/WARN]:        at com.gamingmesh.jobs.config.ExploreManager.load(ExploreManager.java:48)
[13:00:00] [Server thread/WARN]:        at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:955)
[13:00:00] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:00:00] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:00:00] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[13:00:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[13:00:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[13:00:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[13:00:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[13:00:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[13:00:00] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[13:00:00] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
```

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 1.14.2
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-164 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment]
You using and oldest version of Jobs please update.
