### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by SliderKP** [Zrips/Jobs#768]
***Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
[14:23:09 ERROR]: Could not pass event BlockBreakEvent to Jobs v4.15.7
java.lang.NullPointerException: null


**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/m3uzAE49
```

---

**Server Type (Spigot/Paperspigot/etc):**  paperspigot 1.15

**Server Version (using `/ver`):**
http://puu.sh/FE2Cx/6d09407c78.png 

**Relevant plugins (Delete if this isn't needed):**

why air?
http://puu.sh/FE2G2/326b72feb1.png

**Comment by montlikadani** [comment]
You not included the full console error about jobs.

**Comment by SliderKP** [comment]
> You not included the full console error about jobs.

srry, my bad, thansk for your quicly answer !!!

https://pastebin.com/cCYHAMKh

**Comment by SliderKP** [comment]
i replaced sapling with oak_sapling in job config and i get this error:

[14:32:51 INFO]: [Jobs] Buffered payment thread shutdown.
[14:32:51 INFO]: [Jobs] Loaded 8 titles!
[14:32:51 INFO]: [Jobs] Loaded 75 protected blocks timers!
[14:32:51 INFO]: [Jobs] Loaded 995 custom item names!
[14:32:51 INFO]: [Jobs] Loaded 67 custom entity names!
[14:32:51 INFO]: [Jobs] Loaded 2 custom MythicMobs names!
[14:32:51 INFO]: [Jobs] Loaded 38 custom enchant names!
[14:32:51 INFO]: [Jobs] Loaded 16 custom color names!
[14:32:51 INFO]: [Jobs] Loaded 4 shop items!
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Le?ador
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Minero
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Excavador
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Cazador
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Crafter
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Pescador
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Herrero
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Brewer
[14:32:51 INFO]: [Jobs] Loaded 1 quests for Enchanter
[14:32:51 INFO]: [Jobs] Loaded 9 jobs!
[14:32:51 INFO]: [Jobs] Explorer job manager registered!
[14:32:51 INFO]: [Jobs] Loaded 143 furnaces and 16 brewing stands for reassigning.
[14:32:51 INFO]: [Jobs] Started database save task.
[14:32:51 INFO]: El conjuro ha sido aplicado.
[14:32:51 INFO]: [Jobs] Started buffered payment thread.
[14:32:53 ERROR]: Could not pass event FurnaceSmeltEvent to Jobs v4.15.7
java.lang.NullPointerException: null
        at com.gamingmesh.jobs.container.JobsPlayer.getQuestProgressions(JobsPlayer.java:1052) ~[?:?]
        at com.gamingmesh.jobs.Jobs.checkDailyQuests(Jobs.java:793) ~[?:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:947) ~[?:?]
        at com.gamingmesh.jobs.Jobs.action(Jobs.java:811) ~[?:?]
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onFurnaceSmelt(JobsPaymentListener.java:1035) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor596.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[overcraft.jar:git-Paper-103]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[overcraft.jar:git-Paper-103]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[overcraft.jar:git-Paper-103]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[overcraft.jar:git-Paper-103]
        at net.minecraft.server.v1_15_R1.TileEntityFurnace.burn(TileEntityFurnace.java:345) ~[overcraft.jar:git-Paper-103]
        at net.minecraft.server.v1_15_R1.TileEntityFurnace.tick(TileEntityFurnace.java:298) ~[overcraft.jar:git-Paper-103]
        at net.minecraft.server.v1_15_R1.World.tickBlockEntities(World.java:776) ~[overcraft.jar:git-Paper-103]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:523) ~[overcraft.jar:git-Paper-103]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[overcraft.jar:git-Paper-103]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[overcraft.jar:git-Paper-103]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[overcraft.jar:git-Paper-103]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[overcraft.jar:git-Paper-103]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by SliderKP** [comment]
solved, thanks for your answer anyway !
