### ISSUE TITLE
NaN Error while DynamicPayment is true

### ISSUE THREAD

**Issue by JaCyGa** [Zrips/Jobs#774]
Whenever I set the option for dynamic payment to true I get a NaN error, I set it back to false the plugin runs without problems.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

```
[16:36:35] [Jobs-BufferedPaymentThread/WARN]: java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (NaN)
[16:36:35] [Jobs-BufferedPaymentThread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
[16:36:35] [Jobs-BufferedPaymentThread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158)
[16:36:35] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.config.BossBarManager.ShowJobProgression(BossBarManager.java:125)
[16:36:35] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.config.BossBarManager.ShowJobProgression(BossBarManager.java:44)
[16:36:35] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:207)
[16:36:35] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
[16:36:35] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Exception in BufferedPaymentThread, stopping economy payments!
[16:36:35] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
  DynamicPayment:
    # Do you want to use dynamic payment dependent on how many players already working for jobs?
    # This can help automatically lift up payments for not so popular jobs and lower for most popular ones
    use: false
    # totalworkers: The total number of players on the server who have jobs
    # totaljobs: The number of jobs that are enabled
    # jobstotalplayers: The number of people in that particular job
    # Exponential equation: totalworkers / totaljobs / jobstotalplayers - 1
    # Linear equation: ((totalworkers / totaljobs) - jobstotalplayers)/10.0
    equation: totalworkers / totaljobs / jobstotalplayers - 1
    MaxPenalty: 50.0
    MaxBonus: 300.0
```

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
 1.15.2

**Comment by montlikadani** [comment]
The console error has been fixed in [commit](https://github.com/Zrips/Jobs/commit/c4d0d0101a9f986b17e30718d157d2bdd5694bba)

Are you sure you set the DynamicPayment to true? Because that is not enabled.

**Comment by JaCyGa** [comment]
yes i can set them true in the config but when i do that the NaN Warning occured

**Comment by JaCyGa** [comment]
[18:22:29 WARN]: java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (NaN)

[18:22:29 WARN]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)

[18:22:29 WARN]: at org.bukkit.craftbukkit.v1_15_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158)

[18:22:29 WARN]: at com.gamingmesh.jobs.config.BossBarManager.ShowJobProgression(BossBarManager.java:125)

[18:22:29 WARN]: at com.gamingmesh.jobs.config.BossBarManager.ShowJobProgression(BossBarManager.java:44)

[18:22:29 WARN]: at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:207)

[18:22:29 WARN]: at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)

[18:22:29 INFO]: [Jobs] Exception in BufferedPaymentThread, stopping economy payments!

[18:22:29 INFO]: [Jobs] Buffered payment thread shutdown.

**Comment by Zrips** [comment]
3e50e3ae5b457fb254c974223fa7acca3a7ecfb9
