### ISSUE TITLE
Bug of scoreboard

### ISSUE THREAD

**Issue by epicfail76** [Zrips/Jobs#777]
***Description of issue:**
When we use /jobs top Mineur we have a error on console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## [13:01:29] [Server thread/INFO]: epicfail76 issued server command: /jobs top Mineur
[13:01:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin Jobs v4.15.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-165]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-165]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1053) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1046) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1016) ~[patched_1.15.2.jar:git-Paper-165]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:939) ~[patched_1.15.2.jar:git-Paper-165]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_15_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:137) ~[patched_1.15.2.jar:git-Paper-165]
        at org.bukkit.craftbukkit.v1_15_R1.scoreboard.CraftObjective.getName(CraftObjective.java:29) ~[patched_1.15.2.jar:git-Paper-165]
        at com.gamingmesh.jobs.stuff.CMIScoreboardManager.RunScheduler(CMIScoreboardManager.java:40) ~[?:?]
        at com.gamingmesh.jobs.stuff.CMIScoreboardManager.addNew(CMIScoreboardManager.java:57) ~[?:?]
        at com.gamingmesh.jobs.commands.list.top.perform(top.java:97) ~[?:?]
        at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:98) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-165]
 ##
####################
---

**Server Type (Spigot/Paperspigot/etc):** 
spigot

**Server Version (using `/ver`):** 
1.15.2

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/338d306fe7ba411b0c65b2424f45d958a29f483d
