### ISSUE TITLE
Exception in BufferedPaymentThread, stopping economy payments

### ISSUE THREAD

**Issue by ThomasLETELLIER** [Zrips/Jobs#782]
***Description of issue:**
Everything was fine with Jobs, but just got an error, that seems to be a DB connection (MySQL) issue.
The bossbar/texts doesn't appear but with /jobs stats I know that I got some exp as doing jobs.
But everything's about money doesn't appear.
It already happens twice, since last Saturday. Had to restart the server entirely.
/reload doesn't do anything. /jobs reload don't too.

---

**ERROR:**
```
[01:52:58] [Jobs-BufferedPaymentThread/WARN]: java.lang.NullPointerException
[01:52:58] [Jobs-BufferedPaymentThread/WARN]:   at com.gamingmesh.jobs.config.BossBarManager.ShowJobProgression(BossBarManager.java:41)
[01:52:58] [Jobs-BufferedPaymentThread/WARN]:   at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:207)
[01:52:58] [Jobs-BufferedPaymentThread/WARN]:   at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
[01:52:58] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Exception in BufferedPaymentThread, stopping economy payments!
[01:52:58] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.
```

---

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 4.15.9

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/572e77b36fed3b4312327b308928c7bec905eaa1
