### ISSUE TITLE
 Players don't earn money

### ISSUE THREAD

**Issue by joecwhiter** [Zrips/Jobs#789]
i dont know if it only happens to me but i just installed the jobs reborn 1.15.10 plugin and it paired correctly with the vault, players can join the jobs but when they perform an action of their job this comes to me in the console
---
WARN [Jobs] Plugin Jobs v4.15.10 generated an exception while executing task 701
```
10.05 15:06:16 [Server] WARN [Jobs] Plugin Jobs v4.15.10 generated an exception while executing task 701
10.05 15:06:16 [Server] INFO  java.lang.RuntimeException: Essentials API is called before Essentials is loaded.
10.05 15:06:16 [Server] INFO at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:66) ~[?:?]
10.05 15:06:16 [Server] INFO at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:131) ~[?:?]
10.05 15:06:16 [Server] INFO at com.earth2me.essentials.api.Economy.substract(Economy.java:349) ~[?:?]
10.05 15:06:16 [Server] INFO at com.earth2me.essentials.api.Economy.subtract(Economy.java:329) ~[?:?]
10.05 15:06:16 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Essentials.withdrawPlayer(Economy_Essentials.java:107) ~[?:?]
10.05 15:06:16 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.withdrawPlayer(AbstractEconomy.java:40) ~[?:?]
10.05 15:06:16 [Server] INFO at com.gamingmesh.jobs.economy.VaultEconomy.withdrawPlayer(VaultEconomy.java:43) ~[?:?]
10.05 15:06:16 [Server] INFO at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:43) ~[?:?]
10.05 15:06:16 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[CraftTask.class:492fbbf]
10.05 15:06:16 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:492fbbf]
10.05 15:06:16 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:492fbbf]
10.05 15:06:16 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
10.05 15:06:16 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
10.05 15:06:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
10.05 15:06:18 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.78
10.05 15:06:18 [Server] INFO CONSOLE issued server command: /list 
10.05 15:06:18 [Server] INFO There are 3 out of maximum 20 players online.
10.05 15:06:18 [Server] INFO admi: [Admi]Joe
10.05 15:06:18 [Server] INFO novato: [Novato]AdroCRAFT, [Novato]asbel 62
10.05 15:06:51 [Server] WARN [Jobs] Plugin Jobs v4.15.10 generated an exception while executing task 706
10.05 15:06:51 [Server] INFO  java.lang.RuntimeException: Essentials API is called before Essentials is loaded.
10.05 15:06:51 [Server] INFO at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:66) ~[?:?]
10.05 15:06:51 [Server] INFO at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:131) ~[?:?]
10.05 15:06:51 [Server] INFO at com.earth2me.essentials.api.Economy.substract(Economy.java:349) ~[?:?]
10.05 15:06:51 [Server] INFO at com.earth2me.essentials.api.Economy.subtract(Economy.java:329) ~[?:?]
10.05 15:06:51 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Essentials.withdrawPlayer(Economy_Essentials.java:107) ~[?:?]
10.05 15:06:51 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.withdrawPlayer(AbstractEconomy.java:40) ~[?:?]
10.05 15:06:51 [Server] INFO at com.gamingmesh.jobs.economy.VaultEconomy.withdrawPlayer(VaultEconomy.java:43) ~[?:?]
10.05 15:06:51 [Server] INFO at com.gamingmesh.jobs.tasks.BufferedPaymentTask.run(BufferedPaymentTask.java:43) ~[?:?]
10.05 15:06:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[CraftTask.class:492fbbf]
10.05 15:06:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:492fbbf]
10.05 15:06:51 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:492fbbf]
10.05 15:06:51 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
10.05 15:06:51 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
10.05 15:06:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

I didn't change the configs all is default
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

Spigot i'm using magma for mods and plugins 

1.12.2-R0.1-SNAPSHOT 492fbbf (MC: 1.12.2)

Vault, EssX 1.17.2.78, jobs reborn 1.15.10
![error](https://user-images.githubusercontent.com/65084504/81505032-af3ffc80-92ba-11ea-84d7-9f303650c44d.jpg)

**Comment by montlikadani** [comment]
> java.lang.RuntimeException: Essentials API is called before Essentials is loaded.

It says, essentials is not loaded correctly. So you have to reload your server.

**Comment by joecwhiter** [comment]
ok i'll try

**Comment by joecwhiter** [comment]
no, i just restarted the server and the problem continues

**Comment by montlikadani** [comment]
Firstly update the Essentials to the dev version from https://ci.ender.zone/job/EssentialsX/

**Comment by joecwhiter** [comment]
I just installed the essentialsx update and restarted the server and the problem persists

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/1942013d27b4be0ec2b242a85a1dd695c11ba0e5
