### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Jobs#818]
Hi, I have error in log.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:00:21] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to Jobs v4.15.11
java.util.NoSuchElementException: null
	at org.bukkit.craftbukkit.v1_15_R1.util.UnsafeList$Itr.next(UnsafeList.java:263) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.Chunk.a(Chunk.java:931) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.World.getEntities(World.java:1231) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1239) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1225) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1216) ~[patched_1.15.2.jar:git-Paper-345]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onArmorstandPlace(JobsPaymentListener.java:1335) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor427.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-345]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:639) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:560) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1266) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1174) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.addEntity(CraftWorld.java:1952) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1959) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1543) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnEntity(CraftWorld.java:769) ~[patched_1.15.2.jar:git-Paper-345]
	at me.qKing12.HandyOrbs.Orbs.Orb$1.lambda$run$0(Orb.java:219) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-345]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1263) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1180) ~[patched_1.15.2.jar:git-Paper-345]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:969) ~[patched_1.15.2.jar:git-Paper-345]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

---

**Server Type (Spigot/Paperspigot/etc):**  Paper
 
**Server Version (using `/ver`):**  345

**Jobs version:** Jobs4.15.11

**Comment by montlikadani** [comment]
Try to update the Paper to 348

**Comment by Volgeop** [comment]
Ok, probably fixed, it happens again, will let you know
