### ISSUE TITLE
Jobs console error

### ISSUE THREAD

**Issue by TobalX** [Zrips/Jobs#822]
***Description of issue:**

The error is spamming my console and i don't know why, i haven't configured the jobs i just have changed the names of the jobs, and also i have another plugin that is UltimateTimber.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

[17:23:44 ERROR]: Could not pass event BlockPlaceEvent to Jobs v4.15.11
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[survival.jar:git-TacoSpigot-"95870a93"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[survival.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[survival.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [survival.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [survival.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:127) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:160) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [survival.jar:git-TacoSpigot-"95870a93"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [survival.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [survival.jar:git-TacoSpigot-"95870a93"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
```

**Server Type (Spigot/Paperspigot/etc):** 

TacoSpigot 1.8.8-R0.2-SNAPSHOT 

**Server Version (using `/ver`):** 

git-TacoSpigot-"95870a93" MC:1.8.8

**Relevant plugins (Delete if this isn't needed):**
UltimateTimber

**Comment by montlikadani** [comment]
Send here the full error, not just the half.

**Comment by TobalX** [comment]
That's everything related to the error that i could recover from the logs! :( What should i do?

**Comment by montlikadani** [comment]
> Caused by: java.lang.NullPointerException

No, there is another error after this ^

**Comment by montlikadani** [comment]
Closing, due to there is no answer from the author.
