### ISSUE TITLE
[1.16.1] Unable to start Jobs reborn

### ISSUE THREAD

**Issue by mrfloris** [Zrips/Jobs#829]
Hey, someone had to report it :)

```
[04:10:40] [Server thread/INFO]: [Jobs] Enabling Jobs v4.15.11
[04:10:40] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16_R1
[04:10:40] [Server thread/ERROR]: Error occurred while enabling Jobs v4.15.11 (Is it up to date?)
java.lang.NullPointerException: null
	at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:785) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:632) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[04:10:40] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[04:10:40] [Server thread/INFO]: Done (14.956s)! For help, type "help"
```
```
>ver
[04:11:48] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[04:11:48] [Server thread/INFO]: Checking version, please wait...
[04:11:48] [Thread-7/INFO]: You are running the latest version
>
```

I hope this helps you guys get started on making jobs working on 1.16.1

**Comment by Blueeyestar** [comment]
When will the plugin come out publicly for download?

**Comment by mrfloris** [comment]
There[s a 4.15.12 version that's in Discord dev-release channel you can download and play/test with. It's only updated to work and load on 1.16.1, but the're nothing updated in regards to 1.16.1 in it yet from what i gather.

**Comment by TNTUP** [comment]
Safe to use? Usually dev builds tend to changes things so I'd prefer to be on the safe side for production use (currently just for testing yet)

**Comment by mrfloris** [comment]
The SpigotMC build is 4.15.11 at the moment, this is for 1.15.2.
The Discord dev-build is 4.15.12 at the moment, this is for 1.16.1 and loads. I run it live now.

They are dev builds, they're meant for testing, finding bugs, configuration tests, etc.  (but i run it live to find bugs faster for zrips)
