### ISSUE TITLE
4.16.0 dev disabled on startup

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#847]
***Description of issue:**
jobs plugin disabled on startup
---

[13:08:46] [Server thread/INFO]: [Jobs] Enabling Jobs v4.16.0
[13:08:46] [Server thread/INFO]: [Jobs] PlaceholderAPI hooked.
[13:08:47] [Server thread/INFO]: [Jobs] Loaded 8 titles!
[13:08:47] [Server thread/INFO]: [Jobs] Loaded 8 protected blocks timers!
[13:08:47] [Server thread/INFO]: [Jobs] Loaded 1098 custom item names!
[13:08:47] [Server thread/INFO]: [Jobs] Loaded 71 custom entity names!
[13:08:47] [Server thread/INFO]: [Jobs] Loaded 2 custom MythicMobs names!
[13:08:47] [Server thread/INFO]: [Jobs] Loaded 38 custom enchant names!
[13:08:47] [Server thread/INFO]: [Jobs] Loaded 16 custom color names!
[13:08:47] [Server thread/INFO]: [Jobs] Loaded 14 top list signs
[13:08:47] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[13:08:47] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.CMIMaterial.get(CMIMaterial.java:1396)
[13:08:47] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ConfigManager.loadJobSettings(ConfigManager.java:1232)
[13:08:47] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ConfigManager.reload(ConfigManager.java:278)
[13:08:47] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:757)
[13:08:47] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:441)
[13:08:47] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:673)
[13:08:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:08:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[13:08:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[13:08:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500)
[13:08:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414)
[13:08:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[13:08:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[13:08:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[13:08:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[13:08:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[13:08:47] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[13:08:47] [Server thread/INFO]: [Jobs] Plugin has been disabled successfully.

**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
version 79
**Relevant plugins (Delete if this isn't needed):**
jobs 4.16.0 dev version

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/e630aee35cf29f88c1c784b66b57afebee821ecb
