### ISSUE TITLE
Error Buffered payment thread shutdown. Miners are not getting paid.

### ISSUE THREAD

**Issue by notbike** [Zrips/Jobs#858]
***Description of issue:**

plugin doesn't pay Miners when they breaks blocks. and the following error popped out.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: java.lang.NullPointerException
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.IDFinder.getID(IDFinder.java:139)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.TNEAPI.hasAccount(TNEAPI.java:182)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.hasAccount(Economy_TheNewEconomy.java:67)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.depositPlayer(Economy_TheNewEconomy.java:188)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.depositPlayer(Economy_TheNewEconomy.java:182)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:158)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
[19:50:02] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Exception in BufferedPaymentThread, stopping economy payments!
[19:50:02] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.


https://pastebin.com/g2UU3uNk
for easier view

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
mysql:
  username: root
  password: 
  hostname: localhost:3306
  database: jobs
  table-prefix: jobs_
  verify-server-certificate: false
  use-ssl: false
  auto-reconnect: true

no sure if it's a problem with MySQL
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.16.1
**Relevant plugins (Delete if this isn't needed):**

Jobs reborn ver. 4.16.0
Economy plugin is The New Economy

**Comment by montlikadani** [comment]
```
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: java.lang.NullPointerException
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.IDFinder.getID(IDFinder.java:139)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.TNEAPI.hasAccount(TNEAPI.java:182)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.hasAccount(Economy_TheNewEconomy.java:67)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.depositPlayer(Economy_TheNewEconomy.java:188)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.depositPlayer(Economy_TheNewEconomy.java:182
```
So this is The New Economy issue not Jobs.
