### ISSUE TITLE
SQLite Bug/Error

### ISSUE THREAD

**Issue by Braynblocks** [Zrips/Jobs#870]
Description of issue: I am getting this error in my console. It's something about SQLite Exception. 

---
CONSOLE ERROR :
[05:03:47 WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: jobNames.name)
[05:03:47 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1010)
[05:03:47 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1022)
[05:03:47 WARN]:        at org.sqlite.core.DB.execute(DB.java:861)
[05:03:47 WARN]:        at org.sqlite.core.DB.executeUpdate(DB.java:902)
[05:03:47 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[05:03:47 WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.recordNewJobName(JobsDAO.java:1129)
[05:03:47 WARN]:        at com.gamingmesh.jobs.dao.JobsDAO.loadAllJobsNames(JobsDAO.java:1171)
[05:03:47 WARN]:        at com.gamingmesh.jobs.Jobs.reload(Jobs.java:760)
[05:03:47 WARN]:        at com.gamingmesh.jobs.Jobs.reload(Jobs.java:712)
[05:03:47 WARN]:        at com.gamingmesh.jobs.commands.list.reload.perform(reload.java:14)
[05:03:47 WARN]:        at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:99)
[05:03:47 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[05:03:47 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[05:03:47 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005)
[05:03:47 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[05:03:47 WARN]:        at java.lang.Thread.run(Unknown Source)

Server: Spigot
Version: 1.16.1

**Comment by montlikadani** [comment]
- Did you converted your database before?
- Does you upgraded the jobs plugin from old versions?
- Did you modified the database before this error appeared?

**Comment by Braynblocks** [comment]
Did you converted your database before?
- No, I haven't. I just deleted and added new jobs.

Does you upgraded the jobs plugin from old versions?
- Nope, I'm using the latest one.

Did you modified the database before this error appeared?
- No, not at all. I even tried to reset the database by deleting it and resetting it. This error still shows
