### ISSUE TITLE
1.12 support

### ISSUE THREAD

**Issue by DmitryRendov** [Zrips/Jobs#94]
Some old methods are deprecated since 1.12. So on the latest spigot I'm getting well known issue:
```
[14:34:56] [Server thread/ERROR]: Error occurred while enabling Jobs v3.9.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at com.gamingmesh.jobs.config.YmlMaker.reloadConfig(YmlMaker.java:57) ~[?:?]
        at com.gamingmesh.jobs.config.YmlMaker.getConfig(YmlMaker.java:76) ~[?:?]
        at com.gamingmesh.jobs.i18n.Language.reload(Language.java:41) ~[?:?]
        at com.gamingmesh.jobs.Jobs.reload(Jobs.java:555) ~[?:?]
        at com.gamingmesh.jobs.Jobs.startup(Jobs.java:489) ~[?:?]
        at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:758) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

```
 
Could you please have a look? thank you for such great plugin!

**Comment by DmitryRendov** [comment]
@Zrips nice hotfix, but still not fully valid ((
`[16:57:59] [Server thread/ERROR]: Cannot load configuration from stream
java.io.IOException: Stream closed
        at sun.nio.cs.StreamDecoder.ensureOpen(StreamDecoder.java:46) ~[?:1.8.0_91]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:148) ~[?:1.8.0_91]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_91]
        at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_91]
        at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_91]
        at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_91]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:154) ~[spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:207) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at com.gamingmesh.jobs.config.YmlMaker.reloadConfig(YmlMaker.java:56) [Jobs3.9.3.jar:?]
        at com.gamingmesh.jobs.config.YmlMaker.getConfig(YmlMaker.java:75) [Jobs3.9.3.jar:?]
        at com.gamingmesh.jobs.i18n.Language.reload(Language.java:41) [Jobs3.9.3.jar:?]
        at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:792) [Jobs3.9.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-survival-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
`

**Comment by Zrips** [comment]
Should be addressed with next build.
