### ISSUE TITLE
IllegalPluginAccessException: Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#95]
Jobs v3.9.3
Paper dev 1111 (Spigot 1.12)

Exception on shutdown.

```
[10:02:55] [Jobs-BufferedPaymentThread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[10:02:55] [Jobs-BufferedPaymentThread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413)
[10:02:55] [Jobs-BufferedPaymentThread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:148)
[10:02:55] [Jobs-BufferedPaymentThread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:122)
[10:02:55] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:190)
[10:02:55] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:55)
[10:02:55] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Exception in BufferedPaymentThread, stopping economy payments!
[10:02:55] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.
```

**Comment by montlikadani** [comment]
**Try update to the latest version.**
