### ISSUE TITLE
Jobs won't load

### ISSUE THREAD

**Issue by Arturitu12** [Zrips/Jobs#978]
***Description of issue:**
Hello i just completed file's config of Jobs' plugin and it won't load. I double checked and in files all ok. before config stock settings was working. Here's pastebin of logs and config files i've made. I though its becose i used Polish letters but when i erase itplugin still dont load.
---

**ERROR **
```
####################
## https://pastebin.com/gW1hanHR


 ##
####################
```

**CONFIG SECTION**
```

#####################################
## [jobConfig.txt](https://github.com/Zrips/Jobs/files/5437598/jobConfig.txt)
[generalConfig.txt](https://github.com/Zrips/Jobs/files/5437599/generalConfig.txt) ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
also i use jobs 4.16.2, vault 1.7.3, luckperms 5.1.75, essentialsx 2.18.0.11

**Comment by montlikadani** [comment]
Its describes
```
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
in 'string', line 562, column 7:
Name: Wegiel drzewny
^
```

**Comment by Arturitu12** [comment]
Oh man i've been blind or too tired let me check

**Comment by Arturitu12** [comment]
[11:50:28] [Server thread/INFO]: [Jobs] Loaded 8 titles!
[11:50:28] [Server thread/INFO]: [Jobs] Loaded 75 protected blocks timers!
[11:50:29] [Server thread/INFO]: [Jobs] Loaded 1097 custom item names!
[11:50:29] [Server thread/INFO]: [Jobs] Loaded 72 custom entity names!
[11:50:29] [Server thread/INFO]: [Jobs] Loaded 2 custom MythicMobs names!
[11:50:29] [Server thread/INFO]: [Jobs] Loaded 38 custom enchant names!
[11:50:29] [Server thread/INFO]: [Jobs] Loaded 16 custom color names!
[11:50:29] [Server thread/INFO]: [Jobs] Loaded 4 shop items!
[11:50:29] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
in 'string', line 567, column 9:
-msg [playerName] Zaliczono quest!
^
could not find expected ':'
in 'string', line 568, column 9:
RewardDesc:
^
[11:50:29] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.ConfigReader.getyml(ConfigReader.java:225)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.ConfigReader.<init>(ConfigReader.java:43)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ConfigManager.updateFile(ConfigManager.java:59)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ConfigManager.<init>(ConfigManager.java:53)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.getConfigManager(Jobs.java:192)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:734)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:423)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:650)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[11:50:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:50:29] [Server thread/WARN]: Caused by: while scanning a simple key
in 'string', line 567, column 9:
-msg [playerName] Zaliczono quest!
^
could not find expected ':'
in 'string', line 568, column 9:
RewardDesc:
^
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:464)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:278)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:530)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:208)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:398)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[11:50:29] [Server thread/WARN]: 	... 19 more
[11:50:29] [Server thread/INFO]: Failed to load jobConfig.yml! Backup have been saved into plugins/Jobs/FileBackups/2020-10-26 11-50-29 jobConfig.yml
[11:50:29] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
in 'string', line 567, column 9:
-msg [playerName] Zaliczono quest!
^
could not find expected ':'
in 'string', line 568, column 9:
RewardDesc:
^
[11:50:29] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.ConfigReader.getyml(ConfigReader.java:225)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.CMILib.ConfigReader.<init>(ConfigReader.java:43)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ConfigManager.updateFile(ConfigManager.java:59)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.config.ConfigManager.<init>(ConfigManager.java:53)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.getConfigManager(Jobs.java:192)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:734)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:423)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:650)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[11:50:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:50:29] [Server thread/WARN]: Caused by: while scanning a simple key
in 'string', line 567, column 9:
-msg [playerName] Zaliczono quest!
^
could not find expected ':'
in 'string', line 568, column 9:
RewardDesc:
^
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:464)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:278)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:530)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:208)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
[11:50:29] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:398)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[11:50:29] [Server thread/WARN]: 	... 19 more
[11:50:29] [Server thread/ERROR]: [Jobs] ==================== Jobs ====================
[11:50:29] [Server thread/ERROR]: [Jobs] Unable to load jobConfig.yml!
[11:50:29] [Server thread/ERROR]: [Jobs] Check your config for formatting issues!
[11:50:29] [Server thread/ERROR]: [Jobs] No jobs were loaded!
[11:50:29] [Server thread/ERROR]: [Jobs] Error: while scanning a simple key
in 'string', line 567, column 9:
-msg [playerName] Zaliczono quest!
^
could not find expected ':'
in 'string', line 568, column 9:
RewardDesc:
^
[11:50:29] [Server thread/ERROR]: [Jobs] ==============================================
[11:50:29] [Server thread/WARN]: java.lang.NullPointerException
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.getJob(Jobs.java:399)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.dao.JobsDAO.loadAllJobsNames(JobsDAO.java:1154)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.reload(Jobs.java:737)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.startup(Jobs.java:423)
[11:50:29] [Server thread/WARN]: 	at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:650)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[11:50:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[11:50:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[11:50:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:50:29] [Server thread/INFO]: There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.
[11:50:29] [Server thread/INFO]: [Jobs] Plugin has been disabled successfully.
I know it describes but how its dont work when i just copied quest config from one job and changed values?

**Comment by Arturitu12** [comment]
Why program excepts ":" where it should be?

**Comment by Arturitu12** [comment]
[jobConfig.txt](https://github.com/Zrips/Jobs/files/5438374/jobConfig.txt)
Here's my config file, maded by copying from default jobs and changing vaules, all in place what happening?

**Comment by montlikadani** [comment]
```yml
'2':
        Name: Wegiel-drzewny
        Objectives:
        - Smelt;charcoal;
        RewardCommands:
        - eco give [playerName] 100
        -msg [playerName] Zaliczono quest!
        RewardDesc:
        - Przepal 64 sztuki wegla drzewnego
        - Dostaniesz 100 Szoksww!
```
Put a space after the `-`
`- msg`

**Comment by montlikadani** [comment]
Also use online yaml validator which can help you.

**Comment by Arturitu12** [comment]
thx
