### ISSUE TITLE
IOException on startup

### ISSUE THREAD

**Issue by Eredrim** [Zrips/Jobs#98]
Hello,
I have a problem with the latest jobs version on spigot 1.12 (latest) on startup. The plugin works but I see this stack : 
```
[00:17:38 ERROR]: Cannot load configuration from stream
java.io.IOException: Stream closed
        at sun.nio.cs.StreamDecoder.ensureOpen(Unknown Source) ~[?:1.8.0_131]
        at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_131]
        at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_131]
        at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_131]
        at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_131]
        at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:154) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:207) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at com.gamingmesh.jobs.config.YmlMaker.reloadConfig(YmlMaker.java:56) [Jobs3.9.3.jar:?]
        at com.gamingmesh.jobs.config.YmlMaker.getConfig(YmlMaker.java:75) [Jobs3.9.3.jar:?]
        at com.gamingmesh.jobs.i18n.Language.reload(Language.java:41) [Jobs3.9.3.jar:?]
        at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:792) [Jobs3.9.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by Zrips** [comment]
Should be fixed with next build
